function test_ae_workflow_route_ownership()
%TEST_AE_WORKFLOW_ROUTE_OWNERSHIP Guard maintained AE production routes.

fprintf('Running AE workflow route-ownership test...\n');

repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
publicSolver = "lamb.models.acoustoelastic_iop_hgo.solveAcoustoelasticIOPHGOBranch";
advancedSolvers = [ ...
    "solveAcoustoelasticIOPHGOAtlasBranch", ...
    "lamb.models.acoustoelastic_iop_hgo.solvers.solveAcoustoelasticAtlasBranch"];
lowLevelOwners = [ ...
    "lamb.models.acoustoelastic_iop_hgo.tracking.aeFindAtlasLocalMinima", ...
    "lamb.models.acoustoelastic_iop_hgo.tracking.aeLinkAtlasBranches", ...
    "lamb.models.acoustoelastic_iop_hgo.tracking.aeSplitAtlasBranches", ...
    "lamb.models.acoustoelastic_iop_hgo.policies.aeSelectAtlasA0Branch", ...
    "lamb.models.acoustoelastic_iop_hgo.policies.aeApplyAtlasA0FallbackPolicy"];

mainAdapter = readRepoFile(repoRoot, 'app', 'main', ...
    'guiRunAcoustoelasticIOPHGOModel.m');
studyWorkflow = readRepoFile(repoRoot, 'studies', 'sensitivity', ...
    'acoustoelastic_iop_hgo', 'runAcoustoelasticSensitivity.m');
gridStudyWorkflow = readRepoFile(repoRoot, 'studies', 'sensitivity', ...
    'acoustoelastic_iop_hgo', 'runAcoustoelasticGridSensitivity.m');
fitEvaluator = readRepoFile(repoRoot, 'src', '+lamb', '+fitting', ...
    '+acoustoelastic_iop_hgo', 'aeEvaluateFitModel.m');
basicExample = readRepoFile(repoRoot, 'examples', ...
    'acoustoelastic_iop_hgo', 'basic', 'run_atlas_branch.m');
fitAdapter = readRepoFile(repoRoot, 'app', 'fitting', ...
    'guiFitAcoustoelasticIOPHGOSolver.m');

assert(contains(mainAdapter, publicSolver), ...
    'Main GUI AE adapter must call the maintained public solver.');
assert(contains(studyWorkflow, publicSolver), ...
    'AE sensitivity points must call the public solver.');
assert(contains(gridStudyWorkflow, publicSolver), ...
    'AE grid sensitivity points must call the public solver.');
assert(contains(fitEvaluator, publicSolver), ...
    'Maintained AE fitting evaluations must call the public solver.');
assert(contains(basicExample, publicSolver), ...
    'Maintained AE basic example must call the public solver.');
assert(contains(fitAdapter, "aeFitDispersionData"), ...
    'FitTool AE adapter must delegate optimization to aeFitDispersionData.');

productionText = readMatlabTree(fullfile(repoRoot, 'app')) + ...
    readMatlabTree(fullfile(repoRoot, 'src', '+lamb', '+fitting', ...
        '+acoustoelastic_iop_hgo')) + ...
    readMatlabTree(fullfile(repoRoot, 'examples', ...
        'acoustoelastic_iop_hgo', 'basic')) + ...
    readMatlabTree(fullfile(repoRoot, 'examples', ...
        'acoustoelastic_iop_hgo', 'fitting'));
for i = 1:numel(advancedSolvers)
    assert(~contains(productionText, advancedSolvers(i)), ...
        'Maintained AE production consumers must not call %s.', advancedSolvers(i));
end
solverPackage = fullfile(repoRoot, 'src', '+lamb', '+models', ...
    '+acoustoelastic_iop_hgo', '+solvers');
assert(isfile(fullfile(solverPackage, 'solveAcoustoelasticAtlasBranch.m')), ...
    'AE retired-route guard must target the maintained +solvers package.');
assert(~isfile(fullfile(solverPackage, 'solveAcoustoelasticIOPHGOAtlasBranch.m')), ...
    'The obsolete AE forwarding API must remain removed.');
for i = 1:numel(lowLevelOwners)
    assert(~contains(productionText, lowLevelOwners(i)), ...
        'Maintained AE production consumers must not call %s.', lowLevelOwners(i));
end

fprintf('AE workflow route-ownership test passed.\n');
end

function text = readRepoFile(repoRoot, varargin)
text = string(fileread(fullfile(repoRoot, varargin{:})));
end

function text = readMatlabTree(root)
assert(isfolder(root), 'Maintained MATLAB tree does not exist: %s', root);
files = dir(fullfile(root, '**', '*.m'));
assert(~isempty(files), 'Maintained MATLAB tree contains no MATLAB files: %s', root);
text = "";
for i = 1:numel(files)
    text = text + newline + string(fileread(fullfile(files(i).folder, files(i).name)));
end
end
