function test_runtime_measurement_output_schema()
%TEST_RUNTIME_MEASUREMENT_OUTPUT_SCHEMA Guard local runtime-evidence schema.

repoRoot = testRepositoryRoot(mfilename('fullpath'));
originalFolder = pwd;
cleanup = onCleanup(@()cd(originalFolder));
cd(tempdir);

result = measureTestRuntime("test_repository_root_utilities", ...
    'RepeatCount', 1, 'WriteCsv', false);
expectedColumns = { ...
    'Entrypoint', 'Path', 'EntryType', 'OwningArea', 'Category', ...
    'RepeatCountRequested', 'RepeatCountCompleted', 'Status', 'Passed', ...
    'ElapsedSecondsMedian', 'ElapsedSecondsMin', 'ElapsedSecondsMax', ...
    'ErrorIdentifier', 'ErrorMessage', 'HardTimeoutAvailable', ...
    'TimeoutSeconds', 'MeasuredAtCommit', 'MATLABRelease', 'Platform', 'Notes'};
assert(isequal(result.Properties.VariableNames, expectedColumns), ...
    'Runtime measurement table schema changed.');
assert(height(result) == 1 && result.Entrypoint == "test_repository_root_utilities", ...
    'Runtime schema fixture measured an unexpected entrypoint.');
assert(result.Passed && result.Status == "passed", ...
    'Runtime schema fixture must complete successfully.');

source = string(fileread(fullfile(repoRoot, 'tests', 'tooling', ...
    'measureTestRuntime.m')));
assert(contains(source, '"Results/test_runtime/test_runtime_measurements.csv"'), ...
    'Default runtime output must be repository-root-aware ignored evidence.');

fprintf('Runtime measurement output-schema contract passed.\n');
end
