repoRoot = testRepositoryRoot(mfilename('fullpath'));

assert(isfile(fullfile(repoRoot, 'startup.m')), ...
    'testRepositoryRoot should resolve a folder containing startup.m.');
assert(isfolder(fullfile(repoRoot, 'tests', 'runners')), ...
    'testRepositoryRoot should resolve the repository root, not a tests subfolder.');
assert(strcmp(testRepositoryRoot(fullfile(repoRoot, 'tests', 'run_all_smoke_tests.m')), repoRoot), ...
    'testRepositoryRoot should resolve root-level test wrappers.');
assert(strcmp(testRepositoryRoot(fullfile(repoRoot, 'tests', 'runners', 'run_core_smoke_tests.m')), repoRoot), ...
    'testRepositoryRoot should resolve runner implementations.');

fprintf('test_repository_root_utilities passed. Repository-root resolution is path independent.\n');
