function fig = aePlotSweepCp(sweepResult, varargin)
%AEPLOTSWEEPCP Plot AE IOP/HGO sweep curves with the shared renderer.

p = inputParser;
addParameter(p, 'Title', "", @(x)ischar(x) || isstring(x) || iscellstr(x));
addParameter(p, 'ShowInvalidPoints', false, @(x)islogical(x) || isnumeric(x));
addParameter(p, 'FrequencyScale', 1e3, @(x)isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'FrequencyUnit', "kHz", @(x)ischar(x) || isstring(x));
addParameter(p, 'StartFrequencyAtZero', true, @(x)islogical(x) || isnumeric(x));
addParameter(p, 'StartCpAtZero', true, @(x)islogical(x) || isnumeric(x));
addParameter(p, 'ShowFixedParameters', true, @(x)islogical(x) || isnumeric(x));
addParameter(p, 'LineWidth', 1.8, @(x)isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'LegendLocation', "southeast", @(x)ischar(x) || isstring(x));
parse(p, varargin{:});

plotData = aeBuildSweepPlotData(sweepResult);
fig = plotSweepCpFigure(plotData, ...
    'Title', p.Results.Title, ...
    'FigureName', "AE IOP/HGO sweep Cp", ...
    'FrequencyScale', p.Results.FrequencyScale, ...
    'FrequencyUnit', p.Results.FrequencyUnit, ...
    'StartFrequencyAtZero', p.Results.StartFrequencyAtZero, ...
    'StartCpAtZero', p.Results.StartCpAtZero, ...
    'ShowFixedParameters', p.Results.ShowFixedParameters, ...
    'ShowInvalidPoints', p.Results.ShowInvalidPoints, ...
    'LineWidth', p.Results.LineWidth, ...
    'LegendLocation', p.Results.LegendLocation);
end