function [overrides, canonicalName] = aeGetNumericalPreset(presetName)
%AEGETNUMERICALPRESET Return maintained AE numerical preset values.

name = lower(strtrim(string(presetName)));
if numel(name) ~= 1 || strlength(name) == 0
    error('aeGetNumericalPreset:InvalidPreset', ...
        'AE numerical preset must be Fast, Balanced, Robust, or MainGUI.');
end

switch name
    case "fast"
        canonicalName = "Fast";
        overrides = struct('atlasNumYPoints', 300, 'atlasTopNMinima', 12);
    case "balanced"
        canonicalName = "Balanced";
        overrides = struct('atlasNumYPoints', 600, 'atlasTopNMinima', 16);
    case "robust"
        canonicalName = "Robust";
        overrides = struct('atlasNumYPoints', 900, 'atlasTopNMinima', 20);
    case {"maingui", "mainguiinteractive"}
        canonicalName = "MainGUI";
        defaults = defaultAcoustoelasticIOPHGOOptions();
        overrides = struct( ...
            'aeGuiAtlasPreset', "fast", ...
            'numCpScanPoints', 420, ...
            'maxLocalCandidates', 8, ...
            'refineLocalMinima', false, ...
            'atlasInitializationNumFrequencyPoints', 25, ...
            'trackingMethod', "predictiveContinuation", ...
            'localContinuationFallback', defaults.localContinuationFallback, ...
            'predictiveWindow', 0.22, ...
            'predictionWeight', defaults.predictionWeight, ...
            'curvatureWeight', defaults.curvatureWeight);
    otherwise
        error('aeGetNumericalPreset:InvalidPreset', ...
            'Unknown AE numerical preset "%s".', string(presetName));
end
end
