clear; clc;
startup

fprintf('\nRunning execution profile fit curve metadata test...\n');
fprintf('--------------------------------------------------\n');

%% Rayleigh-Lamb fitted curve keeps profile metadata.
rlParams = rlDefaultParams();
rlParams.mu = 85e3;
rlFrequency = linspace(1000, 3000, 4).';
rlOptions = rlDefaultOptions("Robust");
rlCp = rlEvaluateFitModel(rlParams, rlFrequency, "A0", rlOptions);
rlRequest = guiBuildFitRequest("rayleigh_lamb", ...
    'branchName', "A0", ...
    'experimental', struct('frequency_Hz', rlFrequency, 'Cp_mps', rlCp, 'validMask', isfinite(rlCp)), ...
    'fixedParams', struct('thickness', rlParams.thickness, 'rho', rlParams.rho, 'nu', rlParams.nu), ...
    'freeParams', "mu", ...
    'initialGuess', struct('mu', rlParams.mu), ...
    'bounds', struct('mu', [20e3, 160e3]), ...
    'controls', struct('robustness', "robust"), ...
    'fitOptions', shortFitOptions(1, 3, 1e-4));
rlFit = guiRunFit(rlRequest);
assertSameProfileMetadata(rlFit);
assert(rlFit.normalized.fullCurve.executionProfile.effectiveExecutionProfile == "Robust", ...
    'RL fitted curve should preserve effective Robust metadata.');

%% AE fitted curve keeps atlas profile metadata and density.
aeParams = struct('R', 7.8e-3, 'thickness', 550e-6, 'IOP', 15 * 133.322, ...
    'mu', 64e3, 'k1', 50e3, 'k2', 200, 'rho', 1060, 'rhoF', 1000, ...
    'fluidBulkModulus', 2.2e9);
aeFrequency = logspace(log10(300), log10(3000), 5).';
aeOptions = aeDefaultSweepOptions("Balanced");
[aeCp, aeRaw] = aeEvaluateFitModel(aeParams, aeFrequency, "atlasA0", aeOptions);
aeRequest = guiBuildFitRequest("acoustoelastic_iop_hgo", ...
    'branchName', "atlasA0", ...
    'experimental', struct('frequency_Hz', aeFrequency, 'Cp_mps', aeCp, 'validMask', aeRaw.validMask), ...
    'fixedParams', rmfield(aeParams, 'mu'), ...
    'freeParams', "mu", ...
    'initialGuess', struct('mu', aeParams.mu), ...
    'bounds', struct('mu', [10e3, 150e3]), ...
    'controls', struct('executionProfile', "Balanced", 'atlasInitializationNumFrequencyPoints', 50), ...
    'fitOptions', shortFitOptions(1, 3, 1e-3));
aeFit = guiRunFit(aeRequest);
assertSameProfileMetadata(aeFit);
assert(aeFit.normalized.fullCurve.executionProfile.atlasNumYPoints == 600 && ...
    aeFit.normalized.fullCurve.executionProfile.atlasTopNMinima == 16, ...
    'AE fitted curve should preserve Balanced 600/16 atlas metadata.');

%% mRLFE fitted curve keeps requested/effective mapping and fast.
mrlfeParams = mrlfeDefaultSweepParams();
mrlfeFrequency = linspace(1000, 4000, 5).';
mrlfeOptions = mrlfeDefaultSweepOptions("A0Like", 'EtaS', 0, ...
    'A0Policy', "physicalTail");
mrlfeCp = mrlfeEvaluateFitModel(mrlfeParams, mrlfeFrequency, "A0Like", mrlfeOptions);
mrlfeRequest = guiBuildFitRequest("mrlfe", ...
    'branchName', "A0Like", ...
    'experimental', struct('frequency_Hz', mrlfeFrequency, 'Cp_mps', mrlfeCp, 'validMask', isfinite(mrlfeCp)), ...
    'fixedParams', struct('thickness', mrlfeParams.thickness, 'rho', mrlfeParams.rho, 'nu', mrlfeParams.nu, 'etaS', 0), ...
    'freeParams', "mu", ...
    'initialGuess', struct('mu', mrlfeParams.mu), ...
    'bounds', struct('mu', [20e3, 160e3]), ...
    'controls', struct('executionProfile', "Balanced", ...
        'etaS', 0, 'fluidDensity', 1000, 'fluidSoundSpeed', 1500, ...
        'mrlfeA0Policy', "physicalTail"), ...
    'fitOptions', shortFitOptions(1, 3, 1e-4));
mrlfeFit = guiRunFit(mrlfeRequest);
assertSameProfileMetadata(mrlfeFit);
assert(mrlfeFit.normalized.fullCurve.executionProfile.requestedExecutionProfile == "Balanced", ...
    'mRLFE fitted curve should preserve requested Balanced metadata.');
assert(mrlfeFit.normalized.fullCurve.executionProfile.effectiveExecutionProfile == "Fast", ...
    'mRLFE fitted curve should preserve effective Fast metadata.');
assert(mrlfeFit.normalized.fullCurve.executionProfile.internalAtlasPreset == "fast", ...
    'mRLFE fitted curve should preserve fast metadata.');

fprintf('Execution profile fit curve metadata test passed.\n');

function fitOptions = shortFitOptions(maxIter, maxFunEvals, tolX)
fitOptions = struct('useStandardErrorWeights', false, ...
    'optimizerOptions', optimset('Display', 'off', ...
    'MaxIter', maxIter, 'MaxFunEvals', maxFunEvals, 'TolX', tolX));
end

function assertSameProfileMetadata(fitOutput)
top = fitOutput.executionProfile;
normalized = fitOutput.normalized.executionProfile;
fullCurve = fitOutput.normalized.fullCurve.executionProfile;
assert(isequaln(top, normalized), ...
    'Normalized output should preserve top-level execution profile metadata.');
assert(isequaln(top, fullCurve), ...
    'Fitted curve should preserve top-level execution profile metadata.');
end
