function test_execution_profile_surface_metadata()
fprintf('\nRunning execution profile surface metadata tests...\n');
fprintf('--------------------------------------------------\n');

%% Main/API Rayleigh-Lamb accepts executionProfile metadata without changing Cp.
params = lamb.models.rayleigh_lamb.rlDefaultParams();
params.fmin = 1000;
params.fmax = 3000;
params.numFrequencyPoints = 10;
params.frequencySpacing = "linspace";

legacyOptions = lamb.models.rayleigh_lamb.rlDefaultOptions("Fast");
legacyOptions.computeA0 = true;
legacyOptions.computeS0 = false;
legacy = lamb.models.rayleigh_lamb.rlComputeFundamentalLambModes(params, legacyOptions);

profileOptions = legacyOptions;
profileOptions.executionProfile = "Fast";
profileOptions.robustness = "Fast";
profileResult = guiRunRayleighLambModel(struct('params', params, 'options', profileOptions));
profileCp = profileResult.metadata.modelResult.modes.A0.phaseVelocity_mps(:);
assert(max(abs(profileCp - legacy.modes.A0.phaseVelocity_mps(:))) < 10 * eps(max(abs(legacy.modes.A0.phaseVelocity_mps(:)))), ...
    'RL execution profile metadata changed deterministic Cp output.');
assert(profileResult.metadata.executionProfile.requestedExecutionProfile == "Fast", ...
    'RL metadata should report requested Fast.');
assert(profileResult.metadata.executionProfile.effectiveExecutionProfile == "Fast", ...
    'RL metadata should report effective Fast.');

%% mRLFE main adapter applies the requested Balanced preset directly.
mrlfeOptions = mrlfeDefaultSweepOptions("A0Like", 'EtaS', 0);
mrlfeOptions.executionProfile = "Balanced";
mrlfeOptions.effectiveExecutionProfile = "Balanced";
mrlfeOptions.robustness = "Balanced";
mrlfeOptions.branchNames = "A0Like";
mrlfeOptions.mrlfeA0Policy = "physicalTail";
mrlfeOptions.mrlfeParams = lamb.models.mrlfe.configuration.mrlfeDefaultInternalParameters();
mrlfeOptions.mrlfeParams.etaS = 0;
mrlfeParams = params;
mrlfeParams.fmax = 4000;
mrlfeParams.numFrequencyPoints = 10;
mrlfeMain = guiRunMRLFEModel(struct('params', mrlfeParams, 'options', mrlfeOptions, ...
    'mrlfeParams', mrlfeOptions.mrlfeParams, 'computeVisco', false));
assert(mrlfeMain.metadata.executionProfile.requestedExecutionProfile == "Balanced", ...
    'mRLFE main metadata should preserve requested Balanced.');
assert(mrlfeMain.metadata.executionProfile.effectiveExecutionProfile == "Balanced", ...
    'mRLFE main metadata should report effective Balanced.');
assert(mrlfeMain.metadata.executionProfile.profileOverrideApplied == false, ...
    'mRLFE main metadata should not report an override.');
assert(strlength(mrlfeMain.metadata.executionProfile.profileOverrideReason) == 0, ...
    'mRLFE main override reason should be empty.');
assert(mrlfeMain.metadata.executionProfile.routePolicy == "lamb.models.mrlfe.mrlfeSolve", ...
    'mRLFE main route should use the public solver.');
assert(mrlfeMain.metadata.executionProfile.effectiveNumericalPreset == "balanced", ...
    'mRLFE main GUI should apply the balanced public preset.');
assert(mrlfeMain.metadata.requests.A0Like.numerics.preset == "balanced", ...
    'mRLFE main request should carry the balanced numerical preset.');
assert(mrlfeMain.metadata.modelResult.execution.internalEngine == "elastic_adaptive", ...
    'mRLFE etaS=0 main engine should be neutral elastic_adaptive.');
assert(mrlfeMain.metadata.modelResult.fallback.policy == "none" && ...
    mrlfeMain.metadata.modelResult.fallback.applied == false, ...
    'mRLFE main GUI fallback must remain disabled.');
assert(mrlfeMain.metadata.modelResult.termination.policy == "physicalTail", ...
    'mRLFE A0 termination policy should be physicalTail.');

%% AE Fit metadata records preserved 300/12/50 override for requested Robust.
aeControls = struct('executionProfile', "Robust", 'atlasNumYPoints', 300, ...
    'atlasTopNMinima', 12, 'atlasInitializationNumFrequencyPoints', 50);
[aeOptions, aeMetadata] = aeResolveExecutionProfile(aeControls, ...
    'DefaultProfile', "Fast", 'DefaultSource', "FitTool default");
aeOptions.atlasNumYPoints = aeControls.atlasNumYPoints;
aeOptions.atlasTopNMinima = aeControls.atlasTopNMinima;
aeOptions.atlasInitializationNumFrequencyPoints = aeControls.atlasInitializationNumFrequencyPoints;
assert(aeMetadata.requestedExecutionProfile == "Robust", 'AE resolver should preserve requested Robust.');
assert(aeOptions.atlasNumYPoints == 300 && aeOptions.atlasTopNMinima == 12, ...
    'AE Fit override values changed.');

%% FitTool mRLFE applies requested Robust/robust directly.
fitParams = mrlfeDefaultSweepParams();
fitParams.mu = 75e3;
fitFrequency = linspace(1000, 4000, 5).';
fitOptions = mrlfeDefaultSweepOptions("A0Like", 'EtaS', 0.0);
fitCp = mrlfeEvaluateFitModel(fitParams, fitFrequency, "A0Like", fitOptions);
mrlfeRequest = guiBuildFitRequest("mrlfe", ...
    'branchName', "A0Like", ...
    'experimental', struct('frequency_Hz', fitFrequency, 'Cp_mps', fitCp, 'validMask', isfinite(fitCp)), ...
    'fixedParams', struct('thickness', fitParams.thickness, 'rho', fitParams.rho, 'nu', fitParams.nu, 'etaS', 0), ...
    'freeParams', "mu", ...
    'initialGuess', struct('mu', fitParams.mu), ...
    'bounds', struct('mu', [20e3, 160e3]), ...
    'controls', struct('executionProfile', "Robust", 'etaS', 0, ...
        'fluidDensity', 1000, 'fluidSoundSpeed', 1500, ...
        'mrlfeA0Policy', "physicalTail"), ...
    'fitOptions', struct('useStandardErrorWeights', false, ...
        'optimizerOptions', optimset('Display', 'off', 'MaxIter', 1, 'MaxFunEvals', 3, 'TolX', 1e-4)));
mrlfeFit = guiRunFit(mrlfeRequest);
assert(mrlfeFit.executionProfile.requestedExecutionProfile == "Robust", ...
    'mRLFE Fit should preserve requested Robust metadata.');
assert(mrlfeFit.executionProfile.effectiveExecutionProfile == "Robust", ...
    'mRLFE Fit should report effective Robust metadata.');
assert(mrlfeFit.executionProfile.profileOverrideApplied == false, ...
    'mRLFE Fit should not report a profile override.');
assert(mrlfeFit.executionProfile.internalAtlasPreset == "robust", ...
    'mRLFE Fit should report robust metadata.');
assert(mrlfeFit.fitResult.modelEvaluation.modelResult.execution.effectivePreset == "robust", ...
    'mRLFE Fit solver result should use robust preset.');

%% FitTool AE applies requested Robust when atlas density controls are not supplied.
aeParams = struct('R', 7.8e-3, 'thickness', 550e-6, 'IOP', 15 * 133.322, ...
    'mu', 64e3, 'k1', 50e3, 'k2', 200, 'rho', 1060, 'rhoF', 1000, ...
    'fluidBulkModulus', 2.2e9);
aeFrequency = logspace(log10(300), log10(3000), 5).';
aeRobustOptions = aeDefaultSweepOptions("Robust");
[aeCp, aeRaw] = aeEvaluateFitModel(aeParams, aeFrequency, "atlasA0", aeRobustOptions);
aeRequest = guiBuildFitRequest("acoustoelastic_iop_hgo", ...
    'branchName', "atlasA0", ...
    'experimental', struct('frequency_Hz', aeFrequency, 'Cp_mps', aeCp, 'validMask', aeRaw.validMask), ...
    'fixedParams', rmfield(aeParams, 'mu'), ...
    'freeParams', "mu", ...
    'initialGuess', struct('mu', aeParams.mu), ...
    'bounds', struct('mu', [10e3, 150e3]), ...
    'controls', struct('executionProfile', "Robust", 'atlasInitializationNumFrequencyPoints', 50), ...
    'fitOptions', struct('useStandardErrorWeights', false, ...
        'optimizerOptions', optimset('Display', 'off', 'MaxIter', 1, 'MaxFunEvals', 3, 'TolX', 1e-3)));
aeFit = guiRunFit(aeRequest);
assert(aeFit.executionProfile.requestedExecutionProfile == "Robust", ...
    'AE Fit should preserve requested Robust metadata.');
assert(aeFit.executionProfile.effectiveExecutionProfile == "Robust", ...
    'AE Fit should report effective Robust metadata.');
assert(aeFit.executionProfile.profileOverrideApplied == false, ...
    'AE Fit should not override atlas density when controls omit density fields.');
assert(aeFit.executionProfile.atlasNumYPoints == 900 && aeFit.executionProfile.atlasTopNMinima == 20, ...
    'AE Fit Robust should use 900/20.');
assert(aeFit.executionProfile.atlasInitializationNumFrequencyPoints == 50, ...
    'AE Fit should preserve atlasInitializationNumFrequencyPoints metadata.');

%% Legacy AE Fit controls can still override atlas density explicitly.
legacyAERequest = aeRequest;
legacyAERequest.controls.atlasNumYPoints = 300;
legacyAERequest.controls.atlasTopNMinima = 12;
legacyAEFit = guiRunFit(legacyAERequest);
assert(legacyAEFit.executionProfile.requestedExecutionProfile == "Robust", ...
    'Legacy AE Fit controls should preserve requested Robust metadata.');
assert(legacyAEFit.executionProfile.effectiveExecutionProfile == "Fast", ...
    'Legacy AE Fit 300/12 controls should report effective Fast.');
assert(legacyAEFit.executionProfile.profileOverrideApplied == true, ...
    'Legacy AE Fit atlas-density controls should remain explicit overrides.');

%% Fit request builder accepts executionProfile alias and rejects conflict.
experimental = struct('frequency_Hz', [1000; 2000], 'Cp_mps', [2; 3]);
request = guiBuildFitRequest("rayleigh_lamb", 'branchName', "A0", 'experimental', experimental, ...
    'fixedParams', struct(), 'freeParams', "mu", 'initialGuess', struct('mu', 1), ...
    'bounds', struct('mu', [1, 2]), 'controls', struct('executionProfile', "fast"));
assert(request.controls.executionProfile == "Fast", 'Fit request should canonicalize executionProfile.');
assert(request.controls.robustness == "Fast", 'Fit request should populate robustness compatibility alias.');
assertThrows(@()guiBuildFitRequest("rayleigh_lamb", 'branchName', "A0", 'experimental', experimental, ...
    'fixedParams', struct(), 'freeParams', "mu", 'initialGuess', struct('mu', 1), ...
    'bounds', struct('mu', [1, 2]), 'controls', struct('executionProfile', "Fast", 'robustness', "Robust")), ...
    'guiNormalizeExecutionProfile:ConflictingProfiles');

fprintf('Execution profile surface metadata tests passed.\n');
end

function assertThrows(fcn, expectedId)
threw = false;
try
    fcn();
catch ME
    threw = true;
    assert(strcmp(ME.identifier, expectedId), ...
        'Expected error id %s, got %s.', expectedId, ME.identifier);
end
assert(threw, 'Expected function to throw %s.', expectedId);
end
