clear; clc;
startup

fprintf('\nRunning execution profile surface integration tests...\n');
fprintf('----------------------------------------------------\n');

profiles = ["Fast", "Balanced", "Robust"];

%% Surface defaults are explicit.
mainOptions = rlDefaultOptions("Balanced");
[~, mainMetadata] = rlResolveExecutionProfile("Balanced", ...
    'DefaultProfile', "Balanced", 'DefaultSource', "Main GUI default");
assert(mainOptions.robustness == "Balanced", 'Main GUI visible default should remain Balanced.');
assert(mainMetadata.surfaceDefaultExecutionProfile == "Balanced", ...
    'Main GUI metadata should record Balanced surface default.');

sweepRegistry = guiGetSweepRegistry();
for i = 1:numel(sweepRegistry.modelFamilies)
    family = sweepRegistry.modelFamilies(i);
    assert(string(family.defaultExecutionProfile) == "Fast", ...
        'SweepTool family %s defaultExecutionProfile should be Fast.', family.id);
    assert(string(family.surfaceDefaultExecutionProfile) == "Fast", ...
        'SweepTool family %s surface default should be Fast.', family.id);
end

fitRegistry = guiGetFitRegistry();
for i = 1:numel(fitRegistry.modelFamilies)
    family = fitRegistry.modelFamilies(i);
    assert(string(family.defaultExecutionProfile) == "Fast", ...
        'FitTool family %s defaultExecutionProfile should be Fast.', family.id);
    assert(string(family.surfaceDefaultExecutionProfile) == "Fast", ...
        'FitTool family %s surface default should be Fast.', family.id);
end

aeSweepFamily = guiGetSweepFamilyConfig(sweepRegistry, "ae_iop_hgo");
assert(isequal(string(aeSweepFamily.executionProfiles), profiles), ...
    'AE SweepTool should expose Fast/Balanced/Robust.');

%% RL resolver and SweepTool adapter use the requested profile exactly.
params = rlDefaultParams();
params.fmin = 1000;
params.fmax = 3000;
params.numFrequencyPoints = 10;
params.frequencySpacing = "linspace";
for i = 1:numel(profiles)
    profile = profiles(i);
    [options, metadata] = rlResolveExecutionProfile(profile);
    reference = rlDefaultOptions(profile);
    assert(options.gridPointsInitial == reference.gridPointsInitial, ...
        'RL resolver changed gridPointsInitial for %s.', profile);
    assert(metadata.requestedExecutionProfile == profile && metadata.effectiveExecutionProfile == profile, ...
        'RL resolver should report requested/effective %s.', profile);
end

rlSweep = guiRunSweep(guiBuildSweepRequest("rayleigh_lamb", ...
    'modelLabel', "Rayleigh-Lamb", ...
    'branchName', "A0", ...
    'sweepField', "thickness", ...
    'sweepLabel', "thickness", ...
    'sweepValuesDisplay', [0.5], ...
    'displayUnit', "mm", ...
    'displayScale', 1e-3, ...
    'baseParams', params, ...
    'controls', struct(), ...
    'outputMode', "workspace", ...
    'outputTaskName', "rl_profile_surface_test"));
assert(rlSweep.executionProfile.requestedExecutionProfile == "Fast", ...
    'RL SweepTool adapter should default to Fast.');
assert(rlSweep.executionProfile.effectiveExecutionProfile == "Fast", ...
    'RL SweepTool adapter should apply Fast effectively.');

%% AE profiles map to maintained atlas densities in Main/Sweep/Fit paths.
expectedY = [300, 600, 900];
expectedTopN = [12, 16, 20];
for i = 1:numel(profiles)
    profile = profiles(i);
    [aeOptions, aeMetadata] = aeResolveExecutionProfile(profile, ...
        'DefaultProfile', "Fast", 'DefaultSource', "surface test");
    assert(aeOptions.atlasNumYPoints == expectedY(i), 'AE %s atlasNumYPoints mismatch.', profile);
    assert(aeOptions.atlasTopNMinima == expectedTopN(i), 'AE %s atlasTopNMinima mismatch.', profile);
    assert(aeOptions.atlasBranchPolicy == "atlasA0", 'AE %s branch policy changed.', profile);
    assert(aeMetadata.effectiveExecutionProfile == profile, 'AE %s metadata effective mismatch.', profile);
end

aeParams = struct('R', 7.8e-3, 'thickness', 550e-6, 'IOP', 15 * 133.322, ...
    'mu', 64e3, 'k1', 50e3, 'k2', 200, 'rho', 1060, 'rhoF', 1000, ...
    'fluidBulkModulus', 2.2e9, 'frequency', logspace(log10(300), log10(3000), 5));
aeSweep = guiRunSweep(guiBuildSweepRequest("ae_iop_hgo", ...
    'modelLabel', "AE IOP/HGO", ...
    'branchName', "atlasA0", ...
    'sweepField', "IOP", ...
    'sweepLabel', "IOP", ...
    'sweepValuesDisplay', [15], ...
    'displayUnit', "mmHg", ...
    'displayScale', 133.322, ...
    'baseParams', aeParams, ...
    'controls', struct('executionProfile', "Robust"), ...
    'outputMode', "workspace", ...
    'outputTaskName', "ae_profile_surface_test"));
assert(aeSweep.executionProfile.effectiveExecutionProfile == "Robust", ...
    'AE SweepTool Robust should be effective Robust.');
assert(aeSweep.executionProfile.atlasNumYPoints == 900 && aeSweep.executionProfile.atlasTopNMinima == 20, ...
    'AE SweepTool Robust should use 900/20.');

%% mRLFE keeps fast internal presets and route policies separate.
[mrlfeOptions, mrlfeMetadata] = mrlfeResolveExecutionProfile("A0Like", ...
    struct('executionProfile', "Robust"), ...
    'Surface', "sweep", ...
    'EtaS', 0, ...
    'A0Policy', "physicalTail");
assert(mrlfeOptions.executionProfile == "Robust", ...
    'mRLFE should preserve requested profile.');
assert(mrlfeMetadata.effectiveExecutionProfile == "Fast", ...
    'mRLFE Robust should map to effective Fast.');
assert(mrlfeMetadata.profileOverrideApplied == true, ...
    'mRLFE Robust should report explicit override.');
assert(mrlfeMetadata.routePolicy == "physicalTail", ...
    'mRLFE route policy should remain separate from execution profile.');
assert(mrlfeMetadata.profileSupportMode == "mapped_to_fast", ...
    'mRLFE support mode should document mapped-to-Fast behavior.');

fprintf('Execution profile surface integration tests passed.\n');
