clear; clc;
startup

fprintf('\nRunning execution profile validation matrix test...\n');
fprintf('------------------------------------------------\n');

matrix = validateExecutionProfileMatrix('WriteCsv', false);

expectedRows = 3 * 4 * numel(guiExecutionProfileValues());
assert(height(matrix) == expectedRows, ...
    'Validation matrix should contain Main/Sweep/Fit x 4 scenarios x 3 profiles.');
assert(all(matrix.ResultValidity), 'All validation matrix rows should have complete valid metadata.');
assert(all(matrix.NumericalOutputAvailable), 'All validation matrix rows should produce finite numerical output.');

requiredColumns = ["Surface", "Model", "Scenario", "RequestedProfile", ...
    "EffectiveProfile", "SupportMode", "InternalSolverPreset", ...
    "InternalAtlasPreset", "RoutePolicy", "ProfileOverrideApplied", ...
    "ProfileOverrideReason", "ExecutionProfileSource", "ResultValidity", ...
    "NumericalOutputAvailable", "ExportMetadataAvailable", ...
    "SyntheticFittingApplicability", "Notes", "ElapsedSeconds"];
assert(isequal(string(matrix.Properties.VariableNames), requiredColumns), ...
    'Validation matrix columns changed.');

rlRows = matrix.Model == "Rayleigh-Lamb";
assert(all(matrix.RequestedProfile(rlRows) == matrix.EffectiveProfile(rlRows)), ...
    'Rayleigh-Lamb rows should be fully effective for every profile.');
assert(all(matrix.SupportMode(rlRows) == "fully_supported"), ...
    'Rayleigh-Lamb support mode should be fully_supported.');
assert(all(matrix.RoutePolicy(rlRows) == "direct"), ...
    'Rayleigh-Lamb route policy should remain direct.');

aeRows = matrix.Model == "AE IOP/HGO";
assert(all(matrix.RequestedProfile(aeRows) == matrix.EffectiveProfile(aeRows)), ...
    'AE rows should be fully effective for every profile.');
assert(all(matrix.SupportMode(aeRows) == "fully_supported"), ...
    'AE support mode should be fully_supported.');
assert(all(matrix.RoutePolicy(aeRows) == "atlasA0"), ...
    'AE route policy should remain atlasA0.');
assert(any(matrix.InternalAtlasPreset(aeRows & matrix.RequestedProfile == "Fast") == "ae_atlas_300x12"), ...
    'AE Fast should report 300/12 atlas preset.');
assert(any(matrix.InternalAtlasPreset(aeRows & matrix.RequestedProfile == "Balanced") == "ae_atlas_600x16"), ...
    'AE Balanced should report 600/16 atlas preset.');
assert(any(matrix.InternalAtlasPreset(aeRows & matrix.RequestedProfile == "Robust") == "ae_atlas_900x20"), ...
    'AE Robust should report 900/20 atlas preset.');

mrlfeRows = matrix.Model == "mRLFE";
assert(all(matrix.RequestedProfile(mrlfeRows) == matrix.EffectiveProfile(mrlfeRows)), ...
    'mRLFE rows should apply every requested public profile directly.');
assert(all(matrix.SupportMode(mrlfeRows) == "direct"), ...
    'mRLFE support mode should report direct profile support.');
assert(all(~matrix.ProfileOverrideApplied(mrlfeRows)), ...
    'mRLFE direct profile support should not report overrides.');
assert(all(matrix.ProfileOverrideReason(mrlfeRows) == ""), ...
    'mRLFE direct profile support should not report override reasons.');
assert(any(matrix.InternalAtlasPreset(mrlfeRows & matrix.RequestedProfile == "Fast") == "fast"), ...
    'mRLFE Fast rows should report the fast preset.');
assert(any(matrix.InternalAtlasPreset(mrlfeRows & matrix.RequestedProfile == "Balanced") == "balanced"), ...
    'mRLFE Balanced rows should report the balanced preset.');
assert(any(matrix.InternalAtlasPreset(mrlfeRows & matrix.RequestedProfile == "Robust") == "robust"), ...
    'mRLFE Robust rows should report the robust preset.');

fitRows = matrix.Surface == "FitTool";
assert(all(matrix.SyntheticFittingApplicability(fitRows) == "synthetic_fit_and_fitted_curve"), ...
    'FitTool rows should report synthetic/fitting/fitted-curve applicability.');

fprintf('Execution profile validation matrix test passed.\n');