clear; clc;
startup

fprintf('\nRunning execution profile diagnostics format test...\n');
fprintf('-------------------------------------------------\n');

%% RL diagnostics expose effective numerical settings and unambiguous labels.
[~, rlMetadata] = rlResolveExecutionProfile("Robust", ...
    'DefaultProfile', "Balanced", 'DefaultSource', "Main GUI default");
rlLines = guiFormatExecutionProfileDiagnostics(rlMetadata, ...
    'Surface', "Main GUI", ...
    'Model', "Rayleigh-Lamb", ...
    'ControlProfile', "Robust", ...
    'VisibleBranch', "RayleighLamb A0", ...
    'ValidCount', 10, ...
    'TotalCount', 10, ...
    'ElapsedSeconds', 2.1);
assertContains(rlLines, "control value: Robust");
assertContains(rlLines, "requested: Robust");
assertContains(rlLines, "effective: Robust");
assertContains(rlLines, "gridPointsInitial = 6000");
assertContains(rlLines, "gridPointsTracking = 1400");
assertContains(rlLines, "route policy: direct");
assertNoRequestedEffectiveSlash(rlLines);

%% AE diagnostics expose atlas density and route policy.
[~, aeMetadata] = aeResolveExecutionProfile("Balanced", ...
    'DefaultProfile', "Fast", 'DefaultSource', "SweepTool default");
aeLines = guiFormatExecutionProfileDiagnostics(aeMetadata, ...
    'Surface', "SweepTool", ...
    'Model', "AE IOP/HGO", ...
    'ControlProfile', "Balanced", ...
    'VisibleBranch', "atlasA0", ...
    'ValidCount', 35, ...
    'TotalCount', 35, ...
    'ElapsedSeconds', 29.3);
assertContains(aeLines, "atlas preset: ae_atlas_600x16");
assertContains(aeLines, "atlasNumYPoints = 600");
assertContains(aeLines, "atlasTopNMinima = 16");
assertContains(aeLines, "route policy: atlasA0");

%% mRLFE diagnostics show mapped-to-Fast without presenting Balanced effective.
[~, mrlfeMetadata] = mrlfeResolveExecutionProfile("A0Like", ...
    struct('executionProfile', "Balanced"), ...
    'Surface', "fit", ...
    'DefaultProfile', "Fast", ...
    'DefaultSource', "FitTool default", ...
    'EtaS', 0, ...
    'UseUnifiedAtlasRoute', true, ...
    'A0Policy', "adaptivePhysicalTail");
mrlfeMetadata.actualRoute = "zero_viscosity_adaptive_atlas";
mrlfeLines = guiFormatExecutionProfileDiagnostics(mrlfeMetadata, ...
    'Surface', "FitTool", ...
    'Model', "mRLFE", ...
    'ControlProfile', "Balanced", ...
    'VisibleBranch', "A0Like", ...
    'ValidCount', 10, ...
    'TotalCount', 10, ...
    'ElapsedSeconds', 7.5, ...
    'Fallback', false, ...
    'ExtraLines', ["A0 policy: adaptivePhysicalTail"]);
assertContains(mrlfeLines, "requested: Balanced");
assertContains(mrlfeLines, "effective: Fast");
assertContains(mrlfeLines, "support mode: mapped_to_fast");
assertContains(mrlfeLines, "atlas preset: fast_fit_atlas");
assertContains(mrlfeLines, "actual route: zero_viscosity_adaptive_atlas");
assertContains(mrlfeLines, "A0 policy: adaptivePhysicalTail");
assert(~any(contains(mrlfeLines, "effective: Balanced")), ...
    'mRLFE diagnostics must not present Balanced as effective when mapped to Fast.');

fprintf('Execution profile diagnostics format test passed.\n');

function assertContains(lines, expected)
assert(any(contains(string(lines), expected)), ...
    'Expected diagnostics to contain "%s".', expected);
end

function assertNoRequestedEffectiveSlash(lines)
assert(~any(contains(string(lines), "requested/effective")), ...
    'Diagnostics should not use ambiguous requested/effective slash wording.');
end
