clear; clc;
startup

fprintf('\nRunning execution profile state transition contract test...\n');
fprintf('---------------------------------------------------------\n');

profiles = guiExecutionProfileValues();

%% Main GUI headless transition equivalent: RL -> mRLFE -> AE -> RL.
[~, rlBalanced] = rlResolveExecutionProfile("Balanced", ...
    'DefaultProfile', "Balanced", 'DefaultSource', "Main GUI default");
[~, mrlfeBalanced] = mrlfeResolveExecutionProfile("A0Like", ...
    struct('executionProfile', "Balanced"), ...
    'Surface', "gui", ...
    'DefaultProfile', "Balanced", ...
    'DefaultSource', "Main GUI default", ...
    'EtaS', 0, ...
    'A0Policy', "physicalTail");
[~, aeBalanced] = aeResolveExecutionProfile("Balanced", ...
    'DefaultProfile', "Balanced", 'DefaultSource', "Main GUI default");
[~, rlAgain] = rlResolveExecutionProfile("Balanced", ...
    'DefaultProfile', "Balanced", 'DefaultSource', "Main GUI default");

assert(rlBalanced.effectiveExecutionProfile == "Balanced", ...
    'Main RL default should be effective Balanced.');
assert(mrlfeBalanced.requestedExecutionProfile == "Balanced" && ...
    mrlfeBalanced.effectiveExecutionProfile == "Fast", ...
    'Main mRLFE should preserve requested Balanced and explicit effective Fast.');
assert(aeBalanced.effectiveExecutionProfile == "Balanced", ...
    'Main AE default should be effective Balanced.');
assert(rlAgain.internalAtlasPreset == "" && rlAgain.internalSolverPreset == "Balanced", ...
    'Returning to RL should not preserve another model internal preset.');

%% SweepTool family transitions keep Fast default and profile declarations.
sweepRegistry = guiGetSweepRegistry();
sweepOrder = ["rayleigh_lamb", "ae_iop_hgo", "mrlfe", "rayleigh_lamb"];
for i = 1:numel(sweepOrder)
    family = guiGetSweepFamilyConfig(sweepRegistry, sweepOrder(i));
    assert(family.defaultExecutionProfile == "Fast", ...
        'SweepTool family %s should default to Fast.', family.id);
    assert(isequal(string(family.executionProfiles), profiles), ...
        'SweepTool family %s profile list should stay canonical.', family.id);
    assert(strlength(string(family.profileSupportMode)) > 0, ...
        'SweepTool family %s should declare profile support mode.', family.id);
end

%% FitTool model transitions keep Fast default, free parameter state, and controls.
fitRegistry = guiGetFitRegistry();
fitOrder = ["rayleigh_lamb", "acoustoelastic_iop_hgo", "mrlfe", "acoustoelastic_iop_hgo", "rayleigh_lamb"];
previousState = struct();
for i = 1:numel(fitOrder)
    family = findFitFamily(fitRegistry, fitOrder(i));
    state = guiBuildFitParameterState(family.id, "", previousState);
    config = guiBuildFitParameterRequest(state);
    request = guiBuildFitRequest(family.id, ...
        'branchName', family.defaultBranchName, ...
        'experimental', struct('frequency_Hz', [1000; 2000], 'Cp_mps', [2; 3]), ...
        'fixedParams', config.fixedParams, ...
        'freeParams', config.freeParams, ...
        'initialGuess', config.initialGuess, ...
        'bounds', config.bounds, ...
        'controls', config.controls);

    assert(family.defaultExecutionProfile == "Fast", ...
        'FitTool family %s should default to Fast.', family.id);
    assert(isfield(request.controls, 'executionProfile') == isfield(config.controls, 'executionProfile'), ...
        'FitTool builder should not add an implicit profile when state controls omit it.');
    assert(numel(request.freeParams) == 1, ...
        'FitTool should remain one-free-parameter after model transition.');
    previousState = state;
end

%% Historical alias still fails early on contradiction.
assertThrows(@()guiBuildSweepRequest("rayleigh_lamb", ...
    'branchName', "A0", ...
    'sweepField', "thickness", ...
    'sweepValuesDisplay', 0.5, ...
    'controls', struct('executionProfile', "Fast", 'robustness', "Robust")), ...
    'guiNormalizeExecutionProfile:ConflictingProfiles');

assertThrows(@()guiBuildFitRequest("rayleigh_lamb", ...
    'branchName', "A0", ...
    'experimental', struct('frequency_Hz', [1000; 2000], 'Cp_mps', [2; 3]), ...
    'fixedParams', struct(), ...
    'freeParams', "mu", ...
    'initialGuess', struct('mu', 1), ...
    'bounds', struct('mu', [1, 2]), ...
    'controls', struct('executionProfile', "Robust", 'robustness', "Fast")), ...
    'guiNormalizeExecutionProfile:ConflictingProfiles');

fprintf('Execution profile state transition contract test passed.\n');

function family = findFitFamily(registry, id)
for i = 1:numel(registry.modelFamilies)
    if string(registry.modelFamilies(i).id) == string(id)
        family = registry.modelFamilies(i);
        return;
    end
end
error('Missing FitTool family %s.', id);
end

function assertThrows(fcn, expectedId)
threw = false;
try
    fcn();
catch ME
    threw = true;
    assert(strcmp(ME.identifier, expectedId), ...
        'Expected error id %s, got %s.', expectedId, ME.identifier);
end
assert(threw, 'Expected function to throw %s.', expectedId);
end
