clear; clc;
startup

% Run all maintained smoke and consistency tests.
%
% This script is intended as the first validation step after refactors,
% folder reorganizations, or path changes. It should remain lightweight and
% avoid generating figures.

fprintf('\nRunning Lamb Fundamental Solver smoke tests...\n');
fprintf('---------------------------------------------\n');


%% Rayleigh-Lamb base solver path checks
fprintf('\nChecking Rayleigh-Lamb base solver functions...\n');
assert(~isempty(which('buildFrequencyVector')), ...
    'Missing Rayleigh-Lamb base function buildFrequencyVector on MATLAB path.');
assert(~isempty(which('computeFundamentalLambModes')), ...
    'Missing Rayleigh-Lamb base function computeFundamentalLambModes on MATLAB path.');
assert(~isempty(which('computeGeometry')), ...
    'Missing Rayleigh-Lamb base function computeGeometry on MATLAB path.');
assert(~isempty(which('computeMaterial')), ...
    'Missing Rayleigh-Lamb base function computeMaterial on MATLAB path.');
assert(~isempty(which('defaultOptions')), ...
    'Missing Rayleigh-Lamb base function defaultOptions on MATLAB path.');
assert(~isempty(which('defaultParams')), ...
    'Missing Rayleigh-Lamb base function defaultParams on MATLAB path.');
assert(~isempty(which('makeBranchSpec')), ...
    'Missing Rayleigh-Lamb base function makeBranchSpec on MATLAB path.');
assert(~isempty(which('validateOptions')), ...
    'Missing Rayleigh-Lamb base function validateOptions on MATLAB path.');
assert(~isempty(which('validateParams')), ...
    'Missing Rayleigh-Lamb base function validateParams on MATLAB path.');
assert(~isempty(which('rayleighLambAResidual')), ...
    'Missing Rayleigh-Lamb base function rayleighLambAResidual on MATLAB path.');
assert(~isempty(which('rayleighLambSResidual')), ...
    'Missing Rayleigh-Lamb base function rayleighLambSResidual on MATLAB path.');
assert(~isempty(which('computeA0ThinPlateApproximation')), ...
    'Missing Rayleigh-Lamb base function computeA0ThinPlateApproximation on MATLAB path.');
assert(~isempty(which('computeAnalyticalApproximations')), ...
    'Missing Rayleigh-Lamb base function computeAnalyticalApproximations on MATLAB path.');
assert(~isempty(which('computeS0ExtensionalApproximation')), ...
    'Missing Rayleigh-Lamb base function computeS0ExtensionalApproximation on MATLAB path.');
assert(~isempty(which('solveFundamentalBranch')), ...
    'Missing Rayleigh-Lamb base function solveFundamentalBranch on MATLAB path.');


%% Rayleigh-Lamb organized wrapper layer path checks
fprintf('\nChecking Rayleigh-Lamb organized wrapper layer functions...\n');
assert(~isempty(which('rlBuildFrequencyVector')), ...
    'Missing Rayleigh-Lamb wrapper function rlBuildFrequencyVector on MATLAB path.');
assert(~isempty(which('rlComputeFundamentalLambModes')), ...
    'Missing Rayleigh-Lamb wrapper function rlComputeFundamentalLambModes on MATLAB path.');
assert(~isempty(which('rlComputeGeometry')), ...
    'Missing Rayleigh-Lamb wrapper function rlComputeGeometry on MATLAB path.');
assert(~isempty(which('rlComputeMaterial')), ...
    'Missing Rayleigh-Lamb wrapper function rlComputeMaterial on MATLAB path.');
assert(~isempty(which('rlDefaultOptions')), ...
    'Missing Rayleigh-Lamb wrapper function rlDefaultOptions on MATLAB path.');
assert(~isempty(which('rlDefaultParams')), ...
    'Missing Rayleigh-Lamb wrapper function rlDefaultParams on MATLAB path.');
assert(~isempty(which('rlMakeBranchSpec')), ...
    'Missing Rayleigh-Lamb wrapper function rlMakeBranchSpec on MATLAB path.');
assert(~isempty(which('rlValidateOptions')), ...
    'Missing Rayleigh-Lamb wrapper function rlValidateOptions on MATLAB path.');
assert(~isempty(which('rlValidateParams')), ...
    'Missing Rayleigh-Lamb wrapper function rlValidateParams on MATLAB path.');
assert(~isempty(which('rlAResidual')), ...
    'Missing Rayleigh-Lamb wrapper function rlAResidual on MATLAB path.');
assert(~isempty(which('rlSResidual')), ...
    'Missing Rayleigh-Lamb wrapper function rlSResidual on MATLAB path.');
assert(~isempty(which('rlComputeA0ThinPlateApproximation')), ...
    'Missing Rayleigh-Lamb wrapper function rlComputeA0ThinPlateApproximation on MATLAB path.');
assert(~isempty(which('rlComputeAnalyticalApproximations')), ...
    'Missing Rayleigh-Lamb wrapper function rlComputeAnalyticalApproximations on MATLAB path.');
assert(~isempty(which('rlComputeS0ExtensionalApproximation')), ...
    'Missing Rayleigh-Lamb wrapper function rlComputeS0ExtensionalApproximation on MATLAB path.');
assert(~isempty(which('rlSolveFundamentalBranch')), ...
    'Missing Rayleigh-Lamb wrapper function rlSolveFundamentalBranch on MATLAB path.');


%% Rayleigh-Lamb compatibility wrapper smoke checks
fprintf('\nChecking Rayleigh-Lamb compatibility wrapper forwarding...\n');
compatTol = 1e-12;

paramsOld = defaultParams();
paramsNew = rlDefaultParams();
assert(isequaln(paramsOld, paramsNew), ...
    'defaultParams does not match rlDefaultParams.');

optionsOld = defaultOptions();
optionsNew = rlDefaultOptions();
assert(isequaln(optionsOld, optionsNew), ...
    'defaultOptions does not match rlDefaultOptions.');

materialOld = computeMaterial(paramsNew);
materialNew = rlComputeMaterial(paramsNew);
assert(isequaln(materialOld, materialNew), ...
    'computeMaterial does not match rlComputeMaterial.');

geometryOld = computeGeometry(paramsNew);
geometryNew = rlComputeGeometry(paramsNew);
assert(isequaln(geometryOld, geometryNew), ...
    'computeGeometry does not match rlComputeGeometry.');

frequencyParams = paramsNew;
frequencyParams.fmin = 10;
frequencyParams.fmax = 100;
frequencyParams.numFrequencyPoints = 10;
frequencyParams.frequencySpacing = "linspace";
frequencyOld = buildFrequencyVector(frequencyParams);
frequencyNew = rlBuildFrequencyVector(frequencyParams);
assertNumericClose(frequencyOld, frequencyNew, compatTol, ...
    'buildFrequencyVector does not match rlBuildFrequencyVector.');

branchGeometry = geometryNew;
branchGeometry.frequency0 = frequencyNew(1);
branchSpecOld = makeBranchSpec("A0", materialNew, branchGeometry);
branchSpecNew = rlMakeBranchSpec("A0", materialNew, branchGeometry);
assert(isequaln(branchSpecOld, branchSpecNew), ...
    'makeBranchSpec A0 does not match rlMakeBranchSpec A0.');
branchSpecOld = makeBranchSpec("S0", materialNew, branchGeometry);
branchSpecNew = rlMakeBranchSpec("S0", materialNew, branchGeometry);
assert(isequaln(branchSpecOld, branchSpecNew), ...
    'makeBranchSpec S0 does not match rlMakeBranchSpec S0.');

approxFrequency = [10, 25, 100];
a0ApproxOld = computeA0ThinPlateApproximation(approxFrequency, materialNew, geometryNew);
a0ApproxNew = rlComputeA0ThinPlateApproximation(approxFrequency, materialNew, geometryNew);
assert(isequaln(a0ApproxOld, a0ApproxNew), ...
    'computeA0ThinPlateApproximation does not match rlComputeA0ThinPlateApproximation.');

s0ApproxOld = computeS0ExtensionalApproximation(approxFrequency, materialNew, geometryNew);
s0ApproxNew = rlComputeS0ExtensionalApproximation(approxFrequency, materialNew, geometryNew);
assert(isequaln(s0ApproxOld, s0ApproxNew), ...
    'computeS0ExtensionalApproximation does not match rlComputeS0ExtensionalApproximation.');

fprintf('\nChecking maintained acoustoelastic IOP/HGO wrappers and entrypoints...\n');
assert(~isempty(which('solveAcoustoelasticIOPHGOBranch')), ...
    'Missing solveAcoustoelasticIOPHGOBranch on MATLAB path.');
assert(~isempty(which('solveAcoustoelasticIOPHGOAtlasBranch')), ...
    'Missing solveAcoustoelasticIOPHGOAtlasBranch on MATLAB path.');
assert(~isempty(which('solveAcoustoelasticAtlasBranch')), ...
    'Missing solveAcoustoelasticAtlasBranch on MATLAB path.');
assert(~isempty(which('solveAcoustoelasticIOPHGODispersion')), ...
    'Missing solveAcoustoelasticIOPHGODispersion on MATLAB path.');
assert(~isempty(which('solveAcoustoelasticDispersion')), ...
    'Missing solveAcoustoelasticDispersion on MATLAB path.');
assert(~isempty(which('solveAcoustoelasticComplexCDispersion')), ...
    'Missing solveAcoustoelasticComplexCDispersion on MATLAB path.');
assert(~isempty(which('objectiveAcoustoelasticResidual')), ...
    'Missing objectiveAcoustoelasticResidual on MATLAB path.');
assert(~isempty(which('objectiveAcoustoelasticComplexDeterminant')), ...
    'Missing objectiveAcoustoelasticComplexDeterminant on MATLAB path.');
assert(~isempty(which('buildAcoustoelasticMatrix')), ...
    'Missing buildAcoustoelasticMatrix on MATLAB path.');
assert(~isempty(which('defaultAcoustoelasticIOPHGOOptions')), ...
    'Missing defaultAcoustoelasticIOPHGOOptions on MATLAB path.');
assert(~isempty(which('computeAcoustoelasticABGFromIOPHGO')), ...
    'Missing computeAcoustoelasticABGFromIOPHGO on MATLAB path.');
assert(~isempty(which('computeAcoustoelasticAlphaBetaGamma')), ...
    'Missing computeAcoustoelasticAlphaBetaGamma on MATLAB path.');
assert(~isempty(which('computeAcoustoelasticPrestressSigma')), ...
    'Missing computeAcoustoelasticPrestressSigma on MATLAB path.');
assert(~isempty(which('computeAcoustoelasticSRoots')), ...
    'Missing computeAcoustoelasticSRoots on MATLAB path.');
assert(~isempty(which('solveAcoustoelasticHGOStretch')), ...
    'Missing solveAcoustoelasticHGOStretch on MATLAB path.');
assert(~isempty(which('run_acoustoelastic_iop_hgo_atlas_branch')), ...
    'Missing run_acoustoelastic_iop_hgo_atlas_branch on MATLAB path.');
assert(~isempty(which('diagnose_acoustoelastic_iop_hgo_branch_policy')), ...
    'Missing diagnose_acoustoelastic_iop_hgo_branch_policy on MATLAB path.');
assert(~isempty(which('run_acoustoelastic_iop_hgo_A0_backward')), ...
    'Missing run_acoustoelastic_iop_hgo_A0_backward on MATLAB path.');
assert(~isempty(which('run_acoustoelastic_iop_hgo_A0_complexC')), ...
    'Missing run_acoustoelastic_iop_hgo_A0_complexC on MATLAB path.');
assert(~isempty(which('run_acoustoelastic_iop_hgo_direct_alpha_beta_gamma')), ...
    'Missing run_acoustoelastic_iop_hgo_direct_alpha_beta_gamma on MATLAB path.');
assert(~isempty(which('compare_acoustoelastic_iop_hgo_tracking_strategies')), ...
    'Missing compare_acoustoelastic_iop_hgo_tracking_strategies on MATLAB path.');
assert(~isempty(which('summarizeAcoustoelasticIOPHGOTrackingQuality')), ...
    'Missing summarizeAcoustoelasticIOPHGOTrackingQuality on MATLAB path.');
assert(~isempty(which('diagnose_acoustoelastic_iop_hgo_grid_convergence')), ...
    'Missing diagnose_acoustoelastic_iop_hgo_grid_convergence on MATLAB path.');
assert(~isempty(which('diagnose_acoustoelastic_iop_hgo_dimensionless_A1')), ...
    'Missing diagnose_acoustoelastic_iop_hgo_dimensionless_A1 on MATLAB path.');
assert(~isempty(which('diagnose_acoustoelastic_iop_hgo_low_frequency_modal_atlas')), ...
    'Missing diagnose_acoustoelastic_iop_hgo_low_frequency_modal_atlas on MATLAB path.');
assert(~isempty(which('diagnose_acoustoelastic_iop_hgo_matrix_variants')), ...
    'Missing diagnose_acoustoelastic_iop_hgo_matrix_variants on MATLAB path.');
assert(~isempty(which('diagnose_acoustoelastic_iop_hgo_modal_atlas')), ...
    'Missing diagnose_acoustoelastic_iop_hgo_modal_atlas on MATLAB path.');
assert(~isempty(which('diagnose_acoustoelastic_iop_hgo_residual_landscape')), ...
    'Missing diagnose_acoustoelastic_iop_hgo_residual_landscape on MATLAB path.');
assert(~isempty(which('track_acoustoelastic_iop_hgo_raw_branch1_candidate')), ...
    'Missing track_acoustoelastic_iop_hgo_raw_branch1_candidate on MATLAB path.');
assert(~isempty(which('sweep_acoustoelastic_iop_hgo_A0_backward')), ...
    'Missing sweep_acoustoelastic_iop_hgo_A0_backward on MATLAB path.');
assert(~isempty(which('test_acoustoelastic_iop_hgo_constitutive_identity')), ...
    'Missing test_acoustoelastic_iop_hgo_constitutive_identity on MATLAB path.');
assert(~isempty(which('test_acoustoelastic_iop_hgo_strictA0_smoke')), ...
    'Missing test_acoustoelastic_iop_hgo_strictA0_smoke on MATLAB path.');

fprintf('\nChecking Acoustoelastic legacy compatibility wrappers...\n');
assert(~isempty(which('defaultLi2024AcoustoelasticOptions')), ...
    'Missing legacy wrapper defaultLi2024AcoustoelasticOptions on MATLAB path.');
assert(~isempty(which('solveDispersionIOPHGO_Li2024')), ...
    'Missing legacy wrapper solveDispersionIOPHGO_Li2024 on MATLAB path.');
assert(~isempty(which('solveDispersionIOPHGOAtlasBranch_Li2024')), ...
    'Missing legacy wrapper solveDispersionIOPHGOAtlasBranch_Li2024 on MATLAB path.');
assert(~isempty(which('solveDispersionAtlasBranch_Li2024_Acoustoelastic')), ...
    'Missing legacy wrapper solveDispersionAtlasBranch_Li2024_Acoustoelastic on MATLAB path.');
assert(~isempty(which('solveDispersion_Li2024_Acoustoelastic')), ...
    'Missing legacy wrapper solveDispersion_Li2024_Acoustoelastic on MATLAB path.');
assert(~isempty(which('solveDispersionComplexC_Li2024_Acoustoelastic')), ...
    'Missing legacy wrapper solveDispersionComplexC_Li2024_Acoustoelastic on MATLAB path.');
assert(~isempty(which('computeABGFromIOPHGO_Li2024')), ...
    'Missing legacy wrapper computeABGFromIOPHGO_Li2024 on MATLAB path.');
assert(~isempty(which('computeAlphaBetaGamma_Li2024')), ...
    'Missing legacy wrapper computeAlphaBetaGamma_Li2024 on MATLAB path.');
assert(~isempty(which('computePrestressSigma_Li2024')), ...
    'Missing legacy wrapper computePrestressSigma_Li2024 on MATLAB path.');
assert(~isempty(which('solveStretchHGO_Li2024')), ...
    'Missing legacy wrapper solveStretchHGO_Li2024 on MATLAB path.');
assert(~isempty(which('computeSRoots_Li2024')), ...
    'Missing legacy wrapper computeSRoots_Li2024 on MATLAB path.');
assert(~isempty(which('objective_Li2024_Acoustoelastic')), ...
    'Missing legacy wrapper objective_Li2024_Acoustoelastic on MATLAB path.');
assert(~isempty(which('objectiveComplexDet_Li2024_Acoustoelastic')), ...
    'Missing legacy wrapper objectiveComplexDet_Li2024_Acoustoelastic on MATLAB path.');
assert(~isempty(which('buildMatrix_Li2024_Acoustoelastic')), ...
    'Missing legacy wrapper buildMatrix_Li2024_Acoustoelastic on MATLAB path.');

fprintf('\n[1/3] Acoustoelastic IOP/HGO constitutive identity test\n');
test_acoustoelastic_iop_hgo_constitutive_identity;

fprintf('\n[2/3] Acoustoelastic IOP/HGO strict-A0 atlas branch smoke test\n');
test_acoustoelastic_iop_hgo_strictA0_smoke;

fprintf('\n[3/3] mRLFE smoke test\n');
test_mrlfe_smoke;

fprintf('\nAll maintained smoke tests passed.\n');

function assertNumericClose(actual, expected, tol, message)
%ASSERTNUMERICCLOSE Strict numeric comparison that treats matching empty arrays as equal.
if isempty(actual) && isempty(expected)
    return;
end
assert(isequal(size(actual), size(expected)), message);
assert(max(abs(actual(:) - expected(:))) < tol, message);
end
