clear; clc;
startup

% Run GUI adapter, sweep, and fitting smoke tests.

fprintf('\nRunning GUI smoke tests...\n');
fprintf('--------------------------\n');

fprintf('\nChecking GUI adapter path functions...\n');
assertFunctionsOnPath({ ...
    'LambFundamental_GUI', ...
    'FitTool_GUI', ...
    'createFittingTab', ...
    'guiRunRayleighLambModel', ...
    'guiRunMRLFEModel', ...
    'guiRunAcoustoelasticIOPHGOModel', ...
    'guiBuildAcoustoelasticIOPHGOOptions', ...
    'guiBuildAcoustoelasticIOPHGORequest', ...
    'guiNormalizeRawResult', ...
    'guiNormalizedBranchToTable', ...
    'guiNormalizedBranchesToTables', ...
    'guiGetNormalizedBranchPlotData', ...
    'guiBuildSweepRequest', ...
    'guiRunSweep', ...
    'guiRunMRLFESweep', ...
    'guiNormalizeMRLFESweep', ...
    'guiRunAcoustoelasticIOPHGOSweep', ...
    'guiNormalizeAcoustoelasticIOPHGOSweep', ...
    'guiPlotSweepResult', ...
    'guiGetSweepRegistry', ...
    'guiGetSweepFamilyConfig', ...
    'guiGetSweepParameterConfig', ...
    'guiFormatSweepValues', ...
    'guiGetFitRegistry', ...
    'guiBuildFitRequest', ...
    'guiRunFit', ...
    'guiFitRLSolver', ...
    'guiFitMRLFESolver', ...
    'guiFitAcoustoelasticIOPHGOSolver', ...
    'guiNormalizeFitResult', ...
    'guiPlotFitResult'}, ...
    'GUI adapter/helper');

fprintf('\n[GUI 1/10] GUI normalized adapters smoke test\n');
test_gui_normalized_adapters_smoke;

fprintf('\n[GUI 2/10] GUI sweep adapters smoke test\n');
test_gui_sweep_adapters_smoke;

fprintf('\n[GUI 3/10] GUI sweep registry smoke test\n');
test_gui_sweep_registry_smoke;

fprintf('\n[GUI 4/10] Acoustoelastic IOP/HGO GUI sweep adapter smoke test\n');
test_gui_acoustoelastic_iop_hgo_sweep_adapter_smoke;

fprintf('\n[GUI 5/10] Acoustoelastic IOP/HGO main GUI adapter smoke test\n');
test_gui_acoustoelastic_iop_hgo_main_adapter_smoke;

fprintf('\n[GUI 6/10] GUI fitting backend contract test\n');
test_gui_fit_registry_contract;

fprintf('\n[GUI 7/10] FitTool model registry contract test\n');
test_fit_tool_model_registry_contract;

fprintf('\n[GUI 8/10] GUI mRLFE fixed etaS fit contract test\n');
test_gui_mrlfe_fixed_etaS_fit_contract;

fprintf('\n[GUI 9/10] GUI mRLFE fit route policy contract test\n');
test_gui_mrlfe_fit_route_policy_contract;

fprintf('\n[GUI 10/10] GUI mRLFE fast full-curve test\n');
test_gui_mrlfe_fit_full_curve_fast_contract;

fprintf('\nGUI smoke tests passed.\n');

function assertFunctionsOnPath(functionNames, label)
for i = 1:numel(functionNames)
    functionName = functionNames{i};
    assert(~isempty(which(functionName)), ...
        'Missing %s on MATLAB path: %s.', label, functionName);
end
end
