clear; clc;
startup

% Run GUI adapter and sweep smoke tests.

fprintf('\nRunning GUI smoke tests...\n');
fprintf('--------------------------\n');

fprintf('\nChecking GUI adapter path functions...\n');
assertFunctionsOnPath({ ...
    'guiRunRayleighLambModel', ...
    'guiRunMRLFEModel', ...
    'guiRunAcoustoelasticIOPHGOModel', ...
    'guiBuildAcoustoelasticIOPHGOOptions', ...
    'guiBuildAcoustoelasticIOPHGORequest', ...
    'guiNormalizeRawResult', ...
    'guiNormalizedBranchToTable', ...
    'guiNormalizedBranchesToTables', ...
    'guiGetNormalizedBranchPlotData', ...
    'guiBuildSweepRequest', ...
    'guiRunSweep', ...
    'guiRunMRLFESweep', ...
    'guiNormalizeMRLFESweep', ...
    'guiRunAcoustoelasticIOPHGOSweep', ...
    'guiNormalizeAcoustoelasticIOPHGOSweep', ...
    'guiPlotSweepResult', ...
    'guiGetSweepRegistry', ...
    'guiGetSweepFamilyConfig', ...
    'guiGetSweepParameterConfig', ...
    'guiFormatSweepValues'}, ...
    'GUI adapter/helper');

fprintf('\n[GUI 1/5] GUI normalized adapters smoke test\n');
test_gui_normalized_adapters_smoke;

fprintf('\n[GUI 2/5] GUI sweep adapters smoke test\n');
test_gui_sweep_adapters_smoke;

fprintf('\n[GUI 3/5] GUI sweep registry smoke test\n');
test_gui_sweep_registry_smoke;

fprintf('\n[GUI 4/5] Acoustoelastic IOP/HGO GUI sweep adapter smoke test\n');
test_gui_acoustoelastic_iop_hgo_sweep_adapter_smoke;

fprintf('\n[GUI 5/5] Acoustoelastic IOP/HGO main GUI adapter smoke test\n');
test_gui_acoustoelastic_iop_hgo_main_adapter_smoke;

fprintf('\nGUI smoke tests passed.\n');

function assertFunctionsOnPath(functionNames, label)
for i = 1:numel(functionNames)
    functionName = functionNames{i};
    assert(~isempty(which(functionName)), ...
        'Missing %s on MATLAB path: %s.', label, functionName);
end
end
