clear; clc;
startup

% Run all maintained smoke and consistency tests.
%
% This script is intended as the first validation step after refactors,
% folder reorganizations, or path changes. It should remain lightweight and
% avoid generating figures.

fprintf('\nRunning Lamb Fundamental Solver smoke tests...\n');
fprintf('---------------------------------------------\n');


%% GUI adapter path checks
fprintf('\nChecking GUI adapter path functions...\n');
assert(~isempty(which('guiRunRayleighLambModel')), ...
    'Missing GUI adapter function guiRunRayleighLambModel on MATLAB path.');
assert(~isempty(which('guiRunMRLFEModel')), ...
    'Missing GUI adapter function guiRunMRLFEModel on MATLAB path.');
assert(~isempty(which('guiRunAcoustoelasticIOPHGOModel')), ...
    'Missing GUI adapter function guiRunAcoustoelasticIOPHGOModel on MATLAB path.');
assert(~isempty(which('guiNormalizeRawResult')), ...
    'Missing GUI helper function guiNormalizeRawResult on MATLAB path.');
assert(~isempty(which('guiNormalizedBranchToTable')), ...
    'Missing GUI helper function guiNormalizedBranchToTable on MATLAB path.');
assert(~isempty(which('guiNormalizedBranchesToTables')), ...
    'Missing GUI helper function guiNormalizedBranchesToTables on MATLAB path.');
assert(~isempty(which('guiGetNormalizedBranchPlotData')), ...
    'Missing GUI helper function guiGetNormalizedBranchPlotData on MATLAB path.');

%% Rayleigh-Lamb primary API path checks
fprintf('\nChecking Rayleigh-Lamb primary rl* API functions...\n');
assert(~isempty(which('rlBuildFrequencyVector')), ...
    'Missing Rayleigh-Lamb wrapper function rlBuildFrequencyVector on MATLAB path.');
assert(~isempty(which('rlComputeFundamentalLambModes')), ...
    'Missing Rayleigh-Lamb wrapper function rlComputeFundamentalLambModes on MATLAB path.');
assert(~isempty(which('rlComputeGeometry')), ...
    'Missing Rayleigh-Lamb wrapper function rlComputeGeometry on MATLAB path.');
assert(~isempty(which('rlComputeMaterial')), ...
    'Missing Rayleigh-Lamb wrapper function rlComputeMaterial on MATLAB path.');
assert(~isempty(which('rlDefaultOptions')), ...
    'Missing Rayleigh-Lamb wrapper function rlDefaultOptions on MATLAB path.');
assert(~isempty(which('rlDefaultParams')), ...
    'Missing Rayleigh-Lamb wrapper function rlDefaultParams on MATLAB path.');
assert(~isempty(which('rlMakeBranchSpec')), ...
    'Missing Rayleigh-Lamb wrapper function rlMakeBranchSpec on MATLAB path.');
assert(~isempty(which('rlValidateOptions')), ...
    'Missing Rayleigh-Lamb wrapper function rlValidateOptions on MATLAB path.');
assert(~isempty(which('rlValidateParams')), ...
    'Missing Rayleigh-Lamb wrapper function rlValidateParams on MATLAB path.');
assert(~isempty(which('rlAResidual')), ...
    'Missing Rayleigh-Lamb wrapper function rlAResidual on MATLAB path.');
assert(~isempty(which('rlSResidual')), ...
    'Missing Rayleigh-Lamb wrapper function rlSResidual on MATLAB path.');
assert(~isempty(which('rlComputeA0ThinPlateApproximation')), ...
    'Missing Rayleigh-Lamb wrapper function rlComputeA0ThinPlateApproximation on MATLAB path.');
assert(~isempty(which('rlComputeAnalyticalApproximations')), ...
    'Missing Rayleigh-Lamb wrapper function rlComputeAnalyticalApproximations on MATLAB path.');
assert(~isempty(which('rlComputeS0ExtensionalApproximation')), ...
    'Missing Rayleigh-Lamb wrapper function rlComputeS0ExtensionalApproximation on MATLAB path.');
assert(~isempty(which('rlSolveFundamentalBranch')), ...
    'Missing Rayleigh-Lamb wrapper function rlSolveFundamentalBranch on MATLAB path.');


%% Rayleigh-Lamb minimal numerical regression fixtures
fprintf('\nChecking Rayleigh-Lamb minimal numerical regression fixtures...\n');
regressionTol = 1e-12;

regressionParams = rlDefaultParams();
regressionParams.fmin = 10;
regressionParams.fmax = 100;
regressionParams.numFrequencyPoints = 10;
regressionParams.frequencySpacing = "linspace";

regressionOptions = rlDefaultOptions();
regressionOptions.computeA0 = true;
regressionOptions.computeS0 = true;
regressionOptions.computeMRLFE = false;

regressionResults = rlComputeFundamentalLambModes(regressionParams, regressionOptions);
regressionRepeat = rlComputeFundamentalLambModes(regressionParams, regressionOptions);
expectedSize = size(rlBuildFrequencyVector(regressionParams));

assert(isfield(regressionResults, 'grid') && isfield(regressionResults.grid, 'frequency'), ...
    'Rayleigh-Lamb regression results are missing grid.frequency.');
assert(isfield(regressionResults, 'modes') && isfield(regressionResults.modes, 'A0'), ...
    'Rayleigh-Lamb regression results are missing A0 mode output.');
assert(isfield(regressionResults.modes, 'S0'), ...
    'Rayleigh-Lamb regression results are missing S0 mode output.');

regressionFrequency = regressionResults.grid.frequency;
regressionA0 = regressionResults.modes.A0;
regressionS0 = regressionResults.modes.S0;

assert(isequal(size(regressionFrequency), expectedSize), ...
    'Rayleigh-Lamb regression frequency size does not match the requested grid.');
assert(isequal(size(regressionA0.frequency), expectedSize), ...
    'Rayleigh-Lamb A0 regression frequency size does not match the requested grid.');
assert(isequal(size(regressionS0.frequency), expectedSize), ...
    'Rayleigh-Lamb S0 regression frequency size does not match the requested grid.');
assert(isequal(size(regressionA0.Cp), expectedSize), ...
    'Rayleigh-Lamb A0 regression Cp size does not match the requested grid.');
assert(isequal(size(regressionS0.Cp), expectedSize), ...
    'Rayleigh-Lamb S0 regression Cp size does not match the requested grid.');

assert(all(isfinite(regressionFrequency(:))), ...
    'Rayleigh-Lamb regression frequencies must be finite.');
assert(all(isfinite(regressionA0.Cp(:)) & regressionA0.Cp(:) > 0), ...
    'Rayleigh-Lamb A0 regression Cp values must be finite and positive.');
assert(all(isfinite(regressionS0.Cp(:)) & regressionS0.Cp(:) > 0), ...
    'Rayleigh-Lamb S0 regression Cp values must be finite and positive.');
assert(any(abs(regressionA0.Cp(:) - regressionS0.Cp(:)) > regressionTol), ...
    'Rayleigh-Lamb A0 and S0 regression Cp outputs should not be identical.');

assertNumericClose(regressionFrequency, regressionRepeat.grid.frequency, regressionTol, ...
    'Rayleigh-Lamb regression frequencies are not repeatable.');
assertNumericClose(regressionA0.Cp, regressionRepeat.modes.A0.Cp, regressionTol, ...
    'Rayleigh-Lamb A0 regression Cp values are not repeatable.');
assertNumericClose(regressionS0.Cp, regressionRepeat.modes.S0.Cp, regressionTol, ...
    'Rayleigh-Lamb S0 regression Cp values are not repeatable.');

fprintf('\n[1/5] GUI normalized adapters smoke test\n');
test_gui_normalized_adapters_smoke;

fprintf('\nChecking maintained acoustoelastic IOP/HGO wrappers and entrypoints...\n');
assert(~isempty(which('solveAcoustoelasticIOPHGOBranch')), ...
    'Missing solveAcoustoelasticIOPHGOBranch on MATLAB path.');
assert(~isempty(which('solveAcoustoelasticIOPHGOAtlasBranch')), ...
    'Missing solveAcoustoelasticIOPHGOAtlasBranch on MATLAB path.');
assert(~isempty(which('solveAcoustoelasticAtlasBranch')), ...
    'Missing solveAcoustoelasticAtlasBranch on MATLAB path.');
assert(~isempty(which('solveAcoustoelasticIOPHGODispersion')), ...
    'Missing solveAcoustoelasticIOPHGODispersion on MATLAB path.');
assert(~isempty(which('solveAcoustoelasticDispersion')), ...
    'Missing solveAcoustoelasticDispersion on MATLAB path.');
assert(~isempty(which('solveAcoustoelasticComplexCDispersion')), ...
    'Missing solveAcoustoelasticComplexCDispersion on MATLAB path.');
assert(~isempty(which('objectiveAcoustoelasticResidual')), ...
    'Missing objectiveAcoustoelasticResidual on MATLAB path.');
assert(~isempty(which('objectiveAcoustoelasticComplexDeterminant')), ...
    'Missing objectiveAcoustoelasticComplexDeterminant on MATLAB path.');
assert(~isempty(which('buildAcoustoelasticMatrix')), ...
    'Missing buildAcoustoelasticMatrix on MATLAB path.');
assert(~isempty(which('defaultAcoustoelasticIOPHGOOptions')), ...
    'Missing defaultAcoustoelasticIOPHGOOptions on MATLAB path.');
assert(~isempty(which('aeNormalizeBranchPolicy')), ...
    'Missing aeNormalizeBranchPolicy on MATLAB path.');
assert(~isempty(which('aeRunSweep')), ...
    'Missing aeRunSweep on MATLAB path.');
assert(~isempty(which('aeSummarizeSweep')), ...
    'Missing aeSummarizeSweep on MATLAB path.');
assert(~isempty(which('computeAcoustoelasticABGFromIOPHGO')), ...
    'Missing computeAcoustoelasticABGFromIOPHGO on MATLAB path.');
assert(~isempty(which('computeAcoustoelasticAlphaBetaGamma')), ...
    'Missing computeAcoustoelasticAlphaBetaGamma on MATLAB path.');
assert(~isempty(which('computeAcoustoelasticPrestressSigma')), ...
    'Missing computeAcoustoelasticPrestressSigma on MATLAB path.');
assert(~isempty(which('computeAcoustoelasticSRoots')), ...
    'Missing computeAcoustoelasticSRoots on MATLAB path.');
assert(~isempty(which('solveAcoustoelasticHGOStretch')), ...
    'Missing solveAcoustoelasticHGOStretch on MATLAB path.');
assert(~isempty(which('run_acoustoelastic_iop_hgo_atlas_branch')), ...
    'Missing run_acoustoelastic_iop_hgo_atlas_branch on MATLAB path.');
assert(~isempty(which('diagnose_acoustoelastic_iop_hgo_branch_policy')), ...
    'Missing diagnose_acoustoelastic_iop_hgo_branch_policy on MATLAB path.');
assert(~isempty(which('run_acoustoelastic_iop_hgo_A0_backward')), ...
    'Missing run_acoustoelastic_iop_hgo_A0_backward on MATLAB path.');
assert(~isempty(which('run_acoustoelastic_iop_hgo_A0_complexC')), ...
    'Missing run_acoustoelastic_iop_hgo_A0_complexC on MATLAB path.');
assert(~isempty(which('run_acoustoelastic_iop_hgo_direct_alpha_beta_gamma')), ...
    'Missing run_acoustoelastic_iop_hgo_direct_alpha_beta_gamma on MATLAB path.');
assert(~isempty(which('compare_acoustoelastic_iop_hgo_tracking_strategies')), ...
    'Missing compare_acoustoelastic_iop_hgo_tracking_strategies on MATLAB path.');
assert(~isempty(which('compare_acoustoelastic_iop_hgo_branch_policies')), ...
    'Missing compare_acoustoelastic_iop_hgo_branch_policies on MATLAB path.');
assert(~isempty(which('summarizeAcoustoelasticIOPHGOTrackingQuality')), ...
    'Missing summarizeAcoustoelasticIOPHGOTrackingQuality on MATLAB path.');
assert(~isempty(which('diagnose_acoustoelastic_iop_hgo_grid_convergence')), ...
    'Missing diagnose_acoustoelastic_iop_hgo_grid_convergence on MATLAB path.');
assert(~isempty(which('diagnose_acoustoelastic_iop_hgo_dimensionless_A1')), ...
    'Missing diagnose_acoustoelastic_iop_hgo_dimensionless_A1 on MATLAB path.');
assert(~isempty(which('diagnose_acoustoelastic_iop_hgo_low_frequency_modal_atlas')), ...
    'Missing diagnose_acoustoelastic_iop_hgo_low_frequency_modal_atlas on MATLAB path.');
assert(~isempty(which('diagnose_acoustoelastic_iop_hgo_matrix_variants')), ...
    'Missing diagnose_acoustoelastic_iop_hgo_matrix_variants on MATLAB path.');
assert(~isempty(which('diagnose_acoustoelastic_iop_hgo_modal_atlas')), ...
    'Missing diagnose_acoustoelastic_iop_hgo_modal_atlas on MATLAB path.');
assert(~isempty(which('diagnose_acoustoelastic_iop_hgo_residual_landscape')), ...
    'Missing diagnose_acoustoelastic_iop_hgo_residual_landscape on MATLAB path.');
assert(~isempty(which('track_acoustoelastic_iop_hgo_raw_branch1_candidate')), ...
    'Missing track_acoustoelastic_iop_hgo_raw_branch1_candidate on MATLAB path.');
assert(~isempty(which('sweep_acoustoelastic_iop_hgo_A0_backward')), ...
    'Missing sweep_acoustoelastic_iop_hgo_A0_backward on MATLAB path.');
assert(~isempty(which('sweep_acoustoelastic_iop_hgo_iop')), ...
    'Missing sweep_acoustoelastic_iop_hgo_iop on MATLAB path.');
assert(~isempty(which('sweep_acoustoelastic_iop_hgo_mu')), ...
    'Missing sweep_acoustoelastic_iop_hgo_mu on MATLAB path.');
assert(~isempty(which('test_acoustoelastic_iop_hgo_constitutive_identity')), ...
    'Missing test_acoustoelastic_iop_hgo_constitutive_identity on MATLAB path.');
assert(~isempty(which('test_acoustoelastic_iop_hgo_branch_policy_aliases')), ...
    'Missing test_acoustoelastic_iop_hgo_branch_policy_aliases on MATLAB path.');
assert(~isempty(which('test_acoustoelastic_iop_hgo_strictA0_smoke')), ...
    'Missing test_acoustoelastic_iop_hgo_strictA0_smoke on MATLAB path.');

fprintf('\n[2/5] Acoustoelastic IOP/HGO branch policy alias test\n');
test_acoustoelastic_iop_hgo_branch_policy_aliases;

fprintf('\n[3/5] Acoustoelastic IOP/HGO constitutive identity test\n');
test_acoustoelastic_iop_hgo_constitutive_identity;

fprintf('\n[4/5] Acoustoelastic IOP/HGO legacy strict-A0 atlas branch smoke test\n');
test_acoustoelastic_iop_hgo_strictA0_smoke;

fprintf('\n[5/5] mRLFE smoke test\n');
test_mrlfe_smoke;

fprintf('\nAll maintained smoke tests passed.\n');


function assertNumericClose(actual, expected, tol, message)
%ASSERTNUMERICCLOSE Strict numeric comparison that treats matching empty arrays as equal.
if isempty(actual) && isempty(expected)
    return;
end
assert(isequal(size(actual), size(expected)), message);
assert(max(abs(actual(:) - expected(:))) < tol, message);
end
