clear; clc;
startup

% Run all maintained smoke and consistency tests.
%
% This script is intended as the first validation step after refactors,
% folder reorganizations, or path changes. It should remain lightweight and
% avoid generating figures. Historical diagnostics and legacy aliases are not
% part of this smoke-test surface; see docs/maintained_entrypoints.md.

fprintf('\nRunning Lamb Fundamental Solver smoke tests...\n');
fprintf('---------------------------------------------\n');

%% GUI adapter path checks
fprintf('\nChecking GUI adapter path functions...\n');
assertFunctionsOnPath({ ...
    'guiRunRayleighLambModel', ...
    'guiRunMRLFEModel', ...
    'guiRunAcoustoelasticIOPHGOModel', ...
    'guiBuildAcoustoelasticIOPHGOOptions', ...
    'guiBuildAcoustoelasticIOPHGORequest', ...
    'guiNormalizeRawResult', ...
    'guiNormalizedBranchToTable', ...
    'guiNormalizedBranchesToTables', ...
    'guiGetNormalizedBranchPlotData', ...
    'guiBuildSweepRequest', ...
    'guiRunSweep', ...
    'guiRunMRLFESweep', ...
    'guiNormalizeMRLFESweep', ...
    'guiRunAcoustoelasticIOPHGOSweep', ...
    'guiNormalizeAcoustoelasticIOPHGOSweep', ...
    'guiPlotSweepResult', ...
    'guiGetSweepRegistry', ...
    'guiGetSweepFamilyConfig', ...
    'guiGetSweepParameterConfig', ...
    'guiFormatSweepValues'}, ...
    'GUI adapter/helper');

%% Shared material helpers
fprintf('\nChecking shared elastic material helpers...\n');
assertFunctionsOnPath({ ...
    'elasticFromMuNu', ...
    'elasticFromLame'}, ...
    'shared elastic material helper');

elastic = elasticFromMuNu(75e3, 0.4999, 1070);
assertNumericClose(elastic.E, 2 * 75e3 * (1 + 0.4999), 1e-10, ...
    'elasticFromMuNu returned an unexpected Young modulus.');
assertNumericClose(elastic.mu, 75e3, 1e-12, ...
    'elasticFromMuNu should preserve mu.');
assert(elastic.lambda > 0 && elastic.K > 0 && elastic.CL > elastic.CT, ...
    'elasticFromMuNu should return positive lambda/K and CL > CT.');

%% Rayleigh-Lamb primary API path checks
fprintf('\nChecking Rayleigh-Lamb primary rl* API functions...\n');
assertFunctionsOnPath({ ...
    'setSweepPlotLimits', ...
    'rlBuildFrequencyVector', ...
    'rlComputeFundamentalLambModes', ...
    'rlComputeGeometry', ...
    'rlComputeMaterial', ...
    'rlDefaultOptions', ...
    'rlDefaultParams', ...
    'rlMakeBranchSpec', ...
    'rlValidateOptions', ...
    'rlValidateParams', ...
    'rlAResidual', ...
    'rlSResidual', ...
    'rlComputeA0ThinPlateApproximation', ...
    'rlComputeAnalyticalApproximations', ...
    'rlComputeS0ExtensionalApproximation', ...
    'rlSolveFundamentalBranch'}, ...
    'Rayleigh-Lamb maintained API');

fprintf('\nChecking Rayleigh-Lamb sweep helper functions...\n');
assertFunctionsOnPath({ ...
    'rlDefaultSweepParams', ...
    'rlDefaultSweepOptions', ...
    'rlMakeSweepSpec', ...
    'rlRunSweepExample', ...
    'rlOutputFolder', ...
    'rlWriteSweepOutputs', ...
    'rlSaveExampleFigure'}, ...
    'Rayleigh-Lamb sweep helper');

%% Rayleigh-Lamb minimal numerical regression fixtures
fprintf('\nChecking Rayleigh-Lamb minimal numerical regression fixtures...\n');
regressionTol = 1e-12;

regressionParams = rlDefaultParams();
regressionParams.fmin = 10;
regressionParams.fmax = 100;
regressionParams.numFrequencyPoints = 10;
regressionParams.frequencySpacing = "linspace";

regressionOptions = rlDefaultOptions();
regressionOptions.computeA0 = true;
regressionOptions.computeS0 = true;
regressionOptions.computeMRLFE = false;

regressionResults = rlComputeFundamentalLambModes(regressionParams, regressionOptions);
regressionRepeat = rlComputeFundamentalLambModes(regressionParams, regressionOptions);
expectedSize = size(rlBuildFrequencyVector(regressionParams));

assert(isfield(regressionResults, 'grid') && isfield(regressionResults.grid, 'frequency'), ...
    'Rayleigh-Lamb regression results are missing grid.frequency.');
assert(isfield(regressionResults, 'modes') && isfield(regressionResults.modes, 'A0'), ...
    'Rayleigh-Lamb regression results are missing A0 mode output.');
assert(isfield(regressionResults.modes, 'S0'), ...
    'Rayleigh-Lamb regression results are missing S0 mode output.');
assert(string(regressionResults.material.modelType) == "ShearPoisson", ...
    'Rayleigh-Lamb default material model must be ShearPoisson.');

regressionFrequency = regressionResults.grid.frequency;
regressionA0 = regressionResults.modes.A0;
regressionS0 = regressionResults.modes.S0;

assert(isequal(size(regressionFrequency), expectedSize), ...
    'Rayleigh-Lamb regression frequency size does not match the requested grid.');
assert(isequal(size(regressionA0.frequency), expectedSize), ...
    'Rayleigh-Lamb A0 regression frequency size does not match the requested grid.');
assert(isequal(size(regressionS0.frequency), expectedSize), ...
    'Rayleigh-Lamb S0 regression frequency size does not match the requested grid.');
assert(isequal(size(regressionA0.Cp), expectedSize), ...
    'Rayleigh-Lamb A0 regression Cp size does not match the requested grid.');
assert(isequal(size(regressionS0.Cp), expectedSize), ...
    'Rayleigh-Lamb S0 regression Cp size does not match the requested grid.');

assert(all(isfinite(regressionFrequency(:))), ...
    'Rayleigh-Lamb regression frequencies must be finite.');
assert(all(isfinite(regressionA0.Cp(:)) & regressionA0.Cp(:) > 0), ...
    'Rayleigh-Lamb A0 regression Cp values must be finite and positive.');
assert(all(isfinite(regressionS0.Cp(:)) & regressionS0.Cp(:) > 0), ...
    'Rayleigh-Lamb S0 regression Cp values must be finite and positive.');
assert(any(abs(regressionA0.Cp(:) - regressionS0.Cp(:)) > regressionTol), ...
    'Rayleigh-Lamb A0 and S0 regression Cp outputs should not be identical.');

assertNumericClose(regressionFrequency, regressionRepeat.grid.frequency, regressionTol, ...
    'Rayleigh-Lamb regression frequencies are not repeatable.');
assertNumericClose(regressionA0.Cp, regressionRepeat.modes.A0.Cp, regressionTol, ...
    'Rayleigh-Lamb A0 regression Cp values are not repeatable.');
assertNumericClose(regressionS0.Cp, regressionRepeat.modes.S0.Cp, regressionTol, ...
    'Rayleigh-Lamb S0 regression Cp values are not repeatable.');

%% GUI smoke tests
fprintf('\n[1/26] GUI normalized adapters smoke test\n');
test_gui_normalized_adapters_smoke;

fprintf('\n[2/26] GUI sweep adapters smoke test\n');
test_gui_sweep_adapters_smoke;

fprintf('\n[3/26] GUI sweep registry smoke test\n');
test_gui_sweep_registry_smoke;

fprintf('\n[4/26] Acoustoelastic IOP/HGO GUI sweep adapter smoke test\n');
test_gui_acoustoelastic_iop_hgo_sweep_adapter_smoke;

fprintf('\n[5/26] Acoustoelastic IOP/HGO main GUI adapter smoke test\n');
test_gui_acoustoelastic_iop_hgo_main_adapter_smoke;

%% Acoustoelastic maintained API and tests
fprintf('\nChecking maintained acoustoelastic IOP/HGO API functions...\n');
assertFunctionsOnPath({ ...
    'solveAcoustoelasticIOPHGOBranch', ...
    'solveAcoustoelasticIOPHGOAtlasBranch', ...
    'solveAcoustoelasticAtlasBranch', ...
    'solveAcoustoelasticIOPHGODispersion', ...
    'solveAcoustoelasticDispersion', ...
    'solveAcoustoelasticComplexCDispersion', ...
    'objectiveAcoustoelasticResidual', ...
    'objectiveAcoustoelasticComplexDeterminant', ...
    'buildAcoustoelasticMatrix', ...
    'defaultAcoustoelasticIOPHGOOptions', ...
    'aeNormalizeBranchPolicy', ...
    'computeAcoustoelasticABGFromIOPHGO', ...
    'computeAcoustoelasticAlphaBetaGamma', ...
    'computeAcoustoelasticPrestressSigma', ...
    'computeAcoustoelasticSRoots', ...
    'solveAcoustoelasticHGOStretch', ...
    'summarizeAcoustoelasticIOPHGOTrackingQuality', ...
    'aeRunSweep', ...
    'aeSummarizeSweep'}, ...
    'Acoustoelastic maintained API');

fprintf('\nChecking maintained acoustoelastic analysis helpers...\n');
assertFunctionsOnPath({ ...
    'aeOutputFolder', ...
    'aeResolveResultFile', ...
    'aeRunLegacyScript', ...
    'aeDefaultSweepParams', ...
    'aeDefaultSweepOptions', ...
    'aeWriteSweepOutputs', ...
    'aeRunGridSweep', ...
    'aeSummarizeGridSweep', ...
    'aeBuildGridSweepCpCube', ...
    'aePlotSweepCp', ...
    'aePlotGridSweepCp', ...
    'aePlotGridSweepCpByAxis', ...
    'aePlotGridSweepFrequencySurfaceInteractive', ...
    'aeSaveExampleFigure', ...
    'aeDeleteExampleFigure', ...
    'aeScoreBranchIdentityCandidates', ...
    'aeBuildIdentityA0DiagnosticBranch', ...
    'aeDiagnoseAtlasA0TruncationCause', ...
    'aeAnalyzeBranchPersistenceCandidates', ...
    'aeRefineAtlasA0BranchPersistence', ...
    'aeClassifyAmbiguityRegime', ...
    'aeExtractRawBranch1Candidate'}, ...
    'Acoustoelastic maintained analysis helper');

fprintf('\nChecking maintained acoustoelastic public workflows...\n');
assertFunctionsOnPath({ ...
    'run_atlas_branch', ...
    'sweep_iop', ...
    'sweep_mu', ...
    'sweep_mu_iop'}, ...
    'Acoustoelastic maintained public workflow');

fprintf('\nChecking maintained acoustoelastic diagnostic evidence entrypoints...\n');
assertFunctionsOnPath({ ...
    'compare_atlasA0_vs_raw_branch1', ...
    'validate_atlas_raw_grid', ...
    'diagnose_raw_branch_corner', ...
    'diagnose_branch_families', ...
    'diagnose_sweep_reliability', ...
    'diagnose_atlas_truncation', ...
    'diagnose_idA0_plausibility'}, ...
    'Acoustoelastic maintained diagnostic evidence entrypoint');

fprintf('\nChecking maintained acoustoelastic tests...\n');
assertFunctionsOnPath({ ...
    'test_acoustoelastic_iop_hgo_branch_policy_validation', ...
    'test_acoustoelastic_iop_hgo_constitutive_identity', ...
    'test_acoustoelastic_iop_hgo_atlasA0_smoke', ...
    'test_acoustoelastic_iop_hgo_fallback_invalidation', ...
    'test_acoustoelastic_iop_hgo_internal_tracking_grid', ...
    'test_acoustoelastic_iop_hgo_identityA0_diagnostic_policy', ...
    'test_acoustoelastic_iop_hgo_short_entrypoints', ...
    'test_acoustoelastic_iop_hgo_branch_persistence_refinement', ...
    'test_ae_analyze_truncation_recovery'}, ...
    'Acoustoelastic maintained test');

fprintf('\n[6/26] Acoustoelastic atlas branch policy validation test\n');
test_acoustoelastic_iop_hgo_branch_policy_validation;

fprintf('\n[7/26] Acoustoelastic fallback invalidation policy test\n');
test_acoustoelastic_iop_hgo_fallback_invalidation;

fprintf('\n[8/26] Acoustoelastic internal tracking grid test\n');
test_acoustoelastic_iop_hgo_internal_tracking_grid;

fprintf('\n[9/26] Acoustoelastic truncation recovery helper unit test\n');
test_ae_analyze_truncation_recovery;

fprintf('\n[10/26] Acoustoelastic branch-persistence refinement unit test\n');
test_acoustoelastic_iop_hgo_branch_persistence_refinement;

fprintf('\n[11/26] Acoustoelastic IOP/HGO constitutive identity test\n');
test_acoustoelastic_iop_hgo_constitutive_identity;

fprintf('\n[12/26] Acoustoelastic IOP/HGO atlasA0 smoke test\n');
test_acoustoelastic_iop_hgo_atlasA0_smoke;

%% mRLFE maintained API and tests
fprintf('\nChecking maintained mRLFE tests...\n');
assertFunctionsOnPath({ ...
    'computeMRLFE', ...
    'objectiveMRLFEResidual', ...
    'mrlfeModelCandidateNames', ...
    'summarizeMRLFETrackingQuality', ...
    'compareMRLFETrackingStrategies', ...
    'test_mrlfe_smoke', ...
    'test_mrlfe_etaS_zero_limit', ...
    'test_mrlfe_elastic_reference_buffer', ...
    'test_mrlfe_residual_objective_contract', ...
    'test_mrlfe_internal_tracking_grid', ...
    'test_mrlfe_internal_tracking_grid_with_buffer', ...
    'test_mrlfe_viscous_default_internal_tracking_grid', ...
    'test_mrlfe_tracking_quality_summary', ...
    'test_mrlfe_tracking_strategy_comparison', ...
    'test_mrlfe_internal_grid_quality_guard', ...
    'test_mrlfe_maintained_entrypoints_naming', ...
    'test_mrlfe_model_candidate_names', ...
    'test_mrlfe_diagnostic_material_sweep_contract', ...
    'test_mrlfe_etaS_zero_diagnostic_selection'}, ...
    'mRLFE maintained test');

fprintf('\n[13/26] mRLFE smoke test\n');
test_mrlfe_smoke;

fprintf('\n[14/26] mRLFE etaS zero-limit contract test\n');
test_mrlfe_etaS_zero_limit;

fprintf('\n[15/26] mRLFE elastic-reference buffer contract test\n');
test_mrlfe_elastic_reference_buffer;

fprintf('\n[16/26] mRLFE residual objective contract test\n');
test_mrlfe_residual_objective_contract;

fprintf('\n[17/26] mRLFE internal tracking grid contract test\n');
test_mrlfe_internal_tracking_grid;

fprintf('\n[18/26] mRLFE internal tracking grid with buffer contract test\n');
test_mrlfe_internal_tracking_grid_with_buffer;

fprintf('\n[19/26] mRLFE viscous default internal tracking grid contract test\n');
test_mrlfe_viscous_default_internal_tracking_grid;

fprintf('\n[20/26] mRLFE tracking quality summary contract test\n');
test_mrlfe_tracking_quality_summary;

fprintf('\n[21/26] mRLFE tracking strategy comparison contract test\n');
test_mrlfe_tracking_strategy_comparison;

fprintf('\n[22/26] mRLFE internal-grid quality guard test\n');
test_mrlfe_internal_grid_quality_guard;

fprintf('\n[23/26] mRLFE maintained entrypoints naming guard test\n');
test_mrlfe_maintained_entrypoints_naming;

fprintf('\n[24/26] mRLFE model candidate names contract test\n');
test_mrlfe_model_candidate_names;

fprintf('\n[25/26] mRLFE diagnostic material sweep contract test\n');
test_mrlfe_diagnostic_material_sweep_contract;

fprintf('\n[26/26] mRLFE etaS zero diagnostic selection contract test\n');
test_mrlfe_etaS_zero_diagnostic_selection;

fprintf('\nAll maintained smoke tests passed.\n');


function assertFunctionsOnPath(functionNames, label)
for i = 1:numel(functionNames)
    functionName = functionNames{i};
    assert(~isempty(which(functionName)), ...
        'Missing %s on MATLAB path: %s.', label, functionName);
end
end

function assertNumericClose(actual, expected, tol, message)
if isempty(actual) && isempty(expected)
    return;
end
assert(isequal(size(actual), expectedSizeShim(expected)), message);
assert(max(abs(actual(:) - expected(:))) < tol, message);
end

function s = expectedSizeShim(x)
s = size(x);
end
