clear; clc; close all;
launchFolder = pwd;
startup

%COMPARE_ATLASA0_VS_RAW_BRANCH1 Compare official atlasA0, identityA0, and raw branch-1.
%
% Diagnostic only. This script does not promote raw_branch1 and does not modify
% result.Cp or result.validCp. It compares the official atlasA0 output,
% identityA0Diagnostic candidate output, and the global modal-atlas raw_branch1
% curve generated by track_raw_branch1 or regenerated on demand from the
% consolidated modal-atlas outputs.
%
% Preferred input:
%   Results/ae_iop_hgo/raw_branch1/raw_branch1_curve.csv
%
% If the preferred input is missing, this script regenerates it from:
%   Results/ae_iop_hgo/modal_atlas
%
% Outputs:
%   Results/ae_iop_hgo/atlas_vs_raw_branch1

outputFolder = aeOutputFolder(launchFolder, 'atlas_vs_raw_branch1');
plotFolder = fullfile(outputFolder, 'plots');
if ~exist(plotFolder, 'dir')
    mkdir(plotFolder);
end

rawCurveFile = resolveOrBuildRawCurveFile(launchFolder);
rawCurve = readtable(rawCurveFile);

requiredColumns = {'IOP_mmHg','Frequency_Hz','Cp_mps'};
for i = 1:numel(requiredColumns)
    if ~ismember(requiredColumns{i}, rawCurve.Properties.VariableNames)
        error('raw_branch1_curve.csv is missing required column: %s', requiredColumns{i});
    end
end

IOP_mmHg = unique(rawCurve.IOP_mmHg, 'stable');
options = defaultComparisonOptions();

pointRows = table();
summaryRows = table();
caseResults = struct();

for i = 1:numel(IOP_mmHg)
    iop = IOP_mmHg(i);
    rawCase = rawCurve(rawCurve.IOP_mmHg == iop, :);
    rawCase = sortrows(rawCase, 'Frequency_Hz');

    params = defaultExampleParams();
    params.IOP = iop * 133.322;
    params.frequency = rawCase.Frequency_Hz(:).';

    atlasOptions = defaultSolverOptions();
    atlasOptions.atlasBranchPolicy = "atlasA0";
    atlasResult = solveAcoustoelasticIOPHGOBranch(params, atlasOptions);

    identityOptions = atlasOptions;
    identityOptions.atlasBranchPolicy = "identityA0Diagnostic";
    identityResult = solveAcoustoelasticIOPHGOBranch(params, identityOptions);

    comparison = compareCase(iop, rawCase, atlasResult, identityResult, options);
    pointRows = [pointRows; comparison.points]; %#ok<AGROW>
    summaryRows = [summaryRows; comparison.summary]; %#ok<AGROW>

    caseResults(i).IOP_mmHg = iop;
    caseResults(i).rawCase = rawCase;
    caseResults(i).atlasResult = atlasResult;
    caseResults(i).identityResult = identityResult;
    caseResults(i).comparison = comparison;

    plotCaseComparison(comparison.points, iop, plotFolder);

    fprintf('IOP %.1f mmHg: %s | atlas median err %.4g | identity median err %.4g\n', ...
        iop, comparison.summary.Classification, ...
        comparison.summary.MedianAtlasRawRelError, ...
        comparison.summary.MedianIdentityRawRelError);
end

plotSummary(summaryRows, plotFolder);

writetable(pointRows, fullfile(outputFolder, 'atlas_vs_raw_branch1_points.csv'));
writetable(summaryRows, fullfile(outputFolder, 'atlas_vs_raw_branch1_summary.csv'));
save(fullfile(outputFolder, 'atlas_vs_raw_branch1_workspace.mat'), ...
    'pointRows', 'summaryRows', 'caseResults', 'options', 'rawCurveFile', 'launchFolder', '-v7.3');

fprintf('\nComparison summary\n');
disp(summaryRows);
fprintf('\nData files written to:\n%s\n', outputFolder);

assignin('base', 'AcoustoelasticIOPHGOAtlasVsRawBranch1Points', pointRows);
assignin('base', 'AcoustoelasticIOPHGOAtlasVsRawBranch1Summary', summaryRows);
assignin('base', 'AcoustoelasticIOPHGOAtlasVsRawBranch1OutputFolder', outputFolder);

function rawCurveFile = resolveOrBuildRawCurveFile(launchFolder)
try
    rawCurveFile = aeResolveResultFile(launchFolder, ...
        'raw_branch1', 'raw_branch1_curve.csv', ...
        'acoustoelastic_iop_hgo_raw_branch1_candidate', 'raw_branch1_curve.csv');
catch ME
    fprintf('raw_branch1_curve.csv not found. Regenerating from modal_atlas outputs.\n');
    fprintf('Original lookup error: %s\n', ME.message);
    rawBranch = aeExtractRawBranch1Candidate(launchFolder, ...
        'RunTrackerComparison', false, ...
        'MakePlots', false, ...
        'WriteOutputs', true);
    rawCurveFile = rawBranch.curveFile;
    if ~exist(rawCurveFile, 'file')
        error('Failed to regenerate raw_branch1_curve.csv. Run diagnose_modal_atlas first.');
    end
end
end

function params = defaultExampleParams()
params = struct();
params.R = 7.8e-3;
params.thickness = 550e-6;
params.mu = 50e3;
params.k1 = 25e3;
params.k2 = 100;
params.rho = 1060;
params.rhoF = 1000;
params.fluidBulkModulus = 2.2e9;
params.frequency = [];
end

function solverOptions = defaultSolverOptions()
solverOptions = defaultAcoustoelasticIOPHGOOptions();
solverOptions.M54_variant = "corrected";
solverOptions.normalizeRows = false;
solverOptions.usePhysicalCpWindow = false;
solverOptions.atlasNumYPoints = 1000;
solverOptions.atlasTopNMinima = 18;
end

function options = defaultComparisonOptions()
options = struct();
options.RelativeMismatchThreshold = 0.05;
options.ConsecutiveMismatchPoints = 3;
options.MinimumRawCoverageFraction = 0.80;
options.MaximumRawMedianRank = 8;
options.AlignmentMedianThreshold = 0.05;
options.AlignmentMaxThreshold = 0.10;
end

function comparison = compareCase(iop, rawCase, atlasResult, identityResult, options)
f = atlasResult.frequency(:);
rawCp = interp1(rawCase.Frequency_Hz, rawCase.Cp_mps, f, 'linear', nan);
rawValid = isfinite(rawCp);

atlasCp = atlasResult.Cp(:);
atlasValid = logical(atlasResult.validCp(:)) & isfinite(atlasCp);

[identityCp, identityValid] = identityCandidateOnFrequencyGrid(identityResult, f);

[atlasErr, atlasOverlap, atlasMismatch] = relativeError(rawCp, rawValid, atlasCp, atlasValid, options.RelativeMismatchThreshold);
[identityErr, identityOverlap, identityMismatch] = relativeError(rawCp, rawValid, identityCp, identityValid, options.RelativeMismatchThreshold);

firstAtlasMismatch = firstConsecutiveMismatch(f, atlasMismatch, options.ConsecutiveMismatchPoints);
firstIdentityMismatch = firstConsecutiveMismatch(f, identityMismatch, options.ConsecutiveMismatchPoints);

points = table();
points.IOP_mmHg = repmat(iop, numel(f), 1);
points.Frequency_Hz = f;
points.Frequency_kHz = f ./ 1e3;
points.RawCp_mps = rawCp(:);
points.RawValid = rawValid(:);
points.AtlasCp_mps = atlasCp(:);
points.AtlasValid = atlasValid(:);
points.AtlasRawRelError = atlasErr(:);
points.AtlasRawMismatch = atlasMismatch(:);
points.IdentityCp_mps = identityCp(:);
points.IdentityValid = identityValid(:);
points.IdentityRawRelError = identityErr(:);
points.IdentityRawMismatch = identityMismatch(:);

summary = table();
summary.IOP_mmHg = iop;
summary.NumFrequencies = numel(f);
summary.RawValidFraction = nnz(rawValid) / max(numel(rawValid), 1);
summary.AtlasOverlapFraction = atlasOverlap;
summary.IdentityOverlapFraction = identityOverlap;
summary.MedianAtlasRawRelError = median(atlasErr(isfinite(atlasErr)), 'omitnan');
summary.MaxAtlasRawRelError = max(atlasErr(isfinite(atlasErr)), [], 'omitnan');
summary.MedianIdentityRawRelError = median(identityErr(isfinite(identityErr)), 'omitnan');
summary.MaxIdentityRawRelError = max(identityErr(isfinite(identityErr)), [], 'omitnan');
summary.FirstAtlasMismatch_Hz = firstAtlasMismatch;
summary.FirstIdentityMismatch_Hz = firstIdentityMismatch;
summary.Classification = classifyAlignment(summary, options);

comparison = struct('points', points, 'summary', summary);
end

function [cp, valid] = identityCandidateOnFrequencyGrid(identityResult, f)
f = f(:);
cp = nan(size(f));
valid = false(size(f));

if ~isstruct(identityResult) || ~isfield(identityResult, 'identityA0') || ~isstruct(identityResult.identityA0)
    return;
end

identity = identityResult.identityA0;
if ~isfield(identity, 'CpCandidate') || isempty(identity.CpCandidate)
    return;
end

candidateCp = identity.CpCandidate(:);
if isfield(identity, 'validCandidate') && ~isempty(identity.validCandidate)
    candidateValid = logical(identity.validCandidate(:));
else
    candidateValid = isfinite(candidateCp);
end

candidateFrequency = [];
if isfield(identity, 'frequency') && ~isempty(identity.frequency)
    candidateFrequency = identity.frequency(:);
elseif isfield(identityResult, 'frequency') && ~isempty(identityResult.frequency)
    candidateFrequency = identityResult.frequency(:);
end

if numel(candidateCp) == numel(f) && (isempty(candidateFrequency) || numel(candidateFrequency) ~= numel(candidateCp) || sameFrequencyGrid(candidateFrequency, f))
    cp = candidateCp(:);
    valid = candidateValid(:) & isfinite(cp);
    return;
end

if numel(candidateFrequency) ~= numel(candidateCp)
    warning('compare_atlasA0_vs_raw_branch1:IdentityGridMismatch', ...
        'identityA0Diagnostic candidate length does not match either the output grid or its own frequency grid. Marking identity candidate invalid for this case.');
    return;
end

[candidateFrequency, order] = sort(candidateFrequency(:));
candidateCp = candidateCp(order);
candidateValid = candidateValid(order) & isfinite(candidateCp);

[candidateFrequency, uniqueIdx] = unique(candidateFrequency, 'stable');
candidateCp = candidateCp(uniqueIdx);
candidateValid = candidateValid(uniqueIdx);

candidateCp(~candidateValid) = nan;
cp = interp1(candidateFrequency, candidateCp, f, 'linear', nan);
valid = isfinite(cp);
end

function tf = sameFrequencyGrid(a, b)
a = a(:);
b = b(:);
if numel(a) ~= numel(b)
    tf = false;
    return;
end
tol = 10 * eps(max(1, max(abs([a; b]))));
tf = max(abs(a - b)) <= tol;
end

function [err, overlapFraction, mismatch] = relativeError(referenceCp, referenceValid, cp, valid, threshold)
mask = referenceValid(:) & valid(:) & isfinite(referenceCp(:)) & isfinite(cp(:));
err = nan(size(referenceCp(:)));
err(mask) = abs(cp(mask) - referenceCp(mask)) ./ max(abs(referenceCp(mask)), eps);
overlapFraction = nnz(mask) / max(nnz(referenceValid), 1);
mismatch = false(size(err));
mismatch(mask) = err(mask) > threshold;
end

function firstF = firstConsecutiveMismatch(f, mismatch, nConsecutive)
firstF = nan;
if nConsecutive <= 1
    idx = find(mismatch, 1, 'first');
else
    idx = [];
    for k = 1:numel(mismatch)-nConsecutive+1
        if all(mismatch(k:k+nConsecutive-1))
            idx = k;
            break;
        end
    end
end
if ~isempty(idx)
    firstF = f(idx);
end
end

function classification = classifyAlignment(summary, options)
if summary.RawValidFraction < options.MinimumRawCoverageFraction
    classification = "raw_branch_insufficient_coverage";
elseif summary.AtlasOverlapFraction < 0.5
    classification = "atlas_low_overlap";
elseif summary.MedianAtlasRawRelError <= options.AlignmentMedianThreshold && summary.MaxAtlasRawRelError <= options.AlignmentMaxThreshold
    classification = "atlas_aligned_with_raw_branch1";
elseif summary.MedianIdentityRawRelError < summary.MedianAtlasRawRelError
    classification = "identityA0_closer_to_raw_branch1";
else
    classification = "atlas_deviates_from_raw_branch1";
end
end

function plotCaseComparison(points, iop, plotFolder)
figure('Color', 'w');
hold on;
plot(points.Frequency_kHz, points.RawCp_mps, 'k-', 'LineWidth', 2.2, 'DisplayName', 'raw branch1');
plot(points.Frequency_kHz(points.AtlasValid), points.AtlasCp_mps(points.AtlasValid), 'b--', 'LineWidth', 1.8, 'DisplayName', 'official atlasA0');
plot(points.Frequency_kHz(points.IdentityValid), points.IdentityCp_mps(points.IdentityValid), 'r-.', 'LineWidth', 1.5, 'DisplayName', 'identityA0 diagnostic');
hold off;
grid on;
xlabel('frequency [kHz]');
ylabel('Cp [m/s]');
title(sprintf('atlasA0 vs raw branch1, IOP %.1f mmHg', iop));
legend('Location', 'best');
saveas(gcf, fullfile(plotFolder, sprintf('atlas_vs_raw_branch1_IOP_%g.fig', iop)));
saveas(gcf, fullfile(plotFolder, sprintf('atlas_vs_raw_branch1_IOP_%g.png', iop)));
end

function plotSummary(summaryRows, plotFolder)
figure('Color', 'w');
plot(summaryRows.IOP_mmHg, summaryRows.MedianAtlasRawRelError, 'o-', 'LineWidth', 1.6, 'DisplayName', 'atlasA0');
hold on;
plot(summaryRows.IOP_mmHg, summaryRows.MedianIdentityRawRelError, 's--', 'LineWidth', 1.6, 'DisplayName', 'identityA0 diagnostic');
hold off;
grid on;
xlabel('IOP [mmHg]');
ylabel('median relative error vs raw branch1');
title('Branch comparison summary');
legend('Location', 'best');
saveas(gcf, fullfile(plotFolder, 'atlas_vs_raw_branch1_summary.fig'));
saveas(gcf, fullfile(plotFolder, 'atlas_vs_raw_branch1_summary.png'));
end
