clear; clc; close all;
launchFolder = pwd;
startup

%COMPARE_ATLASA0_VS_RAW_BRANCH1 Compare official atlasA0, identityA0, and raw branch-1.
%
% Diagnostic only. This script does not promote raw_branch1 and does not modify
% result.Cp or result.validCp. It compares the official atlasA0 output,
% identityA0Diagnostic candidate output, and the global modal-atlas raw_branch1
% curve generated by track_raw_branch1.
%
% Inputs:
%   Results/ae_iop_hgo/raw_branch1/raw_branch1_curve.csv
%
% Outputs:
%   Results/ae_iop_hgo/atlas_vs_raw_branch1

outputFolder = aeOutputFolder(launchFolder, 'atlas_vs_raw_branch1');
plotFolder = fullfile(outputFolder, 'plots');
if ~exist(plotFolder, 'dir')
    mkdir(plotFolder);
end

rawCurveFile = aeResolveResultFile(launchFolder, ...
    'raw_branch1', 'raw_branch1_curve.csv', ...
    'acoustoelastic_iop_hgo_raw_branch1_candidate', 'raw_branch1_curve.csv');
rawCurve = readtable(rawCurveFile);

requiredColumns = {'IOP_mmHg','Frequency_Hz','Cp_mps'};
for i = 1:numel(requiredColumns)
    if ~ismember(requiredColumns{i}, rawCurve.Properties.VariableNames)
        error('raw_branch1_curve.csv is missing required column: %s', requiredColumns{i});
    end
end

IOP_mmHg = unique(rawCurve.IOP_mmHg, 'stable');
options = defaultComparisonOptions();

pointRows = table();
summaryRows = table();
caseResults = struct();

for i = 1:numel(IOP_mmHg)
    iop = IOP_mmHg(i);
    rawCase = rawCurve(rawCurve.IOP_mmHg == iop, :);
    rawCase = sortrows(rawCase, 'Frequency_Hz');

    params = defaultExampleParams();
    params.IOP = iop * 133.322;
    params.frequency = rawCase.Frequency_Hz(:).';

    atlasOptions = defaultSolverOptions();
    atlasOptions.atlasBranchPolicy = "atlasA0";
    atlasResult = solveAcoustoelasticIOPHGOBranch(params, atlasOptions);

    identityOptions = atlasOptions;
    identityOptions.atlasBranchPolicy = "identityA0Diagnostic";
    identityResult = solveAcoustoelasticIOPHGOBranch(params, identityOptions);

    comparison = compareCase(iop, rawCase, atlasResult, identityResult, options);
    pointRows = [pointRows; comparison.points]; %#ok<AGROW>
    summaryRows = [summaryRows; comparison.summary]; %#ok<AGROW>

    caseResults(i).IOP_mmHg = iop; %#ok<SAGROW>
    caseResults(i).rawCase = rawCase;
    caseResults(i).atlasResult = atlasResult;
    caseResults(i).identityResult = identityResult;
    caseResults(i).comparison = comparison;

    plotCaseComparison(comparison.points, iop, plotFolder);

    fprintf('IOP %.1f mmHg: %s | atlas median err %.4g | identity median err %.4g\n', ...
        iop, comparison.summary.Classification, ...
        comparison.summary.MedianAtlasRawRelError, ...
        comparison.summary.MedianIdentityRawRelError);
end

plotSummary(summaryRows, plotFolder);

writetable(pointRows, fullfile(outputFolder, 'atlas_vs_raw_branch1_points.csv'));
writetable(summaryRows, fullfile(outputFolder, 'atlas_vs_raw_branch1_summary.csv'));
save(fullfile(outputFolder, 'atlas_vs_raw_branch1_workspace.mat'), ...
    'pointRows', 'summaryRows', 'caseResults', 'options', 'rawCurveFile', 'launchFolder', '-v7.3');

fprintf('\nComparison summary\n');
disp(summaryRows);
fprintf('\nData files written to:\n%s\n', outputFolder);

assignin('base', 'AcoustoelasticIOPHGOAtlasVsRawBranch1Points', pointRows);
assignin('base', 'AcoustoelasticIOPHGOAtlasVsRawBranch1Summary', summaryRows);
assignin('base', 'AcoustoelasticIOPHGOAtlasVsRawBranch1OutputFolder', outputFolder);

function params = defaultExampleParams()
params = struct();
params.R = 7.8e-3;
params.thickness = 550e-6;
params.mu = 50e3;
params.k1 = 25e3;
params.k2 = 100;
params.rho = 1060;
params.rhoF = 1000;
params.fluidBulkModulus = 2.2e9;
params.frequency = [];
end

function solverOptions = defaultSolverOptions()
solverOptions = defaultAcoustoelasticIOPHGOOptions();
solverOptions.M54_variant = "corrected";
solverOptions.normalizeRows = false;
solverOptions.usePhysicalCpWindow = false;
solverOptions.atlasNumYPoints = 1000;
solverOptions.atlasTopNMinima = 18;
end

function options = defaultComparisonOptions()
options = struct();
options.RelativeMismatchThreshold = 0.05;
options.ConsecutiveMismatchPoints = 3;
options.MinimumRawCoverageFraction = 0.80;
options.MaximumRawMedianRank = 8;
options.AlignmentMedianThreshold = 0.05;
options.AlignmentMaxThreshold = 0.10;
end

function comparison = compareCase(iop, rawCase, atlasResult, identityResult, options)
f = atlasResult.frequency(:);
rawCp = interp1(rawCase.Frequency_Hz, rawCase.Cp_mps, f, 'linear', nan);
rawValid = isfinite(rawCp);

atlasCp = atlasResult.Cp(:);
atlasValid = logical(atlasResult.validCp(:)) & isfinite(atlasCp);

identityCp = nan(size(f));
identityValid = false(size(f));
if isfield(identityResult, 'identityA0')
    identityCp = identityResult.identityA0.CpCandidate(:);
    identityValid = logical(identityResult.identityA0.validCandidate(:)) & isfinite(identityCp);
end

[atlasErr, atlasOverlap, atlasMismatch] = relativeError(rawCp, rawValid, atlasCp, atlasValid, options.RelativeMismatchThreshold);
[identityErr, identityOverlap, identityMismatch] = relativeError(rawCp, rawValid, identityCp, identityValid, options.RelativeMismatchThreshold);

firstAtlasMismatch = firstConsecutiveMismatch(f, atlasMismatch, options.ConsecutiveMismatchPoints);
firstIdentityMismatch = firstConsecutiveMismatch(f, identityMismatch, options.ConsecutiveMismatchPoints);

points = table();
points.IOP_mmHg = repmat(iop, numel(f), 1);
points.Frequency_Hz = f;
points.Frequency_kHz = f ./ 1e3;
points.RawCp_mps = rawCp(:);
points.RawValid = rawValid(:);
points.AtlasCp_mps = atlasCp(:);
points.AtlasValid = atlasValid(:);
points.AtlasRawRelError = atlasErr(:);
points.AtlasRawMismatch = atlasMismatch(:);
points.IdentityCp_mps = identityCp(:);
points.IdentityValid = identityValid(:);
points.IdentityRawRelError = identityErr(:);
points.IdentityRawMismatch = identityMismatch(:);

summary = table();
summary.IOP_mmHg = iop;
summary.FrequencyPoints = numel(f);
summary.RawValidPoints = nnz(rawValid);
summary.RawCoverageFraction = nnz(rawValid) / max(numel(f), 1);
summary.RawMedianRank = medianIfPresent(rawCase, 'MinRank');
summary.AtlasValidPoints = nnz(atlasValid);
summary.AtlasValidFraction = nnz(atlasValid) / max(numel(f), 1);
summary.IdentityValidPoints = nnz(identityValid);
summary.IdentityValidFraction = nnz(identityValid) / max(numel(f), 1);
summary.ValidOverlapFraction = nnz(rawValid & (atlasValid | identityValid)) / max(nnz(rawValid), 1);
summary.AtlasRawValidOverlapFraction = nnz(atlasOverlap) / max(nnz(rawValid), 1);
summary.IdentityRawValidOverlapFraction = nnz(identityOverlap) / max(nnz(rawValid), 1);
summary.FirstAtlasRawMismatchFrequency_Hz = firstAtlasMismatch;
summary.FirstAtlasRawMismatchFrequency_kHz = firstAtlasMismatch / 1e3;
summary.FirstIdentityRawMismatchFrequency_Hz = firstIdentityMismatch;
summary.FirstIdentityRawMismatchFrequency_kHz = firstIdentityMismatch / 1e3;
summary.MedianAtlasRawRelError = median(atlasErr(atlasOverlap), 'omitnan');
summary.MedianIdentityRawRelError = median(identityErr(identityOverlap), 'omitnan');
summary.MaxAtlasRawRelError = maxWithNaN(atlasErr(atlasOverlap));
summary.MaxIdentityRawRelError = maxWithNaN(identityErr(identityOverlap));
summary.IdentityAddedPoints = nnz(identityValid & ~atlasValid);
summary.Classification = classifyComparison(summary, firstAtlasMismatch, firstIdentityMismatch, options);

comparison = struct();
comparison.points = points;
comparison.summary = summary;
comparison.atlasResult = atlasResult;
comparison.identityResult = identityResult;
end

function [err, overlap, mismatch] = relativeError(rawCp, rawValid, candidateCp, candidateValid, threshold)
overlap = rawValid(:) & candidateValid(:) & isfinite(rawCp(:)) & isfinite(candidateCp(:));
err = nan(size(rawCp(:)));
err(overlap) = abs(candidateCp(overlap) - rawCp(overlap)) ./ max(abs(rawCp(overlap)), eps);
mismatch = false(size(rawCp(:)));
mismatch(overlap) = err(overlap) > threshold;
end

function fFirst = firstConsecutiveMismatch(f, mismatch, consecutivePoints)
fFirst = nan;
if ~any(mismatch)
    return;
end
runCount = 0;
for k = 1:numel(mismatch)
    if mismatch(k)
        runCount = runCount + 1;
        if runCount >= consecutivePoints
            fFirst = f(k - consecutivePoints + 1);
            return;
        end
    else
        runCount = 0;
    end
end
end

function classification = classifyComparison(summary, firstAtlasMismatch, firstIdentityMismatch, options)
rawUncertain = summary.RawCoverageFraction < options.MinimumRawCoverageFraction || ...
    (isfinite(summary.RawMedianRank) && summary.RawMedianRank > options.MaximumRawMedianRank);
if rawUncertain
    classification = "raw_branch_uncertain";
    return;
end

atlasAligned = isnan(firstAtlasMismatch) && ...
    summary.MedianAtlasRawRelError <= options.AlignmentMedianThreshold && ...
    summary.MaxAtlasRawRelError <= options.AlignmentMaxThreshold;
identityAligned = isnan(firstIdentityMismatch) && ...
    summary.MedianIdentityRawRelError <= options.AlignmentMedianThreshold && ...
    summary.MaxIdentityRawRelError <= options.AlignmentMaxThreshold;

atlasTruncated = summary.AtlasValidFraction < 0.98;
identityExtends = summary.IdentityAddedPoints > 0 && summary.IdentityRawValidOverlapFraction > summary.AtlasRawValidOverlapFraction;

if atlasAligned && atlasTruncated
    classification = "atlas_truncated_but_aligned";
elseif atlasAligned
    classification = "aligned_with_raw_branch";
elseif identityExtends && identityAligned
    classification = "identity_extension_aligned";
elseif identityExtends && ~identityAligned
    classification = "identity_extension_modal_mismatch";
elseif ~isnan(firstAtlasMismatch)
    classification = "atlas_branch_switch_suspected";
else
    classification = "raw_branch_uncertain";
end
end

function value = medianIfPresent(T, columnName)
if ismember(columnName, T.Properties.VariableNames)
    value = median(T.(columnName), 'omitnan');
else
    value = nan;
end
end

function value = maxWithNaN(x)
if isempty(x) || ~any(isfinite(x))
    value = nan;
else
    value = max(x, [], 'omitnan');
end
end

function plotCaseComparison(points, iop, plotFolder)
figure('Color', 'w', 'Name', sprintf('atlasA0 vs raw branch1 IOP %.0f', iop));
hold on; grid on;
plot(points.Frequency_kHz, points.RawCp_mps, '-', 'LineWidth', 2.5, 'DisplayName', 'raw_branch1');
plot(points.Frequency_kHz, points.AtlasCp_mps, '--', 'LineWidth', 1.8, 'DisplayName', 'atlasA0 official');
plot(points.Frequency_kHz, points.IdentityCp_mps, ':', 'LineWidth', 1.8, 'DisplayName', 'identityA0 diagnostic');
xlabel('frequency [kHz]');
ylabel('Cp [m/s]');
title(sprintf('atlasA0 and identityA0 versus raw_branch1, IOP %.0f mmHg', iop), 'Interpreter', 'none');
legend('Location', 'best', 'Interpreter', 'none');
hold off;
saveas(gcf, fullfile(plotFolder, sprintf('atlas_vs_raw_branch1_iop_%g.png', iop)));
saveas(gcf, fullfile(plotFolder, sprintf('atlas_vs_raw_branch1_iop_%g.fig', iop)));
end

function plotSummary(summaryRows, plotFolder)
figure('Color', 'w', 'Name', 'atlasA0 vs raw branch1 median errors');
hold on; grid on;
plot(summaryRows.IOP_mmHg, summaryRows.MedianAtlasRawRelError, '-o', 'LineWidth', 1.8, 'DisplayName', 'atlasA0');
plot(summaryRows.IOP_mmHg, summaryRows.MedianIdentityRawRelError, '-s', 'LineWidth', 1.8, 'DisplayName', 'identityA0');
xlabel('IOP [mmHg]');
ylabel('median relative error vs raw_branch1', 'Interpreter', 'none');
title('Median relative error against raw_branch1', 'Interpreter', 'none');
legend('Location', 'best', 'Interpreter', 'none');
hold off;
saveas(gcf, fullfile(plotFolder, 'atlas_vs_raw_branch1_median_error.png'));
saveas(gcf, fullfile(plotFolder, 'atlas_vs_raw_branch1_median_error.fig'));
end
