function catalog = repository_test_catalog(projectRoot)
%REPOSITORY_TEST_CATALOG Static ownership and deterministic order of maintained tests.
entries = [ ...
    "repository_hygiene" "tests/repository/test_repository_structure_contract.m"
    "repository_hygiene" "tests/repository/test_repository_documentation_contract.m"
    "repository_hygiene" "tests/repository/test_repository_naming_contract.m"
    "repository_hygiene" "tests/repository/test_repository_tracked_artifacts_contract.m"
    "repository_hygiene" "tests/repository/test_repository_dependency_boundaries_contract.m"
    "repository_hygiene" "tests/repository/test_maintained_test_structure_contract.m"
    "repository_hygiene" "tests/repository/test_startup_path_policy.m"
    "repository_hygiene" "tests/repository/test_repository_root_utilities.m"
    "quick_contracts" "tests/repository/test_model_output_folder_helpers.m"
    "quick_contracts" "tests/fitting/test_fitting_helpers_smoke.m"
    "quick_contracts" "tests/fitting/test_fit_objective_coverage_contract.m"
    "quick_contracts" "tests/fitting/test_shared_fit_optimizer_contract.m"
    "quick_contracts" "tests/sweeps/test_parametric_sweep_workflow.m"
    "quick_contracts" "tests/models/rayleigh_lamb/test_rl_result_contract.m"
    "quick_contracts" "tests/app/execution_profiles/test_gui_execution_profile_normalization.m"
    "quick_contracts" "tests/app/execution_profiles/test_model_execution_profile_resolvers.m"
    "quick_contracts" "tests/app/execution_profiles/test_execution_profile_normalization_contract.m"
    "quick_contracts" "tests/app/execution_profiles/test_execution_profile_surface_metadata.m"
    "quick_contracts" "tests/app/execution_profiles/test_execution_profile_state_transition_contract.m"
    "quick_contracts" "tests/app/fitting/test_fit_tool_interaction_helpers.m"
    "quick_contracts" "tests/app/solver/test_main_gui_export_contract.m"
    "quick_contracts" "tests/models/mrlfe/test_mrlfe_public_contract_defaults.m"
    "quick_contracts" "tests/models/mrlfe/test_mrlfe_public_contract_validation.m"
    "quick_contracts" "tests/app/fitting/test_gui_read_experimental_fit_file.m"
    "quick_contracts" "tests/app/fitting/test_gui_prepare_experimental_fit_data.m"
    "quick_smoke" "tests/app/solver/test_main_gui_curve_gaps.m"
    "quick_smoke" "tests/app/fitting/test_fit_plot_legend.m"
    "quick_smoke" "tests/app/utilities/test_gui_struct_helpers_contract.m"
    "quick_smoke" "tests/app/fitting/test_fit_parameter_state_contract.m"
    "quick_smoke" "tests/app/fitting/test_fit_parameter_execution_contract.m"
    "quick_smoke" "tests/app/solver/test_gui_normalized_adapters_smoke.m"
    "quick_smoke" "tests/app/solver/test_ae_gui_main_adapter_smoke.m"
    "quick_smoke" "tests/app/solver/test_main_gui_diagnostics_text.m"
    "quick_smoke" "tests/app/fitting/test_gui_fit_model_configuration_contract.m"
    "quick_smoke" "tests/app/fitting/test_fit_tool_model_configuration_contract.m"
    "quick_smoke" "tests/models/acoustoelastic_iop_hgo/test_ae_branch_policy_validation.m"
    "quick_smoke" "tests/models/acoustoelastic_iop_hgo/test_ae_configuration_characterization.m"
    "quick_smoke" "tests/models/acoustoelastic_iop_hgo/test_ae_configuration_ownership.m"
    "quick_smoke" "tests/models/acoustoelastic_iop_hgo/test_ae_production_architecture_contract.m"
    "quick_smoke" "tests/models/acoustoelastic_iop_hgo/test_ae_result_ownership.m"
    "quick_smoke" "tests/studies/solver_diagnostics/test_ae_analyze_truncation_recovery.m"
    "quick_smoke" "tests/studies/solver_diagnostics/test_ae_analyze_sweep_reliability.m"
    "quick_smoke" "tests/studies/solver_diagnostics/test_ae_analyze_branch_persistence_candidates.m"
    "quick_smoke" "tests/models/acoustoelastic_iop_hgo/test_ae_constitutive_identity.m"
    "quick_smoke" "tests/studies/sensitivity/test_ae_sensitivity_study_contract.m"
    "quick_smoke" "tests/studies/sensitivity/test_sensitivity_plot_renderer_contract.m"
    "quick_smoke" "tests/models/acoustoelastic_iop_hgo/test_ae_identityA0_diagnostic_policy.m"
    "quick_smoke" "tests/studies/test_ae_study_layout_contract.m"
    "quick_smoke" "tests/models/mrlfe/test_mrlfe_smoke.m"
    "quick_smoke" "tests/models/mrlfe/test_mrlfe_etaS_zero_limit.m"
    "quick_smoke" "tests/fitting/mrlfe/test_mrlfe_residual_objective_contract.m"
    "quick_smoke" "tests/studies/solver_diagnostics/test_mrlfe_tracking_quality_summary.m"
    "quick_smoke" "tests/models/mrlfe/test_mrlfe_maintained_surface_contract.m"
    "numerical_regression" "tests/fitting/rayleigh_lamb/test_rl_fit_evaluator_branch_consistency.m"
    "numerical_regression" "tests/fitting/rayleigh_lamb/test_rl_near_incompressible_contract.m"
    "numerical_regression" "tests/fitting/rayleigh_lamb/test_rl_fit_synthetic_A0.m"
    "numerical_regression" "tests/fitting/mrlfe/test_mrlfe_fit_synthetic_A0Like.m"
    "numerical_regression" "tests/models/mrlfe/test_mrlfe_numerical_preset_grids.m"
    "numerical_regression" "tests/models/mrlfe/test_mrlfe_production_core_contract.m"
    "numerical_regression" "tests/models/mrlfe/test_mrlfe_seed_refinement_stability.m"
    "numerical_regression" "tests/models/mrlfe/test_mrlfe_solve_frequency_override.m"
    "numerical_regression" "tests/models/mrlfe/test_mrlfe_robust_start_contract.m"
    "numerical_regression" "tests/models/mrlfe/test_mrlfe_termination_policy.m"
    "numerical_regression" "tests/models/mrlfe/test_mrlfe_public_contract_result_schema.m"
    "numerical_regression" "tests/models/acoustoelastic_iop_hgo/test_ae_result_schema_characterization.m"
    "numerical_regression" "tests/models/acoustoelastic_iop_hgo/test_ae_tracking_policy_characterization.m"
    "numerical_regression" "tests/models/acoustoelastic_iop_hgo/test_ae_tracking_policy_ownership.m"
    "numerical_regression" "tests/models/acoustoelastic_iop_hgo/test_ae_fallback_invalidation.m"
    "numerical_regression" "tests/models/acoustoelastic_iop_hgo/test_ae_internal_tracking_grid.m"
    "numerical_regression" "tests/models/acoustoelastic_iop_hgo/test_ae_atlasA0_smoke.m"
    "numerical_regression" "tests/fitting/acoustoelastic_iop_hgo/test_ae_fit_synthetic_atlasA0.m"
    "numerical_regression" "tests/models/test_lightweight_numerical_regression.m"
    "extended_integration" "tests/app/fitting/test_execution_profile_contract.m"
    "extended_integration" "tests/app/execution_profiles/test_execution_profile_surface_integration.m"
    "extended_integration" "tests/app/execution_profiles/test_execution_profile_fit_curve_metadata.m"
    "extended_integration" "tests/app/execution_profiles/test_execution_profile_validation_matrix.m"
    "extended_integration" "tests/app/fitting/test_fit_tool_requested_curve_models.m"
    "extended_integration" "tests/app/fitting/test_fit_display_curve_no_solver_contract.m"
    "extended_integration" "tests/fitting/rayleigh_lamb/test_fit_validation_rayleigh_lamb.m"
    "extended_integration" "tests/fitting/mrlfe/test_fit_validation_mrlfe.m"
    "extended_integration" "tests/fitting/mrlfe/test_fit_validation_mrlfe_hidden_params.m"
    "extended_integration" "tests/fitting/acoustoelastic_iop_hgo/test_fit_validation_ae_iop_hgo.m"
    "extended_integration" "tests/fitting/acoustoelastic_iop_hgo/test_fit_validation_ae_iop_hgo_hidden_params.m"
    "extended_integration" "tests/fitting/rayleigh_lamb/test_fit_physical_qc_flat_rl.m"
    "extended_integration" "tests/fitting/rayleigh_lamb/test_fit_physical_qc_synthetic_pass.m"
    "extended_integration" "tests/fitting/rayleigh_lamb/test_rl_fit_rejects_prediction_fallback.m"
    "extended_integration" "tests/fitting/mrlfe/test_mrlfe_etaS_fit_forward_cache.m"
    "extended_integration" "tests/fitting/mrlfe/test_mrlfe_fit_fast_options_quality.m"
    "extended_integration" "tests/app/fitting/test_gui_mrlfe_fixed_etaS_fit_contract.m"
    "extended_integration" "tests/app/fitting/test_gui_mrlfe_fit_route_policy_contract.m"
    "extended_integration" "tests/app/fitting/test_gui_mrlfe_fit_full_curve_fast_contract.m"
    "extended_integration" "tests/fitting/mrlfe/test_mrlfe_fit_frequency_grid_contract.m"
    "extended_integration" "tests/app/fitting/test_mrlfe_fit_uses_public_solver.m"
    "extended_integration" "tests/app/fitting/test_mrlfe_fit_public_solver_characterization.m"
    "extended_integration" "tests/app/fitting/test_mrlfe_fit_public_solver_parameter_regression.m"
    "extended_integration" "tests/app/solver/test_mrlfe_main_gui_uses_public_solver.m"
    "extended_integration" "tests/app/solver/test_mrlfe_main_gui_characterization.m"
    "extended_integration" "tests/app/solver/test_mrlfe_main_gui_consumer_equivalence.m"
    "extended_integration" "tests/app/solver/test_mrlfe_main_gui_result_contract.m"
    "extended_integration" "tests/models/mrlfe/test_mrlfe_solve_request_builder.m"
    "extended_integration" "tests/models/mrlfe/test_mrlfe_public_contract_characterization.m"
    "extended_integration" "tests/models/mrlfe/test_mrlfe_canonical_route_contract.m"
    "extended_integration" "tests/models/mrlfe/test_mrlfe_configuration_ownership_contract.m"
    "extended_integration" "tests/models/mrlfe/test_mrlfe_maintained_route_characterization.m"
    "extended_integration" "tests/models/mrlfe/test_mrlfe_production_dependency_contract.m"
    "extended_integration" "tests/models/mrlfe/test_mrlfe_neutral_seed_contract.m"
    "extended_integration" "tests/models/mrlfe/test_mrlfe_neutral_tracker_termination_contract.m"
    "extended_integration" "tests/models/mrlfe/test_mrlfe_production_core_presets.m"
    "extended_integration" "tests/models/mrlfe/test_mrlfe_production_core_characterization.m"
    "performance_benchmarks" "tests/tooling/test_runtime_measurement_output_schema.m"
    "performance_benchmarks" "tests/app/execution_profiles/test_execution_profile_diagnostics_format.m"
    "performance_benchmarks" "tests/app/fitting/test_mrlfe_fit_grid_policy_performance.m"
    "performance_benchmarks" "tests/models/mrlfe/test_mrlfe_production_core_performance.m"
];
catalog = table(entries(:,1), entries(:,2), ...
    'VariableNames', {'Group', 'Path'});
assert(numel(unique(catalog.Path)) == height(catalog), ...
    'lamb:tests:DuplicateOwnership', 'A test has duplicate catalog ownership.');
files = dir(fullfile(projectRoot, 'tests', '**', 'test_*.m'));
actual = strings(numel(files), 1);
for i = 1:numel(files)
    actual(i) = replace(string(fullfile(files(i).folder, files(i).name)), ...
        string(projectRoot) + filesep, "");
end
actual = replace(actual, "\", "/");
assert(isequal(sort(actual), sort(catalog.Path)), ...
    'lamb:tests:CatalogCoverage', ...
    'Missing or uncatalogued maintained tests: %s', ...
    strjoin(setxor(actual, catalog.Path), ', '));
[~, names] = cellfun(@fileparts, cellstr(catalog.Path), 'UniformOutput', false);
assert(numel(unique(names)) == numel(names), ...
    'lamb:tests:DuplicateName', 'Maintained test names must resolve uniquely.');
end
