clear; clc;
startup

% Run GUI, sweep, fitting, and execution-profile contracts and smoke checks.
% Membership includes surface integration and is not a contracts-only runner.

fprintf('\nRunning GUI smoke tests...\n');
fprintf('--------------------------\n');

fprintf('\nChecking GUI adapter path functions...\n');
assertFunctionsOnPath({ ...
    'LambFundamental_GUI', ...
    'FitTool_GUI', ...
    'createFittingTab', ...
    'guiGetStructField', ...
    'guiMergeStructs', ...
    'guiBuildFitParameterState', ...
    'guiFitParameterStateToTable', ...
    'guiApplyFitParameterTable', ...
    'guiBuildFitParameterRequest', ...
    'guiValidateFitParameterState', ...
    'guiResolveFitModelSetup', ...
    'guiRunRayleighLambModel', ...
    'guiRunMRLFEModel', ...
    'guiRunAcoustoelasticIOPHGOModel', ...
    'guiBuildAcoustoelasticIOPHGOOptions', ...
    'guiBuildAcoustoelasticIOPHGORequest', ...
    'guiNormalizeRawResult', ...
    'guiNormalizedBranchToTable', ...
    'guiNormalizedBranchesToTables', ...
    'guiGetNormalizedBranchPlotData', ...
    'guiBuildMainResultExport', ...
    'guiSaveMainResultExport', ...
    'guiBuildSweepRequest', ...
    'guiExecutionProfileValues', ...
    'guiNormalizeExecutionProfile', ...
    'guiNormalizeControlExecutionProfile', ...
    'rlResolveExecutionProfile', ...
    'mrlfeResolveExecutionProfile', ...
    'aeResolveExecutionProfile', ...
    'guiRunSweep', ...
    'guiRunMRLFESweep', ...
    'guiNormalizeMRLFESweep', ...
    'guiRunAcoustoelasticIOPHGOSweep', ...
    'guiNormalizeAcoustoelasticIOPHGOSweep', ...
    'guiPlotSweepResult', ...
    'guiGetSweepRegistry', ...
    'guiGetSweepFamilyConfig', ...
    'guiGetSweepParameterConfig', ...
    'guiFormatSweepValues', ...
    'guiGetFitRegistry', ...
    'guiBuildFitRequest', ...
    'guiRunFit', ...
    'guiFitRLSolver', ...
    'guiFitMRLFESolver', ...
    'guiFitAcoustoelasticIOPHGOSolver', ...
    'guiNormalizeFitResult', ...
    'guiBuildFitParameterSummaryTable', ...
    'guiBuildFitQualitySummaryTable', ...
    'guiBuildFitParameterDisplayTable', ...
    'guiBuildFitQualityDisplayTable', ...
    'guiFitDisplayLabel', ...
    'guiAppendExperimentalFitRow', ...
    'guiDeleteExperimentalFitRows', ...
    'guiMarkExperimentalFitDataEdited', ...
    'guiValidateFitAxisLimits', ...
    'guiApplyFitAxisView', ...
    'guiEvaluateRequestedFitCurve', ...
    'guiPlotFitResult'}, ...
    'GUI adapter/helper');

fprintf('\n[GUI group 1/4] Quick GUI owner\n');
run_gui_quick_tests;

fprintf('\n[GUI group 2/4] FitTool interaction owner\n');
run_fit_tool_interaction_tests;

fprintf('\n[GUI group 3/4] Extended GUI fitting owner\n');
run_gui_extended_tests;

fprintf('\n[GUI group 4/4] GUI execution-profile owner\n');
run_gui_execution_profile_tests;

fprintf('\nGUI smoke tests passed.\n');

function assertFunctionsOnPath(functionNames, label)
for i = 1:numel(functionNames)
    functionName = functionNames{i};
    assert(~isempty(which(functionName)), ...
        'Missing %s on MATLAB path: %s.', label, functionName);
end
end
