clear; clc;
if isempty(which('mrlfeSolve'))
    startup
end

% Run core path/API contracts, cross-model numerical regression, shared fitting
% helpers, and representative Rayleigh-Lamb and mRLFE synthetic fitting checks.

fprintf('\nRunning core smoke tests...\n');
fprintf('---------------------------\n');

%% Shared material helpers
fprintf('\nChecking shared elastic material helpers...\n');
assertFunctionsOnPath({ ...
    'elasticFromMuNu', ...
    'elasticFromLame'}, ...
    'shared elastic material helper');

elastic = elasticFromMuNu(75e3, 0.4999, 1070);
assertNumericClose(elastic.E, 2 * 75e3 * (1 + 0.4999), 1e-10, ...
    'elasticFromMuNu returned an unexpected Young modulus.');
assertNumericClose(elastic.mu, 75e3, 1e-12, ...
    'elasticFromMuNu should preserve mu.');
assert(elastic.lambda > 0 && elastic.K > 0 && elastic.CL > elastic.CT, ...
    'elasticFromMuNu should return positive lambda/K and CL > CT.');

%% Startup/path policy
fprintf('\nRunning canonical core contract owner...\n');
run_core_contract_tests;

%% Shared fitting helpers
fprintf('\nChecking shared fitting helper functions...\n');
assertFunctionsOnPath({ ...
    'normalizeExperimentalDispersionData', ...
    'validateExperimentalDispersionData', ...
    'computeDispersionFitResiduals', ...
    'computeDispersionFitMetrics', ...
    'computeConstantSpeedBaseline', ...
    'assessFitPhysicalQuality', ...
    'buildParameterVector', ...
    'unpackParameterVector', ...
    'estimateLocalSensitivity', ...
    'assessFitIdentifiability'}, ...
    'shared fitting helper');

%% Rayleigh-Lamb public API path checks
fprintf('\nChecking Rayleigh-Lamb primary rl* API functions...\n');
assertFunctionsOnPath({ ...
    'rlComputeFundamentalLambModes', ...
    'rlDefaultOptions', ...
    'rlDefaultParams', ...
    'rlComputeAnalyticalApproximations'}, ...
    'Rayleigh-Lamb public API');

fprintf('\nChecking Rayleigh-Lamb maintained internals...\n');
assertFunctionsOnPath({ ...
    'setSweepPlotLimits', ...
    'rlBuildFrequencyVector', ...
    'rlComputeGeometry', ...
    'rlComputeMaterial', ...
    'rlMakeBranchSpec', ...
    'rlValidateOptions', ...
    'rlValidateParams', ...
    'rlAResidual', ...
    'rlSResidual', ...
    'rlComputeA0ThinPlateApproximation', ...
    'rlComputeS0ExtensionalApproximation', ...
    'rlSolveFundamentalBranch'}, ...
    'Rayleigh-Lamb maintained internal');

rlPublicDefaults = rlDefaultParams();
assert(~any(isfield(rlPublicDefaults, {'E', 'lambda', 'K', 'CL', 'CT'})), ...
    'RL public defaults must contain primary inputs, not derived material fields.');

fprintf('\nChecking Rayleigh-Lamb fitting helper functions...\n');
assertFunctionsOnPath({ ...
    'solveDispersionFitProblem', ...
    'rlBuildFitProblem', ...
    'rlEvaluateFitModel', ...
    'rlFitDispersionData'}, ...
    'Rayleigh-Lamb fitting helper');

fprintf('\nChecking mRLFE fitting helper functions...\n');
assertFunctionsOnPath({ ...
    'mrlfeBuildFitProblem', ...
    'mrlfeEvaluateFitModel', ...
    'mrlfeFitDispersionData'}, ...
    'mRLFE fitting helper');

fprintf('\nChecking Rayleigh-Lamb sweep helper functions...\n');
assertFunctionsOnPath({ ...
    'rlDefaultSweepParams', ...
    'rlDefaultSweepOptions', ...
    'rlMakeSweepSpec', ...
    'rlRunSweep', ...
    'resolveModelOutputFolder', ...
    'rlWriteSweepOutputs', ...
    'rlSaveExampleFigure', ...
    'rl_sweep_thickness_A0', ...
    'rl_sweep_thickness_S0'}, ...
    'Rayleigh-Lamb sweep helper');
assertFunctionsAbsent({ ...
    'sweep_thickness_A0_elastic', ...
    'sweep_thickness_S0_elastic'}, ...
    'obsolete Rayleigh-Lamb sweep entrypoint');

%% Rayleigh-Lamb minimal numerical regression fixtures
fprintf('\nChecking Rayleigh-Lamb minimal numerical regression fixtures...\n');
regressionTol = 1e-12;

regressionParams = rlDefaultParams();
regressionParams.fmin = 10;
regressionParams.fmax = 100;
regressionParams.numFrequencyPoints = 10;
regressionParams.frequencySpacing = "linspace";

regressionOptions = rlDefaultOptions();
regressionOptions.computeA0 = true;
regressionOptions.computeS0 = true;
regressionResults = rlComputeFundamentalLambModes(regressionParams, regressionOptions);
regressionRepeat = rlComputeFundamentalLambModes(regressionParams, regressionOptions);
expectedSize = [numel(rlBuildFrequencyVector(regressionParams)), 1];

assert(isfield(regressionResults, 'model') && regressionResults.model == "rayleigh_lamb", ...
    'Rayleigh-Lamb regression result identity is missing.');
assert(isfield(regressionResults, 'modes') && isfield(regressionResults.modes, 'A0'), ...
    'Rayleigh-Lamb regression results are missing A0 mode output.');
assert(isfield(regressionResults.modes, 'S0'), ...
    'Rayleigh-Lamb regression results are missing S0 mode output.');
assert(string(regressionResults.material.modelType) == "ShearPoisson", ...
    'Rayleigh-Lamb default material model must be ShearPoisson.');

regressionFrequency = regressionResults.modes.A0.frequency_Hz;
regressionA0 = regressionResults.modes.A0;
regressionS0 = regressionResults.modes.S0;

assert(isequal(size(regressionFrequency), expectedSize), ...
    'Rayleigh-Lamb regression frequency size does not match the requested grid.');
assert(isequal(size(regressionA0.frequency_Hz), expectedSize), ...
    'Rayleigh-Lamb A0 regression frequency size does not match the requested grid.');
assert(isequal(size(regressionS0.frequency_Hz), expectedSize), ...
    'Rayleigh-Lamb S0 regression frequency size does not match the requested grid.');
assert(isequal(size(regressionA0.phaseVelocity_mps), expectedSize), ...
    'Rayleigh-Lamb A0 regression Cp size does not match the requested grid.');
assert(isequal(size(regressionS0.phaseVelocity_mps), expectedSize), ...
    'Rayleigh-Lamb S0 regression Cp size does not match the requested grid.');

assert(all(isfinite(regressionFrequency(:))), ...
    'Rayleigh-Lamb regression frequencies must be finite.');
assert(all(isfinite(regressionA0.phaseVelocity_mps(:)) & regressionA0.phaseVelocity_mps(:) > 0), ...
    'Rayleigh-Lamb A0 regression Cp values must be finite and positive.');
assert(all(isfinite(regressionS0.phaseVelocity_mps(:)) & regressionS0.phaseVelocity_mps(:) > 0), ...
    'Rayleigh-Lamb S0 regression Cp values must be finite and positive.');
assert(any(abs(regressionA0.phaseVelocity_mps(:) - regressionS0.phaseVelocity_mps(:)) > regressionTol), ...
    'Rayleigh-Lamb A0 and S0 regression Cp outputs should not be identical.');

assertNumericClose(regressionFrequency, regressionRepeat.modes.A0.frequency_Hz, regressionTol, ...
    'Rayleigh-Lamb regression frequencies are not repeatable.');
assertNumericClose(regressionA0.phaseVelocity_mps, regressionRepeat.modes.A0.phaseVelocity_mps, regressionTol, ...
    'Rayleigh-Lamb A0 regression Cp values are not repeatable.');
assertNumericClose(regressionS0.phaseVelocity_mps, regressionRepeat.modes.S0.phaseVelocity_mps, regressionTol, ...
    'Rayleigh-Lamb S0 regression Cp values are not repeatable.');

%% Historical numerical and synthetic-fitting coverage
fprintf('\nRunning canonical core numerical regression owner...\n');
run_core_numerical_regression_tests;

fprintf('\nCore smoke tests passed.\n');

function assertFunctionsOnPath(functionNames, label)
for i = 1:numel(functionNames)
    functionName = functionNames{i};
    assert(~isempty(which(functionName)), ...
        'Missing %s on MATLAB path: %s.', label, functionName);
end
end

function assertFunctionsAbsent(functionNames, label)
for i = 1:numel(functionNames)
    functionName = functionNames{i};
    assert(isempty(which(functionName)), ...
        'Unexpected %s on MATLAB path: %s.', label, functionName);
end
end

function assertNumericClose(actual, expected, tol, message)
if isempty(actual) && isempty(expected)
    return;
end
assert(isequal(size(actual), expectedSizeShim(expected)), message);
assert(max(abs(actual(:) - expected(:))) < tol, message);
end

function s = expectedSizeShim(x)
s = size(x);
end
