clear; clc;
if isempty(which('mrlfeSolve'))
    startup
end

% Run maintained mRLFE smoke and contract tests.
%
% This runner covers the public mRLFE execution surface, naming contracts,
% tracking-quality summary, residual objective behavior, and lightweight fitting
% contracts. Obsolete atlas-route checks were removed with the legacy route
% cleanup and are replaced by run_mrlfe_route_integrity_tests.

fprintf('\nRunning mRLFE smoke tests...\n');
fprintf('----------------------------\n');

fprintf('\nChecking maintained mRLFE API and tests...\n');
assertFunctionsOnPath({ ...
    'mrlfeSolve', ...
    'mrlfeObjectiveResidual', ...
    'mrlfeSetYoungModulusForShearPoisson', ...
    'summarizeMRLFETrackingQuality', ...
    'mrlfe_sweep_mu_A0Like', ...
    'mrlfe_sweep_mu_S0Like', ...
    'mrlfe_sweep_etaS_A0Like', ...
    'mrlfe_sweep_etaS_S0Like', ...
    'mrlfe_sweep_thickness_A0Like', ...
    'mrlfe_sweep_thickness_S0Like', ...
    'test_mrlfe_smoke', ...
    'test_mrlfe_etaS_zero_limit', ...
    'test_mrlfe_residual_objective_contract', ...
    'test_mrlfe_tracking_quality_summary', ...
    'test_mrlfe_maintained_entrypoints_naming', ...
    'test_mrlfe_diagnostic_material_sweep_contract'}, ...
    'mRLFE maintained API/test');
assertFunctionsAbsent({ ...
    'sweep_mu_A0Like_viscoelastic', ...
    'sweep_mu_S0Like_viscoelastic', ...
    'sweep_etaS_A0Like_viscoelastic', ...
    'sweep_etaS_S0Like_viscoelastic', ...
    'sweep_thickness_A0Like_viscoelastic', ...
    'sweep_thickness_S0Like_viscoelastic'}, ...
    'obsolete mRLFE sweep entrypoint');

fprintf('\n[mRLFE 1/6] mRLFE smoke test\n');
test_mrlfe_smoke;

fprintf('\n[mRLFE 2/6] mRLFE etaS zero-limit contract test\n');
test_mrlfe_etaS_zero_limit;

fprintf('\n[mRLFE 3/6] mRLFE residual objective contract test\n');
test_mrlfe_residual_objective_contract;

fprintf('\n[mRLFE 4/6] mRLFE tracking quality summary contract test\n');
test_mrlfe_tracking_quality_summary;

fprintf('\n[mRLFE 5/6] mRLFE maintained entrypoints naming guard test\n');
test_mrlfe_maintained_entrypoints_naming;

fprintf('\n[mRLFE 6/6] mRLFE diagnostic material sweep contract test\n');
test_mrlfe_diagnostic_material_sweep_contract;

fprintf('\nmRLFE smoke tests passed.\n');

function assertFunctionsOnPath(functionNames, label)
for i = 1:numel(functionNames)
    functionName = functionNames{i};
    assert(~isempty(which(functionName)), ...
        'Missing %s on MATLAB path: %s.', label, functionName);
end
end

function assertFunctionsAbsent(functionNames, label)
for i = 1:numel(functionNames)
    functionName = functionNames{i};
    assert(isempty(which(functionName)), ...
        'Unexpected %s on MATLAB path: %s.', label, functionName);
end
end
