clear; clc;
startup

% Run maintained acoustoelastic IOP/HGO smoke and contract tests.

fprintf('\nRunning acoustoelastic IOP/HGO smoke tests...\n');
fprintf('----------------------------------------------\n');

fprintf('\nChecking maintained acoustoelastic IOP/HGO API functions...\n');
assertFunctionsOnPath({ ...
    'solveAcoustoelasticIOPHGOBranch', ...
    'solveAcoustoelasticIOPHGOAtlasBranch', ...
    'solveAcoustoelasticAtlasBranch', ...
    'solveAcoustoelasticIOPHGODispersion', ...
    'solveAcoustoelasticDispersion', ...
    'solveAcoustoelasticComplexCDispersion', ...
    'objectiveAcoustoelasticResidual', ...
    'objectiveAcoustoelasticComplexDeterminant', ...
    'buildAcoustoelasticMatrix', ...
    'defaultAcoustoelasticIOPHGOOptions', ...
    'aeNormalizeBranchPolicy', ...
    'computeAcoustoelasticABGFromIOPHGO', ...
    'computeAcoustoelasticAlphaBetaGamma', ...
    'computeAcoustoelasticPrestressSigma', ...
    'computeAcoustoelasticSRoots', ...
    'solveAcoustoelasticHGOStretch', ...
    'summarizeAcoustoelasticIOPHGOTrackingQuality', ...
    'aeRunSweep', ...
    'aeSummarizeSweep'}, ...
    'Acoustoelastic maintained API');

fprintf('\nChecking maintained sweep plotting helpers...\n');
assertFunctionsOnPath({ ...
    'plotSweepCpFigure', ...
    'buildParametricSweepPlotData', ...
    'aeBuildSweepPlotData', ...
    'plotParametricSweepCp', ...
    'aePlotSweepCp'}, ...
    'maintained sweep plotting helper');

fprintf('\nChecking maintained acoustoelastic analysis helpers...\n');
assertFunctionsOnPath({ ...
    'aeOutputFolder', ...
    'aeResolveResultFile', ...
    'aeRunLegacyScript', ...
    'aeDefaultSweepParams', ...
    'aeDefaultSweepOptions', ...
    'aeWriteSweepOutputs', ...
    'aeRunGridSweep', ...
    'aeSummarizeGridSweep', ...
    'aeBuildGridSweepCpCube', ...
    'aePlotGridSweepCp', ...
    'aePlotGridSweepCpByAxis', ...
    'aePlotGridSweepFrequencySurfaceInteractive', ...
    'aeSaveExampleFigure', ...
    'aeDeleteExampleFigure', ...
    'aeScoreBranchIdentityCandidates', ...
    'aeBuildIdentityA0DiagnosticBranch', ...
    'aeDiagnoseAtlasA0TruncationCause', ...
    'aeAnalyzeBranchPersistenceCandidates', ...
    'aeRefineAtlasA0BranchPersistence', ...
    'aeClassifyAmbiguityRegime', ...
    'aeExtractRawBranch1Candidate', ...
    'aeComputeModalAtlasForCase', ...
    'aeFindTopModalAtlasLocalMinima', ...
    'aeLinkModalAtlasMinimaIntoBranches', ...
    'aeDefaultIdentityA0ValidationParams', ...
    'aeDefaultIdentityA0ValidationOptions', ...
    'aeDefaultIdentityA0ValidationGrid', ...
    'aeBuildFitProblem', ...
    'aeEvaluateFitModel', ...
    'aeFitDispersionData'}, ...
    'Acoustoelastic maintained analysis helper');

fprintf('\nChecking maintained acoustoelastic public workflows...\n');
assertFunctionsOnPath({ ...
    'run_atlas_branch', ...
    'sweep_iop', ...
    'sweep_mu', ...
    'sweep_mu_iop', ...
    'sweep_thickness', ...
    'sweep_k1', ...
    'sweep_k2', ...
    'sweep_radius'}, ...
    'Acoustoelastic maintained public workflow');

fprintf('\nChecking maintained acoustoelastic diagnostic evidence entrypoints...\n');
assertFunctionsOnPath({ ...
    'compare_atlasA0_vs_raw_branch1', ...
    'validate_atlas_raw_grid', ...
    'diagnose_raw_branch_corner', ...
    'diagnose_branch_families', ...
    'diagnose_sweep_reliability', ...
    'diagnose_atlas_truncation', ...
    'diagnose_idA0_plausibility'}, ...
    'Acoustoelastic maintained diagnostic evidence entrypoint');

fprintf('\nChecking maintained acoustoelastic tests...\n');
assertFunctionsOnPath({ ...
    'test_acoustoelastic_iop_hgo_branch_policy_validation', ...
    'test_acoustoelastic_iop_hgo_constitutive_identity', ...
    'test_acoustoelastic_iop_hgo_atlasA0_smoke', ...
    'test_acoustoelastic_iop_hgo_fallback_invalidation', ...
    'test_acoustoelastic_iop_hgo_internal_tracking_grid', ...
    'test_acoustoelastic_iop_hgo_identityA0_diagnostic_policy', ...
    'test_acoustoelastic_iop_hgo_short_entrypoints', ...
    'test_acoustoelastic_iop_hgo_branch_persistence_refinement', ...
    'test_ae_analyze_truncation_recovery', ...
    'test_ae_fit_synthetic_atlasA0', ...
    'test_ae_physical_sweep_examples_contract', ...
    'test_sweep_plot_renderer_contract'}, ...
    'Acoustoelastic maintained test');

fprintf('\n[AE 1/10] Acoustoelastic atlas branch policy validation test\n');
test_acoustoelastic_iop_hgo_branch_policy_validation;

fprintf('\n[AE 2/10] Acoustoelastic fallback invalidation policy test\n');
test_acoustoelastic_iop_hgo_fallback_invalidation;

fprintf('\n[AE 3/10] Acoustoelastic internal tracking grid test\n');
test_acoustoelastic_iop_hgo_internal_tracking_grid;

fprintf('\n[AE 4/10] Acoustoelastic truncation recovery helper unit test\n');
test_ae_analyze_truncation_recovery;

fprintf('\n[AE 5/10] Acoustoelastic branch-persistence refinement unit test\n');
test_acoustoelastic_iop_hgo_branch_persistence_refinement;

fprintf('\n[AE 6/10] Acoustoelastic IOP/HGO constitutive identity test\n');
test_acoustoelastic_iop_hgo_constitutive_identity;

fprintf('\n[AE 7/10] Acoustoelastic IOP/HGO atlasA0 smoke test\n');
test_acoustoelastic_iop_hgo_atlasA0_smoke;

fprintf('\n[AE 8/10] Acoustoelastic physical sweep example contract test\n');
test_ae_physical_sweep_examples_contract;

fprintf('\n[AE 9/10] Shared sweep plot renderer contract test\n');
test_sweep_plot_renderer_contract;

fprintf('\n[AE 10/10] Acoustoelastic IOP/HGO atlasA0 fitting test\n');
test_ae_fit_synthetic_atlasA0;

fprintf('\nAcoustoelastic IOP/HGO smoke tests passed.\n');

function assertFunctionsOnPath(functionNames, label)
for i = 1:numel(functionNames)
    functionName = functionNames{i};
    assert(~isempty(which(functionName)), ...
        'Missing %s on MATLAB path: %s.', label, functionName);
end
end