clear; clc;
if isempty(which('mrlfeSolve'))
    startup
end

% Run maintained acoustoelastic IOP/HGO contracts plus representative atlas,
% sweep-renderer, and synthetic-fitting execution checks.

fprintf('\nRunning acoustoelastic IOP/HGO smoke tests...\n');
fprintf('----------------------------------------------\n');

fprintf('\nChecking maintained acoustoelastic IOP/HGO API functions...\n');
assertFunctionsOnPath({ ...
    'solveAcoustoelasticIOPHGOBranch', ...
    'solveAcoustoelasticIOPHGOAtlasBranch', ...
    'solveAcoustoelasticAtlasBranch', ...
    'solveAcoustoelasticIOPHGODispersion', ...
    'solveAcoustoelasticDispersion', ...
    'solveAcoustoelasticComplexCDispersion', ...
    'objectiveAcoustoelasticResidual', ...
    'objectiveAcoustoelasticComplexDeterminant', ...
    'buildAcoustoelasticMatrix', ...
    'defaultAcoustoelasticIOPHGOOptions', ...
    'aeNormalizeBranchPolicy', ...
    'computeAcoustoelasticABGFromIOPHGO', ...
    'computeAcoustoelasticAlphaBetaGamma', ...
    'computeAcoustoelasticPrestressSigma', ...
    'computeAcoustoelasticSRoots', ...
    'solveAcoustoelasticHGOStretch', ...
    'summarizeAcoustoelasticIOPHGOTrackingQuality', ...
    'aeRunSweep', ...
    'aeSummarizeSweep'}, ...
    'Acoustoelastic maintained API');

fprintf('\nChecking maintained sweep plotting helpers...\n');
assertFunctionsOnPath({ ...
    'plotSweepCpFigure', ...
    'buildParametricSweepPlotData', ...
    'aeBuildSweepPlotData', ...
    'plotParametricSweepCp', ...
    'aePlotSweepCp'}, ...
    'maintained sweep plotting helper');

fprintf('\nChecking maintained acoustoelastic analysis helpers...\n');
assertFunctionsOnPath({ ...
    'aeOutputFolder', ...
    'aeResolveResultFile', ...
    'aeDefaultSweepParams', ...
    'aeDefaultSweepOptions', ...
    'aeWriteSweepOutputs', ...
    'aeRunGridSweep', ...
    'aeSummarizeGridSweep', ...
    'aeBuildGridSweepCpCube', ...
    'aePlotSweepCp', ...
    'aePlotGridSweepCp', ...
    'aePlotGridSweepCpByAxis', ...
    'aePlotGridSweepFrequencySurfaceInteractive', ...
    'aeSaveExampleFigure', ...
    'aeDeleteExampleFigure', ...
    'aeScoreBranchIdentityCandidates', ...
    'aeBuildIdentityA0DiagnosticBranch', ...
    'aeDiagnoseAtlasA0TruncationCause', ...
    'aeAnalyzeBranchPersistenceCandidates', ...
    'aeRefineAtlasA0BranchPersistence', ...
    'aeClassifyAmbiguityRegime', ...
    'aeExtractRawBranch1Candidate', ...
    'aeComputeModalAtlasForCase', ...
    'aeFindTopModalAtlasLocalMinima', ...
    'aeLinkModalAtlasMinimaIntoBranches', ...
    'aeDefaultIdentityA0ValidationParams', ...
    'aeDefaultIdentityA0ValidationOptions', ...
    'aeDefaultIdentityA0ValidationGrid', ...
    'aeBuildFitProblem', ...
    'aeEvaluateFitModel', ...
    'aeFitDispersionData'}, ...
    'Acoustoelastic maintained analysis helper');

fprintf('\nChecking maintained acoustoelastic public workflows...\n');
assertFunctionsOnPath({ ...
    'run_atlas_branch', ...
    'ae_sweep_iop_A0Like', ...
    'ae_sweep_mu_A0Like', ...
    'ae_sweep_mu_iop_A0Like', ...
    'ae_sweep_thickness_A0Like', ...
    'ae_sweep_k1_A0Like', ...
    'ae_sweep_k2_A0Like', ...
    'ae_sweep_radius_A0Like'}, ...
    'Acoustoelastic maintained public workflow');
assertFunctionsAbsent({ ...
    'sweep_iop', ...
    'sweep_mu', ...
    'sweep_mu_iop', ...
    'sweep_thickness', ...
    'sweep_k1', ...
    'sweep_k2', ...
    'sweep_radius'}, ...
    'obsolete Acoustoelastic sweep entrypoint');

fprintf('\nChecking maintained acoustoelastic diagnostic evidence entrypoints...\n');
assertFunctionsOnPath({ ...
    'compare_atlasA0_vs_raw_branch1', ...
    'validate_atlas_raw_grid', ...
    'diagnose_raw_branch_corner', ...
    'diagnose_branch_families', ...
    'diagnose_sweep_reliability', ...
    'diagnose_atlas_truncation', ...
    'diagnose_idA0_plausibility'}, ...
    'Acoustoelastic maintained diagnostic evidence entrypoint');

fprintf('\nChecking maintained acoustoelastic tests...\n');
assertFunctionsOnPath({ ...
    'test_acoustoelastic_iop_hgo_branch_policy_validation', ...
    'test_acoustoelastic_iop_hgo_constitutive_identity', ...
    'test_acoustoelastic_iop_hgo_atlasA0_smoke', ...
    'test_acoustoelastic_iop_hgo_fallback_invalidation', ...
    'test_acoustoelastic_iop_hgo_internal_tracking_grid', ...
    'test_acoustoelastic_iop_hgo_identityA0_diagnostic_policy', ...
    'test_acoustoelastic_iop_hgo_short_entrypoints', ...
    'test_acoustoelastic_iop_hgo_branch_persistence_refinement', ...
    'test_ae_analyze_truncation_recovery', ...
    'test_ae_fit_synthetic_atlasA0', ...
    'test_ae_physical_sweep_examples_contract', ...
    'test_sweep_plot_renderer_contract'}, ...
    'Acoustoelastic maintained test');

fprintf('\n[AE group 1/2] Quick contracts and representative solves\n');
run_ae_quick_tests;

fprintf('\n[AE group 2/2] Extended synthetic fitting regression\n');
run_ae_extended_tests;

fprintf('\nAcoustoelastic IOP/HGO smoke tests passed.\n');

function assertFunctionsOnPath(functionNames, label)
for i = 1:numel(functionNames)
    functionName = functionNames{i};
    assert(~isempty(which(functionName)), ...
        'Missing %s on MATLAB path: %s.', label, functionName);
end
end

function assertFunctionsAbsent(functionNames, label)
for i = 1:numel(functionNames)
    functionName = functionNames{i};
    assert(isempty(which(functionName)), ...
        'Unexpected %s on MATLAB path: %s.', label, functionName);
end
end
