clear; clc;
startup

% Run core path/API contracts, cross-model numerical regression, shared fitting
% helpers, and representative Rayleigh-Lamb and mRLFE synthetic fitting checks.

fprintf('\nRunning core smoke tests...\n');
fprintf('---------------------------\n');

%% Shared material helpers
fprintf('\nChecking shared elastic material helpers...\n');
assertFunctionsOnPath({ ...
    'elasticFromMuNu', ...
    'elasticFromLame'}, ...
    'shared elastic material helper');

elastic = elasticFromMuNu(75e3, 0.4999, 1070);
assertNumericClose(elastic.E, 2 * 75e3 * (1 + 0.4999), 1e-10, ...
    'elasticFromMuNu returned an unexpected Young modulus.');
assertNumericClose(elastic.mu, 75e3, 1e-12, ...
    'elasticFromMuNu should preserve mu.');
assert(elastic.lambda > 0 && elastic.K > 0 && elastic.CL > elastic.CT, ...
    'elasticFromMuNu should return positive lambda/K and CL > CT.');

%% Startup/path policy
fprintf('\nChecking startup path policy...\n');
test_startup_path_policy

fprintf('\nChecking shared path and output-folder utilities...\n');
test_repository_root_utilities
test_model_output_folder_helpers

%% Shared fitting helpers
fprintf('\nChecking shared fitting helper functions...\n');
assertFunctionsOnPath({ ...
    'normalizeExperimentalDispersionData', ...
    'validateExperimentalDispersionData', ...
    'computeDispersionFitResiduals', ...
    'computeDispersionFitMetrics', ...
    'computeConstantSpeedBaseline', ...
    'assessFitPhysicalQuality', ...
    'buildParameterVector', ...
    'unpackParameterVector', ...
    'estimateLocalSensitivity', ...
    'assessFitIdentifiability'}, ...
    'shared fitting helper');

%% Rayleigh-Lamb primary API path checks
fprintf('\nChecking Rayleigh-Lamb primary rl* API functions...\n');
assertFunctionsOnPath({ ...
    'setSweepPlotLimits', ...
    'rlBuildFrequencyVector', ...
    'rlComputeFundamentalLambModes', ...
    'rlComputeGeometry', ...
    'rlComputeMaterial', ...
    'rlDefaultOptions', ...
    'rlDefaultParams', ...
    'rlMakeBranchSpec', ...
    'rlValidateOptions', ...
    'rlValidateParams', ...
    'rlAResidual', ...
    'rlSResidual', ...
    'rlComputeA0ThinPlateApproximation', ...
    'rlComputeAnalyticalApproximations', ...
    'rlComputeS0ExtensionalApproximation', ...
    'rlSolveFundamentalBranch'}, ...
    'Rayleigh-Lamb maintained API');

fprintf('\nChecking Rayleigh-Lamb fitting helper functions...\n');
assertFunctionsOnPath({ ...
    'rlBuildFitProblem', ...
    'rlEvaluateFitModel', ...
    'rlFitDispersionData'}, ...
    'Rayleigh-Lamb fitting helper');

fprintf('\nChecking mRLFE fitting helper functions...\n');
assertFunctionsOnPath({ ...
    'mrlfeBuildFitProblem', ...
    'mrlfeEvaluateFitModel', ...
    'mrlfeFitDispersionData'}, ...
    'mRLFE fitting helper');

fprintf('\nChecking Rayleigh-Lamb sweep helper functions...\n');
assertFunctionsOnPath({ ...
    'rlDefaultSweepParams', ...
    'rlDefaultSweepOptions', ...
    'rlMakeSweepSpec', ...
    'rlRunSweepExample', ...
    'rlOutputFolder', ...
    'rlWriteSweepOutputs', ...
    'rlSaveExampleFigure', ...
    'rl_sweep_thickness_A0', ...
    'rl_sweep_thickness_S0'}, ...
    'Rayleigh-Lamb sweep helper');
assertFunctionsAbsent({ ...
    'sweep_thickness_A0_elastic', ...
    'sweep_thickness_S0_elastic'}, ...
    'obsolete Rayleigh-Lamb sweep entrypoint');

%% Rayleigh-Lamb minimal numerical regression fixtures
fprintf('\nChecking Rayleigh-Lamb minimal numerical regression fixtures...\n');
regressionTol = 1e-12;

regressionParams = rlDefaultParams();
regressionParams.fmin = 10;
regressionParams.fmax = 100;
regressionParams.numFrequencyPoints = 10;
regressionParams.frequencySpacing = "linspace";

regressionOptions = rlDefaultOptions();
regressionOptions.computeA0 = true;
regressionOptions.computeS0 = true;
regressionOptions.computeMRLFE = false;

regressionResults = rlComputeFundamentalLambModes(regressionParams, regressionOptions);
regressionRepeat = rlComputeFundamentalLambModes(regressionParams, regressionOptions);
expectedSize = size(rlBuildFrequencyVector(regressionParams));

assert(isfield(regressionResults, 'grid') && isfield(regressionResults.grid, 'frequency'), ...
    'Rayleigh-Lamb regression results are missing grid.frequency.');
assert(isfield(regressionResults, 'modes') && isfield(regressionResults.modes, 'A0'), ...
    'Rayleigh-Lamb regression results are missing A0 mode output.');
assert(isfield(regressionResults.modes, 'S0'), ...
    'Rayleigh-Lamb regression results are missing S0 mode output.');
assert(string(regressionResults.material.modelType) == "ShearPoisson", ...
    'Rayleigh-Lamb default material model must be ShearPoisson.');

regressionFrequency = regressionResults.grid.frequency;
regressionA0 = regressionResults.modes.A0;
regressionS0 = regressionResults.modes.S0;

assert(isequal(size(regressionFrequency), expectedSize), ...
    'Rayleigh-Lamb regression frequency size does not match the requested grid.');
assert(isequal(size(regressionA0.frequency), expectedSize), ...
    'Rayleigh-Lamb A0 regression frequency size does not match the requested grid.');
assert(isequal(size(regressionS0.frequency), expectedSize), ...
    'Rayleigh-Lamb S0 regression frequency size does not match the requested grid.');
assert(isequal(size(regressionA0.Cp), expectedSize), ...
    'Rayleigh-Lamb A0 regression Cp size does not match the requested grid.');
assert(isequal(size(regressionS0.Cp), expectedSize), ...
    'Rayleigh-Lamb S0 regression Cp size does not match the requested grid.');

assert(all(isfinite(regressionFrequency(:))), ...
    'Rayleigh-Lamb regression frequencies must be finite.');
assert(all(isfinite(regressionA0.Cp(:)) & regressionA0.Cp(:) > 0), ...
    'Rayleigh-Lamb A0 regression Cp values must be finite and positive.');
assert(all(isfinite(regressionS0.Cp(:)) & regressionS0.Cp(:) > 0), ...
    'Rayleigh-Lamb S0 regression Cp values must be finite and positive.');
assert(any(abs(regressionA0.Cp(:) - regressionS0.Cp(:)) > regressionTol), ...
    'Rayleigh-Lamb A0 and S0 regression Cp outputs should not be identical.');

assertNumericClose(regressionFrequency, regressionRepeat.grid.frequency, regressionTol, ...
    'Rayleigh-Lamb regression frequencies are not repeatable.');
assertNumericClose(regressionA0.Cp, regressionRepeat.modes.A0.Cp, regressionTol, ...
    'Rayleigh-Lamb A0 regression Cp values are not repeatable.');
assertNumericClose(regressionS0.Cp, regressionRepeat.modes.S0.Cp, regressionTol, ...
    'Rayleigh-Lamb S0 regression Cp values are not repeatable.');

%% Lightweight cross-model numerical regression
fprintf('\nChecking lightweight cross-model numerical regression snapshots...\n');
test_lightweight_numerical_regression

%% Shared fitting helper smoke test
fprintf('\nRunning shared fitting helper smoke test from core suite...\n');
test_fitting_helpers_smoke

%% Rayleigh-Lamb fitting smoke test
fprintf('\nRunning Rayleigh-Lamb fitting smoke test from core suite...\n');
test_rl_fit_synthetic_A0

%% mRLFE fitting smoke test
fprintf('\nRunning mRLFE fitting smoke test from core suite...\n');
test_mrlfe_fit_synthetic_A0Like

fprintf('\nCore smoke tests passed.\n');

function assertFunctionsOnPath(functionNames, label)
for i = 1:numel(functionNames)
    functionName = functionNames{i};
    assert(~isempty(which(functionName)), ...
        'Missing %s on MATLAB path: %s.', label, functionName);
end
end

function assertFunctionsAbsent(functionNames, label)
for i = 1:numel(functionNames)
    functionName = functionNames{i};
    assert(isempty(which(functionName)), ...
        'Unexpected %s on MATLAB path: %s.', label, functionName);
end
end

function assertNumericClose(actual, expected, tol, message)
if isempty(actual) && isempty(expected)
    return;
end
assert(isequal(size(actual), expectedSizeShim(expected)), message);
assert(max(abs(actual(:) - expected(:))) < tol, message);
end

function s = expectedSizeShim(x)
s = size(x);
end
