clear; clc;
startup

%TEST_MRLFE_MAINTAINED_ENTRYPOINTS_NAMING Guard maintained mRLFE naming surface.
%
% The maintained mRLFE execution surface should expose physical/model names.

repoRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
forbiddenToken = char([72 97 110]);
forbiddenModelName = char([109 82 76 70 69 72 97 110 86 105 115 99 111 82 101 97 108 75]);

entrypointsPath = fullfile(repoRoot, 'docs', 'maintained_entrypoints.md');
entrypointsText = fileread(entrypointsPath);
sectionStart = strfind(entrypointsText, '## mRLFE model');
sectionEnd = strfind(entrypointsText, '## Smoke-test scope');
assert(~isempty(sectionStart) && ~isempty(sectionEnd), ...
    'maintained_entrypoints.md must contain mRLFE and smoke-test sections.');

mrlfeSection = entrypointsText(sectionStart(1):sectionEnd(1)-1);
assert(contains(mrlfeSection, 'viscoelastic'), ...
    'Maintained mRLFE section should use physical viscoelastic naming.');
assert(~contains(mrlfeSection, forbiddenToken), ...
    'Maintained mRLFE section should not contain author-labeled names.');
assert(contains(mrlfeSection, 'mrlfeSetYoungModulusForShearPoisson'), ...
    'Maintained mRLFE section should list mrlfeSetYoungModulusForShearPoisson.');
assert(contains(mrlfeSection, 'mrlfeSelectRealKBranches'), ...
    'Maintained mRLFE section should list mrlfeSelectRealKBranches.');
assert(contains(mrlfeSection, 'summarizeMRLFETrackingQuality'), ...
    'Maintained mRLFE section should list summarizeMRLFETrackingQuality.');
assert(contains(mrlfeSection, 'compareMRLFETrackingStrategies'), ...
    'Maintained mRLFE section should list compareMRLFETrackingStrategies.');
assert(contains(mrlfeSection, 'stress_test_mrlfe_real_k_range'), ...
    'Maintained mRLFE section should list the unified real-k range diagnostic.');

readmePath = fullfile(repoRoot, 'README.md');
readmeText = fileread(readmePath);
readmeStart = strfind(readmeText, '## mRLFE solver workflow');
assert(~isempty(readmeStart), 'README.md must contain the mRLFE solver workflow section.');
readmeSection = readmeText(readmeStart(1):end);
assert(contains(readmeSection, 'viscoelastic'), ...
    'README mRLFE workflow should use physical viscoelastic naming.');
assert(~contains(readmeSection, forbiddenToken), ...
    'README mRLFE workflow should not contain author-labeled names.');
assert(contains(readmeSection, 'compare_mrlfe_elastic_vs_visco_cp'), ...
    'README should list the renamed elastic-vs-visco comparison example.');

renamedExample = fullfile(repoRoot, 'examples', 'mrlfe', 'basic', 'compare_mrlfe_elastic_vs_visco_cp.m');
assert(isfile(renamedExample), 'Renamed mRLFE elastic-vs-visco example is missing.');

validityDiagnostic = fullfile(repoRoot, 'examples', 'mrlfe', 'diagnostics', 'diagnose_mrlfe_visco_validity_breakdown.m');
assert(isfile(validityDiagnostic), 'mRLFE visco validity diagnostic is missing.');

landscapeDiagnostic = fullfile(repoRoot, 'examples', 'mrlfe', 'diagnostics', 'diagnose_mrlfe_visco_residual_landscape.m');
assert(isfile(landscapeDiagnostic), 'mRLFE visco residual landscape diagnostic is missing.');

rangeStressTest = fullfile(repoRoot, 'examples', 'mrlfe', 'diagnostics', 'stress_test_mrlfe_real_k_range.m');
assert(isfile(rangeStressTest), 'Unified mRLFE real-k range stress test is missing.');
assert(~isfile(fullfile(repoRoot, 'examples', 'mrlfe', 'diagnostics', 'stress_test_mrlfe_elastic_range.m')), ...
    'Obsolete separate mRLFE elastic range stress test should not exist.');
assert(~isfile(fullfile(repoRoot, 'examples', 'mrlfe', 'diagnostics', 'stress_test_mrlfe_visco_range.m')), ...
    'Obsolete separate mRLFE visco range stress test should not exist.');

maintainedFiles = { ...
    fullfile(repoRoot, 'analysis', 'mrlfe', 'mrlfeModelCandidateNames.m'), ...
    fullfile(repoRoot, 'analysis', 'mrlfe', 'mrlfeSetYoungModulusForShearPoisson.m'), ...
    fullfile(repoRoot, 'analysis', 'mrlfe', 'mrlfeSelectRealKBranches.m'), ...
    fullfile(repoRoot, 'app', 'adapters', 'guiNormalizeRawResult.m'), ...
    fullfile(repoRoot, 'app', 'adapters', 'guiRunMRLFEModel.m'), ...
    fullfile(repoRoot, 'app', 'adapters', 'guiRunMRLFESweep.m'), ...
    fullfile(repoRoot, 'app', 'createModelTabs.m'), ...
    fullfile(repoRoot, 'app', 'createPlotTab.m'), ...
    fullfile(repoRoot, 'models', 'rayleigh_lamb', 'core', 'rlComputeFundamentalLambModes.m'), ...
    fullfile(repoRoot, 'models', 'rayleigh_lamb', 'core', 'rlDefaultOptions.m'), ...
    fullfile(repoRoot, 'models', 'mrlfe', 'solvers', 'computeMRLFE.m'), ...
    fullfile(repoRoot, 'models', 'mrlfe', 'core', 'mrlfeMatrix.m'), ...
    fullfile(repoRoot, 'tests', 'test_gui_normalized_adapters_smoke.m'), ...
    fullfile(repoRoot, 'tests', 'mrlfe', 'test_mrlfe_model_candidate_names.m'), ...
    fullfile(repoRoot, 'tests', 'mrlfe', 'test_mrlfe_smoke.m'), ...
    fullfile(repoRoot, 'tests', 'mrlfe', 'test_mrlfe_etaS_zero_limit.m'), ...
    fullfile(repoRoot, 'tests', 'mrlfe', 'test_mrlfe_elastic_reference_buffer.m')};
for i = 1:numel(maintainedFiles)
    fileText = fileread(maintainedFiles{i});
    assert(~contains(fileText, forbiddenToken), ...
        'Maintained mRLFE file should not contain author-labeled names: %s', maintainedFiles{i});
end

analysisFiles = { ...
    fullfile(repoRoot, 'analysis', 'plotParametricSweepCp.m'), ...
    fullfile(repoRoot, 'analysis', 'summarizeParametricSweepBranch.m')};
for i = 1:numel(analysisFiles)
    fileText = fileread(analysisFiles{i});
    assert(contains(fileText, 'mRLFEViscoRealK'), ...
        'Maintained analysis helper should document mRLFEViscoRealK: %s', analysisFiles{i});
    assert(~contains(fileText, forbiddenModelName), ...
        'Maintained analysis helper should not contain author-labeled mRLFE model names: %s', analysisFiles{i});
end

trackerDiagnostic = fullfile(repoRoot, 'examples', 'mrlfe', 'diagnostics', 'compare_mrlfe_tracker_vs_condition_peaks.m');
trackerText = fileread(trackerDiagnostic);
assert(contains(trackerText, 'mRLFEViscoRealK'), ...
    'Tracker diagnostic should use mRLFEViscoRealK as the selectable viscoelastic model.');
assert(~contains(trackerText, forbiddenModelName), ...
    'Tracker diagnostic should not contain author-labeled mRLFE model names.');

fprintf('test_mrlfe_maintained_entrypoints_naming passed. Maintained mRLFE docs use physical naming.\n');
