clear; clc;
startup

fprintf('\nRunning GUI mRLFE zero-eta atlas fitting contract test...\n');
fprintf('---------------------------------------------------------\n');

branchName = "A0Like";
trueMu = 90e3;
frequency_Hz = linspace(1000, 5000, 10).';

params = mrlfeDefaultSweepParams();
params.mu = trueMu;
params.etaS = 0;
options = mrlfeDefaultSweepOptions(branchName, 'EtaS', 0, ...
    'UseUnifiedAtlasRoute', true, 'A0Policy', "adaptivePhysicalTail");

[CpSynthetic, rawSynthetic] = mrlfeEvaluateFitModel(params, frequency_Hz, branchName, options);
assert(rawSynthetic.evaluationPath.routeFamily == "atlas", 'Zero-eta synthetic data should use atlas route family.');
assert(rawSynthetic.evaluationPath.path == "zero_viscosity_adaptive_atlas", ...
    'Zero-eta synthetic data should use the adaptive atlas fit route.');
assert(any(isfinite(CpSynthetic)), 'Zero-eta atlas synthetic data must contain finite Cp values.');

experimental = struct();
experimental.frequency_Hz = frequency_Hz;
experimental.Cp_mps = CpSynthetic;
experimental.validMask = isfinite(CpSynthetic);

request = guiBuildFitRequest("mrlfe", ...
    'branchName', branchName, ...
    'mode', "basic", ...
    'experimental', experimental, ...
    'fixedParams', struct('thickness', params.thickness, 'rho', params.rho, 'nu', params.nu, 'etaS', 0), ...
    'freeParams', "mu", ...
    'initialGuess', struct('mu', trueMu), ...
    'bounds', struct('mu', [0.8 * trueMu, 1.2 * trueMu]), ...
    'controls', struct('robustness', "Fast", 'etaS', 0, ...
        'fluidDensity', 1000, 'fluidSoundSpeed', 1500, ...
        'mrlfeUseUnifiedAtlasRoute', true, 'mrlfeA0Policy', "adaptivePhysicalTail"), ...
    'fitOptions', struct('useStandardErrorWeights', false, ...
        'optimizerOptions', optimset('Display', 'off', 'MaxIter', 2, 'MaxFunEvals', 5, 'TolX', 1e-4)));

fitOutput = guiFitMRLFESolver(request);
assert(fitOutput.routePolicy.requestAtlasFitRoute == true, 'Zero-eta FitTool mRLFE should request atlas-fit route.');
assert(fitOutput.routePolicy.expectedPath == "mrlfe_atlas", 'Zero-eta FitTool mRLFE should expect atlas route family.');
assert(fitOutput.routePolicy.actualPath == "zero_viscosity_adaptive_atlas", ...
    'Zero-eta FitTool mRLFE should use the zero-viscosity adaptive atlas path.');
assert(fitOutput.routePolicy.mrlfeA0Policy == "adaptivePhysicalTail", ...
    'Zero-eta FitTool mRLFE should preserve adaptivePhysicalTail policy.');
assert(fitOutput.fitResult.metrics.RMSE < 1e-4, 'Zero-eta synthetic atlas fit RMSE is too high.');

fprintf('Route: %s | RMSE: %.6g m/s\n', fitOutput.routePolicy.actualPath, fitOutput.fitResult.metrics.RMSE);
fprintf('\nGUI mRLFE zero-eta atlas fitting contract test passed.\n');
