clear; clc;
startup

fprintf('\nRunning GUI mRLFE fit route policy contract test...\n');
fprintf('------------------------------------------------\n');

branchName = "A0Like";
frequency_Hz = linspace(1000, 8000, 10).';
params = mrlfeDefaultSweepParams();
params.mu = 75e3;
params.etaS = 0.12;

options = mrlfeDefaultSweepOptions(branchName, 'EtaS', params.etaS);
options.mrlfeUseDirectViscoAtlas = true;
options.mrlfeDisableForwardCache = true;
[CpSynthetic, rawSynthetic] = mrlfeEvaluateFitModel(params, frequency_Hz, branchName, options);
assert(rawSynthetic.evaluationPath.usedDirectViscoAtlas == true, 'Synthetic data setup should use the direct atlas path.');

experimental = struct();
experimental.frequency_Hz = frequency_Hz;
experimental.Cp_mps = CpSynthetic;
experimental.validMask = isfinite(CpSynthetic);

etaSRequest = guiBuildFitRequest("mrlfe", ...
    'branchName', "A0Like", ...
    'mode', "basic", ...
    'experimental', experimental, ...
    'fixedParams', struct('mu', params.mu, 'thickness', params.thickness, 'rho', params.rho, 'nu', params.nu), ...
    'freeParams', "etaS", ...
    'initialGuess', struct('etaS', params.etaS), ...
    'bounds', struct('etaS', [0.0, 0.30]), ...
    'controls', struct('robustness', "Fast", 'etaS', params.etaS, 'fluidDensity', 1000, 'fluidSoundSpeed', 1500), ...
    'fitOptions', struct('useStandardErrorWeights', false, ...
        'optimizerOptions', optimset('Display', 'off', 'MaxIter', 8, 'MaxFunEvals', 18, 'TolX', 1e-5)));

etaSOutput = guiFitMRLFESolver(etaSRequest);
assert(isfield(etaSOutput, 'routePolicy'), 'mRLFE fit output must expose routePolicy metadata.');
assert(etaSOutput.routePolicy.requestDirectViscoAtlas == true, 'A0Like etaS fitting should request direct atlas.');
assert(etaSOutput.routePolicy.expectedPath == "direct_viscous_atlas", 'Unexpected expected path for A0Like etaS fitting.');
assert(etaSOutput.routePolicy.actualPath == "direct_viscous_atlas", 'A0Like etaS fitting did not use the direct atlas path.');

muRequest = guiBuildFitRequest("mrlfe", ...
    'branchName', "A0Like", ...
    'mode', "basic", ...
    'experimental', experimental, ...
    'fixedParams', struct('thickness', params.thickness, 'rho', params.rho, 'nu', params.nu), ...
    'freeParams', "mu", ...
    'initialGuess', struct('mu', params.mu), ...
    'bounds', struct('mu', [20e3, 160e3]), ...
    'controls', struct('robustness', "Fast", 'etaS', params.etaS, 'fluidDensity', 1000, 'fluidSoundSpeed', 1500), ...
    'fitOptions', struct('useStandardErrorWeights', false, ...
        'optimizerOptions', optimset('Display', 'off', 'MaxIter', 8, 'MaxFunEvals', 18, 'TolX', 1e-5)));

muOutput = guiFitMRLFESolver(muRequest);
assert(isfield(muOutput, 'routePolicy'), 'mRLFE fit output must expose routePolicy metadata.');
assert(muOutput.routePolicy.requestDirectViscoAtlas == false, 'A0Like mu fitting should not request direct atlas by adapter policy.');
assert(muOutput.routePolicy.expectedPath == "maintained_rl_mrlfe_workflow", 'Unexpected expected path for A0Like mu fitting.');

s0Request = guiBuildFitRequest("mrlfe", ...
    'branchName', "S0Like", ...
    'mode', "basic", ...
    'experimental', experimental, ...
    'fixedParams', struct('mu', params.mu, 'thickness', params.thickness, 'rho', params.rho, 'nu', params.nu), ...
    'freeParams', "etaS", ...
    'initialGuess', struct('etaS', params.etaS), ...
    'bounds', struct('etaS', [0.0, 0.30]), ...
    'controls', struct('robustness', "Fast", 'etaS', params.etaS, 'fluidDensity', 1000, 'fluidSoundSpeed', 1500), ...
    'fitOptions', struct('useStandardErrorWeights', false, ...
        'optimizerOptions', optimset('Display', 'off', 'MaxIter', 4, 'MaxFunEvals', 8, 'TolX', 1e-5)));

s0Output = guiFitMRLFESolver(s0Request);
assert(s0Output.routePolicy.requestDirectViscoAtlas == false, 'S0Like etaS fitting should not request direct atlas by adapter policy.');
assert(s0Output.routePolicy.expectedPath == "maintained_rl_mrlfe_workflow", 'Unexpected expected path for S0Like etaS fitting.');

fprintf('A0Like etaS route: expected %s | actual %s\n', etaSOutput.routePolicy.expectedPath, etaSOutput.routePolicy.actualPath);
fprintf('A0Like mu route:   expected %s | actual %s\n', muOutput.routePolicy.expectedPath, muOutput.routePolicy.actualPath);
fprintf('S0Like etaS route: expected %s | actual %s\n', s0Output.routePolicy.expectedPath, s0Output.routePolicy.actualPath);
fprintf('\nGUI mRLFE fit route policy contract test passed.\n');
