clear; clc;
startup

fprintf('\nRunning FitTool requested-curve model coverage test...\n');
fprintf('-----------------------------------------------------\n');

%% Rayleigh-Lamb requested curve.
rlParams = rlDefaultParams();
rlFrequency_Hz = linspace(1000, 7000, 6).';
rlCp_mps = rlEvaluateFitModel(rlParams, rlFrequency_Hz, "A0", rlDefaultOptions("Fast"));
rlOutput = runCase("rayleigh_lamb", "A0", rlFrequency_Hz, rlCp_mps, ...
    struct('thickness', rlParams.thickness, 'rho', rlParams.rho, 'nu', rlParams.nu), ...
    "mu", struct('mu', rlParams.mu), struct('mu', [40e3, 140e3]), ...
    struct('executionProfile', "Fast"), ...
    struct('useStandardErrorWeights', false, ...
        'optimizerOptions', optimset('Display', 'off', 'MaxIter', 6, 'MaxFunEvals', 16, 'TolX', 1e-4)));
assertRequestedCurve(rlOutput, "rayleigh_lamb", "A0");

%% mRLFE requested curve.
mrlfeParams = mrlfeDefaultSweepParams();
mrlfeFrequency_Hz = linspace(1000, 7000, 5).';
mrlfeOptions = mrlfeDefaultSweepOptions("A0Like", 'EtaS', 0.0);
mrlfeCp_mps = mrlfeEvaluateFitModel(mrlfeParams, mrlfeFrequency_Hz, "A0Like", mrlfeOptions);
mrlfeControls = struct('executionProfile', "Fast", ...
    'etaS', 0.0, ...
    'fluidDensity', 1000, ...
    'fluidSoundSpeed', 1500, ...
    'mrlfeA0Policy', "physicalTail");
mrlfeOutput = runCase("mrlfe", "A0Like", mrlfeFrequency_Hz, mrlfeCp_mps, ...
    struct('thickness', mrlfeParams.thickness, 'rho', mrlfeParams.rho, 'nu', mrlfeParams.nu), ...
    "mu", struct('mu', mrlfeParams.mu), struct('mu', [40e3, 140e3]), ...
    mrlfeControls, ...
    struct('useStandardErrorWeights', false, ...
        'optimizerOptions', optimset('Display', 'off', 'MaxIter', 6, 'MaxFunEvals', 16, 'TolX', 1e-4)));
assertRequestedCurve(mrlfeOutput, "mrlfe", "A0Like");

%% AE IOP/HGO requested curve.
aeParams = localDefaultAEParams();
aeFrequency_Hz = aeParams.frequency(:);
[aeOptions, ~] = aeResolveExecutionProfile("Fast", 'DefaultProfile', "Fast", 'DefaultSource', "test");
aeOptions.M54_variant = "corrected";
aeOptions.normalizeRows = false;
aeOptions.usePhysicalCpWindow = false;
aeOptions.atlasBranchPolicy = "atlasA0";
aeOptions.atlasInitializationNumFrequencyPoints = 50;
[aeCp_mps, aeRaw] = aeEvaluateFitModel(aeParams, aeFrequency_Hz, "atlasA0", aeOptions);
assert(isequal(fieldnames(aeRaw), {'modelFamily'; 'modelName'; 'branchName'; ...
    'frequency_Hz'; 'Cp_mps'; 'validMask'; 'solverResult'; 'params'; ...
    'options'}), 'AE fitting evaluator raw-result schema changed.');
valid = aeRaw.validMask(:) & isfinite(aeCp_mps(:));
aeFrequency_Hz = aeFrequency_Hz(valid);
aeCp_mps = aeCp_mps(valid);
aeOutput = runCase("acoustoelastic_iop_hgo", "atlasA0", aeFrequency_Hz, aeCp_mps, ...
    struct('thickness', aeParams.thickness, 'IOP', aeParams.IOP, 'R', aeParams.R, ...
        'k1', aeParams.k1, 'k2', aeParams.k2, 'rho', aeParams.rho, ...
        'rhoF', aeParams.rhoF, 'fluidBulkModulus', aeParams.fluidBulkModulus), ...
    "mu", struct('mu', aeParams.mu), struct('mu', [20e3, 160e3]), ...
    struct('executionProfile', "Fast", 'atlasInitializationNumFrequencyPoints', 50), ...
    struct('useStandardErrorWeights', false, ...
        'optimizerOptions', optimset('Display', 'off', 'MaxIter', 4, 'MaxFunEvals', 12, 'TolX', 1e-3)));
assertRequestedCurve(aeOutput, "acoustoelastic_iop_hgo", "atlasA0");
assert(isequal(fieldnames(aeOutput), {'request'; 'modelFamily'; 'modelName'; ...
    'branchName'; 'fitResult'; 'normalized'; 'executionProfile'; ...
    'fitElapsedSeconds'; 'requestedCurve'}), 'AE FitTool model-result schema changed.');

fprintf('\nFitTool requested-curve model coverage test passed.\n');

function fitOutput = runCase(modelFamily, branchName, frequency_Hz, Cp_mps, fixedParams, freeParam, initialGuess, bounds, controls, fitOptions)
experimental = struct('frequency_Hz', frequency_Hz(:), ...
    'Cp_mps', Cp_mps(:), ...
    'validMask', true(size(frequency_Hz(:))));
request = guiBuildFitRequest(modelFamily, ...
    'branchName', branchName, ...
    'experimental', experimental, ...
    'fixedParams', fixedParams, ...
    'freeParams', freeParam, ...
    'initialGuess', initialGuess, ...
    'bounds', bounds, ...
    'controls', controls, ...
    'fitOptions', fitOptions);
fitOutput = guiRunFit(request);
requestedFrequency_Hz = linspace(min(frequency_Hz), max(frequency_Hz), 18).';
fitOutput.requestedCurve = guiEvaluateRequestedFitCurve(fitOutput, requestedFrequency_Hz);
fitOutput.normalized.requestedCurve = fitOutput.requestedCurve;
end

function assertRequestedCurve(fitOutput, modelFamily, branchName)
assert(isfield(fitOutput.normalized, 'parameterSummaryTable'), ...
    'Normalized output must include parameterSummaryTable.');
assert(isfield(fitOutput.normalized, 'fitQualitySummaryTable'), ...
    'Normalized output must include fitQualitySummaryTable.');
assert(height(fitOutput.normalized.fitQualitySummaryTable) == 1, ...
    'Fit quality summary should have one global row.');
assert(fitOutput.requestedCurve.modelFamily == modelFamily, ...
    'Requested curve model family mismatch.');
assert(fitOutput.requestedCurve.branchName == branchName, ...
    'Requested curve branch mismatch.');
assert(numel(fitOutput.requestedCurve.frequency_Hz) == 18, ...
    'Requested curve must use the requested evaluation grid.');
assert(any(fitOutput.requestedCurve.validMask), ...
    'Requested curve must contain at least one valid point.');
assert(isfinite(fitOutput.requestedCurve.elapsedSeconds), ...
    'Requested curve must record elapsed time.');
assert(isfield(fitOutput.requestedCurve, 'executionProfile'), ...
    'Requested curve must preserve execution profile metadata.');
end

function params = localDefaultAEParams()
params = struct();
params.R = 7.8e-3;
params.thickness = 550e-6;
params.mu = 64e3;
params.k1 = 50e3;
params.k2 = 200;
params.rho = 1060;
params.rhoF = 1000;
params.fluidBulkModulus = 2.2e9;
params.IOP = 15 * 133.322;
params.frequency = logspace(log10(300), log10(15e3), 20);
end
