function ownership = buildTestOwnership(varargin)
%BUILDTESTOWNERSHIP Build and optionally validate canonical test ownership.
%
% ownership = buildTestOwnership()
% ownership = buildTestOwnership('WriteCsv', true)
% ownership = buildTestOwnership('ValidateActual', true)
%
% The proposed-owner rules are intentionally independent of runner nesting.
% This lets the same function describe a design before runner edits and then
% verify the implemented graph after the edits.  Reachability columns always
% describe the graph currently parsed by buildTestInventory.

parser = inputParser;
parser.addParameter('WriteCsv', false, @(x) islogical(x) && isscalar(x));
parser.addParameter('ValidateActual', false, @(x) islogical(x) && isscalar(x));
parser.parse(varargin{:});
options = parser.Results;

thisFile = mfilename('fullpath');
inventoryFolder = fileparts(thisFile);
[inventory, edges] = buildTestInventory();

tests = inventory(inventory.FileType == "test", :);
tests = sortrows(tests, 'Path');
runnerRows = inventory(inventory.FileType == "runner", :);
runnerPaths = string(runnerRows.Path);

runtimePath = fullfile(inventoryFolder, 'test_runtime_measurements.csv');
runtime = table();
if isfile(runtimePath)
    runtime = readtable(runtimePath, 'TextType', 'string');
end

testCount = height(tests);
canonicalRunner = strings(testCount, 1);
runtimeTier = strings(testCount, 1);
manualOnly = false(testCount, 1);
measuredSeconds = nan(testCount, 1);
evidence = strings(testCount, 1);
notes = strings(testCount, 1);

for i = 1:testCount
    entrypoint = string(tests.Entrypoint(i));
    [canonicalRunner(i), manualOnly(i), notes(i)] = proposedOwner(entrypoint, edges);
    runtimeTier(i) = tierForOwner(canonicalRunner(i), manualOnly(i));
    if ~isempty(runtime)
        match = find(runtime.Entrypoint == entrypoint, 1, 'last');
        if ~isempty(match)
            measuredSeconds(i) = runtime.ElapsedSecondsMedian(match);
        end
    end
    if manualOnly(i)
        evidence(i) = "documented manual registry; no normal runner execution";
    elseif isnan(measuredSeconds(i))
        evidence(i) = "static ownership design; runtime unmeasured";
    else
        evidence(i) = "static ownership design; measured child runtime available";
    end
end

runnerReach = buildRunnerReachability(runnerPaths, edges);
additionalRunners = strings(testCount, 1);
for i = 1:testCount
    reachedBy = strings(0, 1);
    for j = 1:numel(runnerPaths)
        if any(runnerReach{j} == string(tests.Path(i)))
            runnerName = runnerEntrypoint(runnerPaths(j), runnerRows);
            if runnerName ~= canonicalRunner(i)
                reachedBy(end + 1, 1) = runnerName; %#ok<AGROW>
            end
        end
    end
    additionalRunners(i) = strjoin(sort(unique(reachedBy)), ';');
end

ownership = table( ...
    string(tests.Path), string(tests.Entrypoint), string(tests.Category), ...
    runtimeTier, canonicalRunner, additionalRunners, manualOnly, ...
    reachableFrom("run_quick_contract_tests", tests.Path, runnerRows, runnerReach), ...
    reachableFrom("run_quick_smoke_tests", tests.Path, runnerRows, runnerReach), ...
    reachableFrom("run_numerical_regression_tests", tests.Path, runnerRows, runnerReach), ...
    reachableFrom("run_extended_integration_tests", tests.Path, runnerRows, runnerReach), ...
    reachableFrom("run_all_smoke_tests", tests.Path, runnerRows, runnerReach), ...
    measuredSeconds, evidence, notes, ...
    'VariableNames', { ...
    'TestPath', 'Entrypoint', 'Category', 'RuntimeTier', 'CanonicalRunner', ...
    'AdditionalAggregateRunners', 'ManualOnly', ...
    'ReachableFromQuickContracts', 'ReachableFromQuickSmoke', ...
    'ReachableFromNumericalRegression', 'ReachableFromExtendedIntegration', ...
    'ReachableFromHistoricalAllSmoke', 'MeasuredSeconds', 'Evidence', 'Notes'});

if options.ValidateActual
    validateActualOwnership(ownership, edges);
end

if options.WriteCsv
    writetable(ownership, fullfile(inventoryFolder, 'test_runner_ownership.csv'));
end
end

function [owner, manualOnly, notes] = proposedOwner(entrypoint, edges)
manualOnly = false;
notes = "";

groups = ownershipGroups();
for i = 1:numel(groups)
    if any(groups(i).Tests == entrypoint)
        owner = groups(i).Runner;
        return;
    end
end

testEdges = edges(edges.EdgeType == "runner_to_test" & ...
    edges.CalleeEntrypoint == entrypoint & edges.DirectOrDynamic ~= "reference_only", :);
callers = unique(string(testEdges.CallerEntrypoint));
if numel(callers) ~= 1
    error('buildTestOwnership:AmbiguousBaselineOwner', ...
        'No explicit ownership rule and %d executable direct runners for %s.', ...
        numel(callers), entrypoint);
end
owner = callers(1);
end

function groups = ownershipGroups()
groups = struct('Runner', {}, 'Tests', {});
groups(end + 1) = group("run_core_contract_tests", [ ...
    "test_startup_path_policy", "test_repository_root_utilities", ...
    "test_model_output_folder_helpers", "test_fitting_helpers_smoke"]);
groups(end + 1) = group("run_core_numerical_regression_tests", [ ...
    "test_lightweight_numerical_regression", "test_rl_fit_synthetic_A0", ...
    "test_mrlfe_fit_synthetic_A0Like"]);
groups(end + 1) = group("run_gui_quick_tests", [ ...
    "test_gui_struct_helpers_contract", "test_fit_parameter_state_contract", ...
    "test_fit_parameter_execution_contract", "test_gui_normalized_adapters_smoke", ...
    "test_gui_sweep_adapters_smoke", "test_gui_sweep_registry_smoke", ...
    "test_gui_acoustoelastic_iop_hgo_sweep_adapter_smoke", ...
    "test_gui_acoustoelastic_iop_hgo_main_adapter_smoke", ...
    "test_gui_fit_registry_contract", "test_fit_tool_model_registry_contract"]);
groups(end + 1) = group("run_gui_extended_tests", [ ...
    "test_gui_mrlfe_fixed_etaS_fit_contract", ...
    "test_gui_mrlfe_fit_route_policy_contract", ...
    "test_gui_mrlfe_fit_full_curve_fast_contract"]);
groups(end + 1) = group("run_gui_execution_profile_tests", [ ...
    "test_execution_profile_current_contract", ...
    "test_execution_profile_surface_integration"]);
groups(end + 1) = group("run_execution_profile_contract_tests", [ ...
    "test_gui_execution_profile_normalization", ...
    "test_model_execution_profile_resolvers", ...
    "test_execution_profile_normalization_contract", ...
    "test_execution_profile_surface_metadata", ...
    "test_execution_profile_state_transition_contract"]);
groups(end + 1) = group("run_execution_profile_integration_tests", [ ...
    "test_execution_profile_fit_curve_metadata", ...
    "test_execution_profile_validation_matrix"]);
groups(end + 1) = group("run_execution_profile_diagnostics_tests", [ ...
    "test_execution_profile_diagnostics_format", ...
    "test_mrlfe_execution_profile_benchmark_contract"]);
groups(end + 1) = group("run_ae_quick_tests", [ ...
    "test_acoustoelastic_iop_hgo_branch_policy_validation", ...
    "test_ae_analyze_truncation_recovery", ...
    "test_acoustoelastic_iop_hgo_branch_persistence_refinement", ...
    "test_acoustoelastic_iop_hgo_constitutive_identity", ...
    "test_ae_physical_sweep_examples_contract", ...
    "test_sweep_plot_renderer_contract", ...
    "test_acoustoelastic_iop_hgo_identityA0_diagnostic_policy", ...
    "test_acoustoelastic_iop_hgo_short_entrypoints"]);
groups(end + 1) = group("run_ae_extended_tests", [ ...
    "test_acoustoelastic_iop_hgo_fallback_invalidation", ...
    "test_acoustoelastic_iop_hgo_internal_tracking_grid", ...
    "test_acoustoelastic_iop_hgo_atlasA0_smoke", ...
    "test_ae_fit_synthetic_atlasA0"]);
groups(end + 1) = group("run_mrlfe_production_core_contract_tests", [ ...
    "test_mrlfe_production_core_contract", ...
    "test_mrlfe_numerical_preset_grids", ...
    "test_mrlfe_solve_frequency_override", ...
    "test_mrlfe_robust_start_contract", ...
    "test_mrlfe_termination_policy"]);
groups(end + 1) = group("run_mrlfe_production_core_extended_tests", [ ...
    "test_mrlfe_production_core_presets", ...
    "test_mrlfe_production_core_characterization"]);
groups(end + 1) = group("run_mrlfe_production_core_performance_tests", ...
    "test_mrlfe_production_core_performance");
groups(end + 1) = group("run_mrlfe_fitting_regression_tests", [ ...
    "test_mrlfe_etaS_fit_forward_cache", ...
    "test_mrlfe_fit_fast_options_quality"]);
groups(end + 1) = group("run_numerical_regression_tests", ...
    "test_rl_fit_evaluator_branch_consistency");
groups(end + 1) = group("run_performance_and_benchmark_tests", ...
    "test_mrlfe_fit_grid_policy_performance");
groups(end + 1) = group("run_mrlfe_public_api_contract_tests", [ ...
    "test_mrlfe_public_contract_defaults", ...
    "test_mrlfe_public_contract_validation"]);
groups(end + 1) = group("run_mrlfe_public_result_contract_tests", ...
    "test_mrlfe_public_contract_result_schema");
groups(end + 1) = group("run_mrlfe_public_contract_tests", ...
    "test_mrlfe_public_contract_characterization");
groups(end + 1) = group("run_fit_data_import_tests", [ ...
    "test_gui_read_experimental_fit_file", ...
    "test_gui_prepare_experimental_fit_data"]);
groups(end + 1) = group("run_fit_tool_interaction_contract_tests", ...
    "test_fit_tool_interaction_helpers");
groups(end + 1) = group("run_fit_tool_requested_curve_tests", ...
    "test_fit_tool_requested_curve_models");
groups(end + 1) = group("run_main_gui_export_tests", ...
    "test_main_gui_export_contract");
end

function value = group(runner, tests)
value = struct('Runner', string(runner), 'Tests', string(tests));
end

function tier = tierForOwner(owner, manualOnly)
if manualOnly
    tier = "manual_deferred";
    return;
end
if any(owner == ["run_core_contract_tests", "run_execution_profile_contract_tests", ...
        "run_fit_data_import_tests", "run_fit_tool_interaction_contract_tests", ...
        "run_main_gui_export_tests", "run_mrlfe_public_api_contract_tests"])
    tier = "quick_contract";
elseif any(owner == ["run_gui_quick_tests", "run_ae_quick_tests", ...
        "run_mrlfe_smoke_tests"])
    tier = "quick_smoke";
elseif any(owner == ["run_core_numerical_regression_tests", ...
        "run_ae_extended_tests", ...
        "run_numerical_regression_tests", ...
        "run_mrlfe_production_core_contract_tests", ...
        "run_mrlfe_public_result_contract_tests"])
    tier = "numerical_regression";
elseif contains(owner, "performance") || owner == "run_performance_and_benchmark_tests"
    tier = "performance";
elseif contains(owner, "diagnostics")
    tier = "diagnostic";
elseif any(owner == ["run_mrlfe_public_contract_tests", ...
        "run_mrlfe_route_integrity_tests", ...
        "run_mrlfe_fit_public_solver_tests", ...
        "run_mrlfe_main_gui_public_solver_tests", ...
        "run_mrlfe_sweeptool_public_solver_tests", ...
        "run_mrlfe_neutral_production_helper_tests", ...
        "run_mrlfe_production_core_extended_tests"])
    tier = "characterization";
else
    tier = "extended_integration";
end
end

function runnerReach = buildRunnerReachability(runnerPaths, edges)
runnerReach = cell(numel(runnerPaths), 1);
for i = 1:numel(runnerPaths)
    pending = runnerPaths(i);
    visited = strings(0, 1);
    reachedTests = strings(0, 1);
    while ~isempty(pending)
        current = pending(1);
        pending(1) = [];
        if any(visited == current)
            continue;
        end
        visited(end + 1, 1) = current; %#ok<AGROW>
        outgoing = edges(edges.CallerPath == current & ...
            edges.DirectOrDynamic ~= "reference_only", :);
        reachedTests = [reachedTests; string(outgoing.CalleePath( ...
            outgoing.EdgeType == "runner_to_test"))]; %#ok<AGROW>
        nested = string(outgoing.CalleePath(outgoing.EdgeType == "runner_to_runner"));
        pending = [pending(:); nested(:)];
    end
    runnerReach{i} = sort(unique(reachedTests));
end
end

function result = reachableFrom(entrypoint, testPaths, runnerRows, runnerReach)
match = find(string(runnerRows.Entrypoint) == entrypoint & ...
    startsWith(string(runnerRows.Path), "tests/runners/"), 1);
result = false(height(testPaths), 1);
if isempty(match)
    return;
end
result = ismember(string(testPaths), runnerReach{match});
end

function name = runnerEntrypoint(path, runnerRows)
match = find(string(runnerRows.Path) == path, 1);
name = string(runnerRows.Entrypoint(match));
end

function validateActualOwnership(ownership, edges)
for i = 1:height(ownership)
    testName = ownership.Entrypoint(i);
    direct = edges(edges.EdgeType == "runner_to_test" & ...
        edges.CalleeEntrypoint == testName & ...
        edges.DirectOrDynamic ~= "reference_only", :);
    directOwners = unique(string(direct.CallerEntrypoint));
    if ownership.ManualOnly(i)
        assert(isempty(directOwners), ...
            'Manual-only test unexpectedly has a direct runner: %s', testName);
    else
        assert(isscalar(directOwners), ...
            'Expected exactly one direct runner for %s; found %d.', ...
            testName, numel(directOwners));
        assert(directOwners == ownership.CanonicalRunner(i), ...
            'Implemented direct owner for %s is %s, expected %s.', ...
            testName, directOwners, ownership.CanonicalRunner(i));
    end
end
end
