function plan = runtime_measurement_plan()
%RUNTIME_MEASUREMENT_PLAN Return the staged runtime evidence plan.

Group = [ ...
    repmat("priority_quick_candidates", 4, 1); ...
    repmat("unregistered_tests", 6, 1); ...
    repmat("likely_extended_tests", 10, 1); ...
    repmat("extended_diagnostics", 2, 1); ...
    repmat("runners_for_sampling", 5, 1)];
Entrypoint = [ ...
    "test_gui_execution_profile_normalization"; ...
    "test_model_execution_profile_resolvers"; ...
    "test_execution_profile_current_contract"; ...
    "test_lightweight_numerical_regression"; ...
    "test_mrlfe_fit_grid_policy_performance"; ...
    "test_acoustoelastic_iop_hgo_identityA0_diagnostic_policy"; ...
    "test_acoustoelastic_iop_hgo_short_entrypoints"; ...
    "test_mrlfe_etaS_fit_forward_cache"; ...
    "test_mrlfe_fit_fast_options_quality"; ...
    "test_rl_fit_evaluator_branch_consistency"; ...
    "test_execution_profile_surface_integration"; ...
    "test_execution_profile_fit_curve_metadata"; ...
    "test_rl_fit_synthetic_A0"; ...
    "test_mrlfe_fit_synthetic_A0Like"; ...
    "test_ae_fit_synthetic_atlasA0"; ...
    "test_mrlfe_public_contract_characterization"; ...
    "test_mrlfe_production_core_characterization"; ...
    "test_mrlfe_production_core_performance"; ...
    "test_mrlfe_main_gui_characterization"; ...
    "test_mrlfe_sweep_point_characterization"; ...
    "test_execution_profile_validation_matrix"; ...
    "test_mrlfe_execution_profile_benchmark_contract"; ...
    "run_core_smoke_tests"; ...
    "run_gui_smoke_tests"; ...
    "run_acoustoelastic_smoke_tests"; ...
    "run_mrlfe_production_core_tests"; ...
    "run_fit_validation_tests"];
EntryType = [repmat("test", 22, 1); repmat("runner", 5, 1)];
RepeatCount = [repmat(2, 3, 1); ones(19, 1); ones(5, 1)];
Automatic = [true(22, 1); false(5, 1)];
EvidencePolicy = [ ...
    repmat("measure in phase 1", 20, 1); ...
    "run the 36-case direct-profile matrix in focused extended validation"; ...
    "run the bounded direct-profile benchmark contract through diagnostics"; ...
    repmat("sample only after individual membership costs are understood", 5, 1)];

plan = table(Group, Entrypoint, EntryType, RepeatCount, Automatic, EvidencePolicy);
plan = sortrows(plan, {'Group', 'Entrypoint'});
end
