function policy = mrlfeDefaultFitGridPolicy()
%MRLFEDEFAULTFITGRIDPOLICY Return the maintained optimized fit-grid policy.

policy = struct( ...
    'gridPolicy', "fitOptimized", ...
    'minimumPointCount', 12, ...
    'maximumPointCount', 40, ...
    'maximumStep_Hz', 250);
end
