clear; clc;
if isempty(which('mrlfeSolve'))
    startup
end

%TEST_MRLFE_MAINTAINED_ENTRYPOINTS_NAMING Guard maintained mRLFE naming surface.
%
% The maintained mRLFE execution surface should expose physical/model names.

repoRoot = testRepositoryRoot(mfilename('fullpath'));
forbiddenToken = char([72 97 110]);
forbiddenModelName = char([109 82 76 70 69 72 97 110 86 105 115 99 111 82 101 97 108 75]);

entrypointsPath = fullfile(repoRoot, 'docs', 'repository', 'maintained_entrypoints.md');
entrypointsText = fileread(entrypointsPath);
sectionStart = strfind(entrypointsText, '## mRLFE model');
sectionEnd = strfind(entrypointsText, '## Smoke-test scope');
assert(~isempty(sectionStart) && ~isempty(sectionEnd), ...
    'maintained_entrypoints.md must contain mRLFE and smoke-test sections.');

mrlfeSection = entrypointsText(sectionStart(1):sectionEnd(1)-1);
assert(~contains(mrlfeSection, forbiddenToken), ...
    'Maintained mRLFE section should not contain author-labeled names.');
assert(contains(mrlfeSection, 'mRLFEViscoRealK'), ...
    'Maintained mRLFE section should document the normalized viscous real-k model name.');
assert(contains(mrlfeSection, 'mrlfeSetYoungModulusForShearPoisson'), ...
    'Maintained mRLFE section should list mrlfeSetYoungModulusForShearPoisson.');
assert(contains(mrlfeSection, 'mrlfeSelectRealKBranches'), ...
    'Maintained mRLFE section should list mrlfeSelectRealKBranches.');
assert(contains(mrlfeSection, 'summarizeMRLFETrackingQuality'), ...
    'Maintained mRLFE section should list summarizeMRLFETrackingQuality.');
assert(contains(mrlfeSection, 'compareMRLFETrackingStrategies'), ...
    'Maintained mRLFE section should list compareMRLFETrackingStrategies.');
assert(contains(mrlfeSection, 'diagnose_mrlfe_fit_performance'), ...
    'Maintained mRLFE section should list the consolidated fit-performance diagnostic.');
assert(~contains(mrlfeSection, 'stress_test_mrlfe_real_k_range'), ...
    'Maintained mRLFE section should not list archived range diagnostics.');
assert(~contains(mrlfeSection, 'solveMRLFEAtlasUnified'), ...
    'Maintained mRLFE section should not list removed legacy solvers.');
assert(contains(mrlfeSection, 'mrlfeTrackBranchAdaptive'), ...
    'Maintained mRLFE section should list mrlfeTrackBranchAdaptive.');
assert(contains(mrlfeSection, 'mrlfeA0Policy'), ...
    'Maintained mRLFE section should document the high-level A0 policy selector.');
assert(~contains(mrlfeSection, 'diagnose_mrlfe_atlas_primary_policy_matrix'), ...
    'Maintained mRLFE section should not list the removed atlas primary policy diagnostic.');
assert(~contains(mrlfeSection, 'diagnose_mrlfe_a0_policy_parametric_sweep'), ...
    'Maintained mRLFE section should not list deleted atlas policy diagnostics.');
assert(~contains(mrlfeSection, 'run_mrlfe_atlas_tests'), ...
    'Maintained mRLFE section should not list removed atlas test runner.');
assert(~contains(entrypointsText, 'run_mrlfe_fit_atlas_tests'), ...
    'maintained_entrypoints.md should not list removed FitTool atlas test runner.');

newSweepEntrypoints = [ ...
    "mrlfe_sweep_mu_A0Like", ...
    "mrlfe_sweep_mu_S0Like", ...
    "mrlfe_sweep_etaS_A0Like", ...
    "mrlfe_sweep_etaS_S0Like", ...
    "mrlfe_sweep_thickness_A0Like", ...
    "mrlfe_sweep_thickness_S0Like" ...
    ];
for i = 1:numel(newSweepEntrypoints)
    assert(~isempty(which(newSweepEntrypoints(i))), ...
        'Missing maintained mRLFE sweep entrypoint: %s.', newSweepEntrypoints(i));
    assert(contains(mrlfeSection, newSweepEntrypoints(i)), ...
        'maintained_entrypoints.md is missing mRLFE sweep entrypoint: %s.', newSweepEntrypoints(i));
end

oldSweepEntrypoints = [ ...
    "sweep_mu_A0Like_viscoelastic", ...
    "sweep_mu_S0Like_viscoelastic", ...
    "sweep_etaS_A0Like_viscoelastic", ...
    "sweep_etaS_S0Like_viscoelastic", ...
    "sweep_thickness_A0Like_viscoelastic", ...
    "sweep_thickness_S0Like_viscoelastic" ...
    ];
for i = 1:numel(oldSweepEntrypoints)
    assert(isempty(which(oldSweepEntrypoints(i))), ...
        'Obsolete mRLFE sweep entrypoint should not resolve on the MATLAB path: %s.', oldSweepEntrypoints(i));
    assert(~contains(mrlfeSection, oldSweepEntrypoints(i)), ...
        'maintained_entrypoints.md should not list obsolete mRLFE sweep entrypoint: %s.', oldSweepEntrypoints(i));
end

readmePath = fullfile(repoRoot, 'README.md');
readmeText = fileread(readmePath);
readmeStart = strfind(readmeText, '## mRLFE solver workflow');
assert(~isempty(readmeStart), 'README.md must contain the mRLFE solver workflow section.');
readmeSection = readmeText(readmeStart(1):end);
assert(~contains(readmeSection, forbiddenToken), ...
    'README mRLFE workflow should not contain author-labeled names.');
assert(contains(readmeSection, 'mRLFEViscoRealK'), ...
    'README mRLFE workflow should document the normalized viscous real-k model name.');
assert(contains(readmeSection, 'compare_mrlfe_elastic_vs_visco_cp'), ...
    'README should list the renamed elastic-vs-visco comparison example.');

renamedExample = fullfile(repoRoot, 'examples', 'mrlfe', 'basic', 'compare_mrlfe_elastic_vs_visco_cp.m');
assert(isfile(renamedExample), 'Renamed mRLFE elastic-vs-visco example is missing.');

fitDiagnostic = fullfile(repoRoot, 'examples', 'mrlfe', 'diagnostics', 'diagnose_mrlfe_fit_performance.m');
assert(isfile(fitDiagnostic), 'Consolidated mRLFE fit-performance diagnostic is missing.');
assert(~isfile(fullfile(repoRoot, 'examples', 'mrlfe', 'diagnostics', 'stress_test_mrlfe_elastic_range.m')), ...
    'Obsolete separate mRLFE elastic range stress test should not exist.');
assert(~isfile(fullfile(repoRoot, 'examples', 'mrlfe', 'diagnostics', 'stress_test_mrlfe_visco_range.m')), ...
    'Obsolete separate mRLFE visco range stress test should not exist.');

atlasDiagnosticReadme = fullfile(repoRoot, 'examples', 'mrlfe', 'diagnostics', 'README.md');
assert(isfile(atlasDiagnosticReadme), 'mRLFE diagnostics README is missing.');

removedDiagnostics = [ ...
    "compare_mrlfe_tracker_vs_condition_peaks", ...
    "diagnose_mrlfe_gui_performance_32kHz", ...
    "diagnose_mrlfe_visco_residual_landscape", ...
    "diagnose_mrlfe_visco_validity_breakdown", ...
    "stress_test_mrlfe_real_k_range", ...
    "diagnose_mrlfe_atlas_primary_policy_matrix" ...
    ];
for i = 1:numel(removedDiagnostics)
    assert(isempty(which(removedDiagnostics(i))), ...
        'Removed mRLFE diagnostic must not resolve on the MATLAB path: %s.', removedDiagnostics(i));
end

maintainedFiles = { ...
    fullfile(repoRoot, 'analysis', 'mrlfe', 'mrlfeModelCandidateNames.m'), ...
    fullfile(repoRoot, 'analysis', 'mrlfe', 'mrlfeSetYoungModulusForShearPoisson.m'), ...
    fullfile(repoRoot, 'analysis', 'mrlfe', 'mrlfeSelectRealKBranches.m'), ...
    fullfile(repoRoot, 'app', 'adapters', 'guiNormalizeRawResult.m'), ...
    fullfile(repoRoot, 'app', 'adapters', 'guiRunMRLFEModel.m'), ...
    fullfile(repoRoot, 'app', 'adapters', 'guiRunMRLFESweep.m'), ...
    fullfile(repoRoot, 'app', 'createModelTabs.m'), ...
    fullfile(repoRoot, 'app', 'createPlotTab.m'), ...
    fullfile(repoRoot, 'models', 'rayleigh_lamb', 'core', 'rlComputeFundamentalLambModes.m'), ...
    fullfile(repoRoot, 'models', 'rayleigh_lamb', 'core', 'rlDefaultOptions.m'), ...
    fullfile(repoRoot, 'models', 'mrlfe', 'api', 'mrlfeSolve.m'), ...
    fullfile(repoRoot, 'models', 'mrlfe', 'tracking', 'mrlfeTrackBranchAdaptive.m'), ...
    fullfile(repoRoot, 'models', 'mrlfe', 'core', 'mrlfeMatrix.m'), ...
    fullfile(repoRoot, 'tests', 'app', 'gui', 'test_gui_normalized_adapters_smoke.m'), ...
    fullfile(repoRoot, 'tests', 'models', 'mrlfe', 'test_mrlfe_model_candidate_names.m'), ...
    fullfile(repoRoot, 'tests', 'models', 'mrlfe', 'test_mrlfe_smoke.m'), ...
    fullfile(repoRoot, 'tests', 'models', 'mrlfe', 'test_mrlfe_etaS_zero_limit.m'), ...
    fullfile(repoRoot, 'tests', 'models', 'mrlfe', 'test_mrlfe_elastic_reference_buffer.m')};
for i = 1:numel(maintainedFiles)
    fileText = fileread(maintainedFiles{i});
    assert(~contains(fileText, forbiddenToken), ...
        'Maintained mRLFE file should not contain author-labeled names: %s', maintainedFiles{i});
end

analysisFiles = { ...
    fullfile(repoRoot, 'analysis', 'plotParametricSweepCp.m'), ...
    fullfile(repoRoot, 'analysis', 'summarizeParametricSweepBranch.m')};
for i = 1:numel(analysisFiles)
    fileText = fileread(analysisFiles{i});
    assert(contains(fileText, 'mRLFEViscoRealK'), ...
        'Maintained analysis helper should document mRLFEViscoRealK: %s', analysisFiles{i});
    assert(~contains(fileText, forbiddenModelName), ...
        'Maintained analysis helper should not contain author-labeled mRLFE model names: %s', analysisFiles{i});
end
