function test_mrlfe_canonical_route_contract()
%TEST_MRLFE_CANONICAL_ROUTE_CONTRACT Verify removal of legacy mRLFE routes.

fprintf('\nRunning mRLFE canonical route contract...\n');
fprintf('--------------------------------------\n');

root = testRepositoryRoot(mfilename('fullpath'));
deletedFunctions = [ ...
    "computeMRLFE", ...
    "solveMRLFEAtlasUnified", ...
    "solveMRLFEViscoBranchAtlas", ...
    "solveMRLFEBranchModalAtlas", ...
    "solveMRLFEBranchDP", ...
    "solveMRLFEBranch", ...
    "mrlfeEvaluateAtlasFitModel", ...
    "mrlfeMakeDirectViscoAtlasBranchOptions", ...
    "mrlfeApplyDelayedViscoModalCut"];

for i = 1:numel(deletedFunctions)
    assert(isempty(which(deletedFunctions(i))), ...
        'Deleted legacy function still resolves on path: %s.', deletedFunctions(i));
end

deletedFiles = string({ ...
    fullfile(root, 'src', '+lamb', '+models', '+mrlfe', '+solvers', 'computeMRLFE.m'), ...
    fullfile(root, 'src', '+lamb', '+models', '+mrlfe', '+solvers', 'solveMRLFEAtlasUnified.m'), ...
    fullfile(root, 'src', '+lamb', '+models', '+mrlfe', '+solvers', 'solveMRLFEViscoBranchAtlas.m'), ...
    fullfile(root, 'src', '+lamb', '+models', '+mrlfe', '+solvers', 'solveMRLFEBranchModalAtlas.m'), ...
    fullfile(root, 'src', '+lamb', '+models', '+mrlfe', '+solvers', 'solveMRLFEBranchDP.m'), ...
    fullfile(root, 'src', '+lamb', '+models', '+mrlfe', '+solvers', 'solveMRLFEBranch.m'), ...
    fullfile(root, 'analysis', 'mrlfe', 'mrlfeEvaluateAtlasFitModel.m')});
for i = 1:numel(deletedFiles)
    assert(~isfile(deletedFiles(i)), 'Deleted legacy file still exists: %s.', deletedFiles(i));
end

fprintf('mRLFE canonical route contract passed.\n');
end
