clear; clc;
if isempty(which('mrlfeSolve'))
    configureTestPath;
end

fprintf('\nRunning mRLFE fast fitting option quality test...\n');
fprintf('------------------------------------------------\n');

branchName = "A0Like";
etaS = 0.0;
params = mrlfeDefaultSweepParams();
params.mu = 75e3;
params.thickness = 0.50e-3;
params.rho = 1070;
params.nu = 0.4999;
params.etaS = etaS;
frequency_Hz = linspace(1000, 8000, 10).';

fastOptions = mrlfeDefaultSweepOptions(branchName, 'EtaS', etaS);
fastOptions.mrlfeNumericalPreset = "fast";
fastOptions.forwardModel = struct( ...
    'gridPolicy', "fitOptimized", ...
    'minimumPointCount', 12, ...
    'maximumPointCount', 40, ...
    'maximumStep_Hz', 250);

[CpFast_mps, rawFast] = mrlfeEvaluateFitModel(params, frequency_Hz, branchName, fastOptions);
request = mrlfeBuildSolveRequest(params, frequency_Hz, branchName, fastOptions);
request.numerics.frequencySolveOverride_Hz = rawFast.frequencySolve_Hz;
directSameFitGrid = mrlfeSolve(request);

validSameFitGrid = rawFast.validMask(:) & directSameFitGrid.validMask(:) & ...
    isfinite(CpFast_mps(:)) & isfinite(directSameFitGrid.phaseVelocity_mps(:));
assert(any(validSameFitGrid), ...
    'Public and direct fit-optimized routes must share valid requested frequencies.');

sameFitGridDiff_mps = CpFast_mps(validSameFitGrid) - ...
    directSameFitGrid.phaseVelocity_mps(validSameFitGrid);
sameFitGridRmse_mps = sqrt(mean(sameFitGridDiff_mps.^2));
sameFitGridMaxAbs_mps = max(abs(sameFitGridDiff_mps));
sameFitGridMaxRel = max(abs(sameFitGridDiff_mps) ./ ...
    max(abs(directSameFitGrid.phaseVelocity_mps(validSameFitGrid)), eps));

numericalPresetOptions = fastOptions;
numericalPresetOptions.forwardModel = struct('gridPolicy', "numericalPreset");
[CpNumericalPreset_mps, rawNumericalPreset] = mrlfeEvaluateFitModel( ...
    params, frequency_Hz, branchName, numericalPresetOptions);
directNumericalPresetRequest = mrlfeBuildSolveRequest( ...
    params, frequency_Hz, branchName, numericalPresetOptions);
directNumericalPreset = mrlfeSolve(directNumericalPresetRequest);
validNumericalPreset = rawNumericalPreset.validMask(:) & ...
    directNumericalPreset.validMask(:) & isfinite(CpNumericalPreset_mps(:)) & ...
    isfinite(directNumericalPreset.phaseVelocity_mps(:));
assert(any(validNumericalPreset), ...
    'Public and direct numerical-preset routes must share valid requested frequencies.');
numericalPresetDiff_mps = CpNumericalPreset_mps(validNumericalPreset) - ...
    directNumericalPreset.phaseVelocity_mps(validNumericalPreset);

crossPolicyValid = rawFast.validMask(:) & rawNumericalPreset.validMask(:) & ...
    isfinite(CpFast_mps(:)) & isfinite(CpNumericalPreset_mps(:));
assert(any(crossPolicyValid), ...
    'Fit-optimized and numerical-preset routes must share valid requested frequencies.');
crossPolicyDiff_mps = CpFast_mps(crossPolicyValid) - ...
    CpNumericalPreset_mps(crossPolicyValid);
crossPolicyRmse_mps = sqrt(mean(crossPolicyDiff_mps.^2));
crossPolicyMaxAbs_mps = max(abs(crossPolicyDiff_mps));
crossPolicyMaxRel = max(abs(crossPolicyDiff_mps) ./ ...
    max(abs(CpNumericalPreset_mps(crossPolicyValid)), eps));

assert(isfield(rawFast, 'fitPerformanceDefaults'), 'Fast mRLFE fitting evaluation must report fit performance defaults.');
assert(rawFast.evaluationPath.usedPublicSolver == true, ...
    'mRLFE fitting evaluation should use the public solver route.');
assert(rawFast.fitGrid.gridPolicy == "fitOptimized", ...
    'Repeated mRLFE fitting evaluations must disclose fitOptimized grid policy.');
assert(rawNumericalPreset.fitGrid.gridPolicy == "numericalPreset", ...
    'Requested-curve evaluations must disclose numericalPreset grid policy.');
assert(all(ismember(frequency_Hz, rawFast.frequencySolve_Hz)), ...
    'The fit-optimized solve grid must preserve every requested frequency.');
assert(numel(rawFast.frequencySolve_Hz) <= fastOptions.forwardModel.maximumPointCount, ...
    'The fit-optimized solve grid must respect its configured point bound.');
assert(rawFast.modelResult.execution.requestedPreset == "fast", ...
    'mRLFE fitting evaluation should request the public fast preset.');
assert(rawFast.modelResult.execution.effectivePreset == "fast", ...
    'mRLFE fitting evaluation should use the public fast preset.');
assert(rawFast.fitPerformanceDefaults.preset == "fast", ...
    'Fast mRLFE fitting should report the public fast preset.');
assert(rawFast.fitPerformanceDefaults.internalFitAtlasPreset == "fast", ...
    'Fast mRLFE fitting should report the neutral internal preset.');
assert(rawFast.fitPerformanceDefaults.atlasCpScanPoints == 100, ...
    'Public fast mRLFE fitting should use 100 coarse Cp scan points.');
assert(rawFast.fitPerformanceDefaults.rescueCpScanPoints == 260, ...
    'Public fast mRLFE fitting should use 260 Cp scan points for dense rescue.');
assert(rawFast.fitPerformanceDefaults.a0DpCandidates == 5, ...
    'Public fast mRLFE fitting should use five candidates.');
assert(rawFast.modelResult.fallback.policy == "none" && ...
    ~rawFast.modelResult.fallback.applied, ...
    'Public fast fitting must not apply fallback.');
assert(rawFast.modelResult.quality.validCount == nnz(rawFast.validMask) && ...
    rawFast.modelResult.quality.pointCount == numel(rawFast.validMask), ...
    'Public fast fitting quality counts must describe the returned requested-grid mask.');
assert(rawFast.evaluationPath.quality.accepted == rawFast.modelResult.quality.accepted && ...
    rawFast.evaluationPath.quality.reason == rawFast.modelResult.quality.reason, ...
    'Fitting metadata must report the public result quality without reinterpretation.');

% These are adapter-equivalence checks: both sides use the same request and
% internal grid. The 1e-12 m/s tolerance allows only floating-point noise;
% the observed same-grid error on MATLAB R2024b is exactly zero.
sameGridTolerance_mps = 1e-12;
sameGridRelativeTolerance = 1e-12;
assert(sameFitGridRmse_mps <= sameGridTolerance_mps, ...
    'Public fit-optimized Cp RMSE differs from an equivalent direct solve.');
assert(sameFitGridMaxAbs_mps <= sameGridTolerance_mps, ...
    'Public fit-optimized maximum Cp difference differs from an equivalent direct solve.');
assert(sameFitGridMaxRel <= sameGridRelativeTolerance, ...
    'Public fit-optimized relative Cp difference differs from an equivalent direct solve.');
assert(max(abs(numericalPresetDiff_mps)) <= sameGridTolerance_mps, ...
    'Public numerical-preset Cp differs from an equivalent direct solve.');

% Viscous fitting uses the same public solver and explicit fit-optimized grid
% policy. It remains a quality/metadata check, not an equality comparison
% against an intentionally different numerical-preset grid.
viscoParams = params;
viscoParams.etaS = 0.12;
viscoOptions = mrlfeDefaultSweepOptions(branchName, 'EtaS', viscoParams.etaS);
viscoOptions.mrlfeNumericalPreset = "fast";
viscoOptions.forwardModel = fastOptions.forwardModel;
[CpVisco_mps, rawVisco] = mrlfeEvaluateFitModel(viscoParams, frequency_Hz, branchName, viscoOptions);
assert(any(isfinite(CpVisco_mps)), 'Viscous mRLFE fitting evaluation produced no finite Cp points.');
assert(rawVisco.evaluationPath.usedPublicSolver == true, ...
    'Viscous mRLFE fitting evaluation should use the public solver route.');
assert(rawVisco.modelResult.execution.effectivePreset == "fast", ...
    'Viscous mRLFE fitting should use the public fast preset.');
assert(rawVisco.fitPerformanceDefaults.atlasCpScanPoints == 100, ...
    'Viscous public fast fitting should use the fast coarse production scan count.');
assert(rawVisco.fitPerformanceDefaults.rescueCpScanPoints == 260, ...
    'Viscous public fast fitting should report the dense rescue scan count.');
assert(rawVisco.modelResult.fallback.applied == false, ...
    'Viscous public fast fitting must not apply fallback.');

fprintf('Fast preset:      public=%s | internal=%s | cpScan=%g | rescueScan=%g\n', ...
    rawFast.fitPerformanceDefaults.preset, ...
    rawFast.fitPerformanceDefaults.internalFitAtlasPreset, ...
    rawFast.fitPerformanceDefaults.atlasCpScanPoints, ...
    rawFast.fitPerformanceDefaults.rescueCpScanPoints);
fprintf('Viscous preset:   public=%s | engine=%s | cpScan=%g | rescueScan=%g\n', ...
    rawVisco.fitPerformanceDefaults.preset, ...
    rawVisco.modelResult.execution.internalEngine, ...
    rawVisco.fitPerformanceDefaults.atlasCpScanPoints, ...
    rawVisco.fitPerformanceDefaults.rescueCpScanPoints);
fprintf('Same fit grid:    RMSE=%.6g m/s | max abs=%.6g m/s | max rel=%.6g\n', ...
    sameFitGridRmse_mps, sameFitGridMaxAbs_mps, sameFitGridMaxRel);
fprintf('Cross-grid diagnostic (no equality contract): RMSE=%.6g m/s | max abs=%.6g m/s | max rel=%.6g\n', ...
    crossPolicyRmse_mps, crossPolicyMaxAbs_mps, crossPolicyMaxRel);
fprintf('\nmRLFE fast fitting option quality test passed.\n');
