clear; clc;
startup

fprintf('\nRunning mRLFE neutral production dependency guard...\n');
fprintf('--------------------------------------------------\n');

root = testRepositoryRoot(mfilename('fullpath'));
productionDirs = [ ...
    string(fullfile(root, 'models', 'mrlfe', 'api')); ...
    string(fullfile(root, 'models', 'mrlfe', 'core')); ...
    string(fullfile(root, 'models', 'mrlfe', 'solvers')); ...
    string(fullfile(root, 'models', 'mrlfe', 'tracking')); ...
    string(fullfile(root, 'models', 'mrlfe', 'policies')); ...
    string(fullfile(root, 'models', 'mrlfe', 'results'))];

historicalNames = [ ...
    "mrlfeMakePhysicalSeedMode", ...
    "solveMRLFEBranchAdaptiveAtlas", ...
    "mrlfeApplyPhysicalCorridorCut"];

for iDir = 1:numel(productionDirs)
    files = dir(fullfile(productionDirs(iDir), '**', '*.m'));
    for iFile = 1:numel(files)
        filePath = fullfile(files(iFile).folder, files(iFile).name);
        text = string(fileread(filePath));
        for iName = 1:numel(historicalNames)
            assert(~contains(text, historicalNames(iName)), ...
                'Production file still references %s: %s', historicalNames(iName), filePath);
        end
    end
end

assert(isempty(which('mrlfeMakePhysicalSeedMode')), ...
    'Historical seed helper should not resolve on the MATLAB path.');
assert(isempty(which('solveMRLFEBranchAdaptiveAtlas')), ...
    'Historical adaptive tracker should not resolve on the MATLAB path.');
assert(isempty(which('mrlfeApplyPhysicalCorridorCut')), ...
    'Historical physical-tail helper should not resolve on the MATLAB path.');

fprintf('mRLFE neutral production dependency guard passed.\n');
