clear; clc;
startup

fprintf('\nRunning mRLFE removed-routes-absent test...\n');
fprintf('-------------------------------------\n');

root = testRepositoryRoot(mfilename('fullpath'));
deletedFunctions = [ ...
    "computeMRLFE", ...
    "solveMRLFEAtlasUnified", ...
    "solveMRLFEViscoBranchAtlas", ...
    "solveMRLFEBranchModalAtlas", ...
    "solveMRLFEBranchDP", ...
    "solveMRLFEBranch", ...
    "mrlfeEvaluateAtlasFitModel", ...
    "mrlfeMakeDirectViscoAtlasBranchOptions", ...
    "mrlfeApplyDelayedViscoModalCut"];

for i = 1:numel(deletedFunctions)
    assert(isempty(which(deletedFunctions(i))), ...
        'Deleted legacy function still resolves on path: %s.', deletedFunctions(i));
end

deletedFiles = string({ ...
    fullfile(root, 'models', 'mrlfe', 'solvers', 'computeMRLFE.m'), ...
    fullfile(root, 'models', 'mrlfe', 'solvers', 'solveMRLFEAtlasUnified.m'), ...
    fullfile(root, 'models', 'mrlfe', 'solvers', 'solveMRLFEViscoBranchAtlas.m'), ...
    fullfile(root, 'models', 'mrlfe', 'solvers', 'solveMRLFEBranchModalAtlas.m'), ...
    fullfile(root, 'models', 'mrlfe', 'solvers', 'solveMRLFEBranchDP.m'), ...
    fullfile(root, 'models', 'mrlfe', 'solvers', 'solveMRLFEBranch.m'), ...
    fullfile(root, 'analysis', 'mrlfe', 'mrlfeEvaluateAtlasFitModel.m')});
for i = 1:numel(deletedFiles)
    assert(~isfile(deletedFiles(i)), 'Deleted legacy file still exists: %s.', deletedFiles(i));
end

consumerFiles = string({ ...
    fullfile(root, 'app', 'adapters', 'guiRunMRLFEModel.m'), ...
    fullfile(root, 'app', 'adapters', 'guiRunMRLFESweep.m'), ...
    fullfile(root, 'app', 'adapters', 'guiFitMRLFESolver.m'), ...
    fullfile(root, 'analysis', 'mrlfe', 'mrlfeEvaluateFitModel.m')});
for i = 1:numel(consumerFiles)
    text = string(fileread(consumerFiles(i)));
    assert(contains(text, "mrlfeSolve") || contains(text, "mrlfeEvaluateFitModel") || contains(text, "mrlfeFitDispersionData"), ...
        'Maintained consumer no longer reaches the public mRLFE route: %s.', consumerFiles(i));
    for j = 1:numel(deletedFunctions)
        token = deletedFunctions(j);
        if token == "computeMRLFE"
            hasLegacyReference = contains(text, "computeMRLFE(");
        else
            hasLegacyReference = contains(text, token);
        end
        assert(~hasLegacyReference, ...
            'Maintained consumer references deleted legacy function %s: %s.', deletedFunctions(j), consumerFiles(i));
    end
end

fprintf('mRLFE removed-routes-absent test passed.\n');
