function test_mrlfe_configuration_ownership_contract()
%TEST_MRLFE_CONFIGURATION_OWNERSHIP_CONTRACT Guard model-owned request/configuration translation.

fprintf('\nRunning mRLFE configuration ownership contract...\n');
fprintf('-----------------------------------------------\n');

root = testRepositoryRoot(mfilename('fullpath'));
requestOwner = fullfile(root, 'src', '+lamb', '+models', '+mrlfe', '+configuration', 'mrlfeBuildSolveRequest.m');
assert(isfile(requestOwner), 'mRLFE solve-request construction must be model-owned under configuration/.');
assert(strcmp(which('lamb.models.mrlfe.configuration.mrlfeBuildSolveRequest'), requestOwner), ...
    'lamb.models.mrlfe.configuration.mrlfeBuildSolveRequest must resolve to the model configuration owner.');
assert(~isfile(fullfile(root, 'analysis', 'requests', 'mrlfe', 'mrlfeBuildSolveRequest.m')), ...
    'The old analysis-owned mRLFE request builder must be absent.');

maintainedFiles = string({ ...
    fullfile(root, 'app', 'main', 'guiRunMRLFEModel.m'), ...
    fullfile(root, 'app', 'sweep', 'guiRunMRLFESweep.m'), ...
    fullfile(root, 'app', 'fitting', 'guiFitMRLFESolver.m'), ...
    fullfile(root, 'src', '+lamb', '+fitting', '+mrlfe', 'mrlfeEvaluateFitModel.m'), ...
    fullfile(root, 'analysis', 'sweeps', 'mrlfe', 'mrlfeDefaultSweepOptions.m'), ...
    requestOwner, ...
    fullfile(root, 'src', '+lamb', '+models', '+mrlfe', '+configuration', 'mrlfeResolveConfiguration.m')});

removedRequestBuilders = string({ ...
    'mrlfeBuildPublicSolveRequest.m', ...
    'mrlfeBuildGuiSolveRequest.m', ...
    'mrlfeBuildFitSolveRequest.m', ...
    'mrlfeBuildSweepSolveRequest.m'});
for i = 1:numel(removedRequestBuilders)
    assert(~isfile(fullfile(root, 'analysis', 'mrlfe', removedRequestBuilders(i))), ...
        'Removed request-builder alias is present: %s.', removedRequestBuilders(i));
end

rayleighLambOwners = string({ ...
    fullfile(root, 'src', '+lamb', '+models', '+rayleigh_lamb', 'rlDefaultOptions.m'), ...
    fullfile(root, 'src', '+lamb', '+models', '+rayleigh_lamb', 'rlComputeFundamentalLambModes.m')});
for i = 1:numel(rayleighLambOwners)
    text = lower(string(fileread(rayleighLambOwners(i))));
    assert(~contains(text, "mrlfe"), ...
        'Rayleigh-Lamb owner still contains mRLFE responsibility: %s.', rayleighLambOwners(i));
end

forbidden = [ ...
    "mrlfeUseAtlasFitRoute", ...
    "mrlfeUseLegacyFitRoute", ...
    "mrlfeUseDirectViscoAtlas", ...
    "mrlfeUseUnifiedAtlasRoute", ...
    "mrlfeGuiActualRoute", ...
    "mrlfeGuiAtlasPreset", ...
    "mrlfeZeroViscosityAdaptiveFallback", ...
    "fast_fit_atlas", ...
    "viscous_unified_atlas", ...
    "zero_viscosity_adaptive_fallback", ...
    "adaptivePhysicalTail", ...
    "delayedCut"];

for i = 1:numel(maintainedFiles)
    text = string(fileread(maintainedFiles(i)));
    for j = 1:numel(forbidden)
        assert(~contains(text, forbidden(j)), ...
            'Maintained file still contains legacy route token %s: %s.', forbidden(j), maintainedFiles(i));
    end
end

fprintf('mRLFE configuration ownership contract passed.\n');
end
