clear; clc;
startup

fprintf('\nRunning mRLFE removed-route-flags-absent test...\n');
fprintf('------------------------------------------\n');

root = testRepositoryRoot(mfilename('fullpath'));
maintainedFiles = string({ ...
    fullfile(root, 'app', 'adapters', 'guiRunMRLFEModel.m'), ...
    fullfile(root, 'app', 'adapters', 'guiRunMRLFESweep.m'), ...
    fullfile(root, 'app', 'adapters', 'guiFitMRLFESolver.m'), ...
    fullfile(root, 'analysis', 'mrlfe', 'mrlfeEvaluateFitModel.m'), ...
    fullfile(root, 'analysis', 'mrlfe', 'mrlfeDefaultSweepOptions.m'), ...
    fullfile(root, 'analysis', 'mrlfe', 'mrlfeBuildSolveRequest.m'), ...
    fullfile(root, 'models', 'mrlfe', 'configuration', 'mrlfeResolveConfiguration.m')});

removedRequestBuilders = string({ ...
    'mrlfeBuildPublicSolveRequest.m', ...
    'mrlfeBuildGuiSolveRequest.m', ...
    'mrlfeBuildFitSolveRequest.m', ...
    'mrlfeBuildSweepSolveRequest.m'});
for i = 1:numel(removedRequestBuilders)
    assert(~isfile(fullfile(root, 'analysis', 'mrlfe', removedRequestBuilders(i))), ...
        'Removed request-builder alias is present: %s.', removedRequestBuilders(i));
end

rayleighLambOwners = string({ ...
    fullfile(root, 'models', 'rayleigh_lamb', 'core', 'rlDefaultOptions.m'), ...
    fullfile(root, 'models', 'rayleigh_lamb', 'core', 'rlComputeFundamentalLambModes.m')});
for i = 1:numel(rayleighLambOwners)
    text = lower(string(fileread(rayleighLambOwners(i))));
    assert(~contains(text, "mrlfe"), ...
        'Rayleigh-Lamb owner still contains mRLFE responsibility: %s.', rayleighLambOwners(i));
end

forbidden = [ ...
    "mrlfeUseAtlasFitRoute", ...
    "mrlfeUseLegacyFitRoute", ...
    "mrlfeUseDirectViscoAtlas", ...
    "mrlfeUseUnifiedAtlasRoute", ...
    "mrlfeGuiActualRoute", ...
    "mrlfeGuiAtlasPreset", ...
    "mrlfeZeroViscosityAdaptiveFallback", ...
    "fast_fit_atlas", ...
    "viscous_unified_atlas", ...
    "zero_viscosity_adaptive_fallback", ...
    "adaptivePhysicalTail", ...
    "delayedCut"];

for i = 1:numel(maintainedFiles)
    text = string(fileread(maintainedFiles(i)));
    for j = 1:numel(forbidden)
        assert(~contains(text, forbidden(j)), ...
            'Maintained file still contains legacy route token %s: %s.', forbidden(j), maintainedFiles(i));
    end
end

fprintf('mRLFE removed-route-flags-absent test passed.\n');
