clear; clc;
startup

%TEST_MRLFE_ROBUST_START_CONTRACT Verify forward-only A0Like recovery.

% Reproduce the observed failure pattern: a very low first frequency followed
% by a jump that prevents the original forward tracker from establishing A0Like.
solveFrequency_Hz = unique([10; (184:150:4000).'; 4000]);
requestedFrequency_Hz = [10 184 500 1000 2000 4000].';

request = struct();
request.branch = "A0Like";
request.frequency_Hz = requestedFrequency_Hz;
request.material = struct( ...
    'mu_Pa', 75e3, ...
    'etaS_Pas', 0, ...
    'rho_kgm3', 1070, ...
    'nu', 0.4999);
request.geometry = struct('thickness_m', 0.5e-3);
request.fluid = struct('density_kgm3', 1000, 'soundSpeed_mps', 1500);
request.numerics = struct( ...
    'preset', "fast", ...
    'frequencySolveOverride_Hz', solveFrequency_Hz);
request.selection = struct('strategy', "adaptive");
request.termination = struct('policy', "physicalTail");
request.fallback = struct('policy', "none");

result = mrlfeSolve(request);
branch = result.diagnostics.rawInternalResult.branchSolve;

assert(isfield(branch, 'robustStart') && isstruct(branch.robustStart), ...
    'A0Like branch diagnostics must include robustStart metadata.');
assert(branch.robustStart.Enabled, ...
    'Robust-start must be enabled for A0Like production solving.');
assert(branch.robustStart.Attempted, ...
    'The low-frequency regression case must attempt robust-start recovery.');
assert(branch.robustStart.Applied, ...
    'The low-frequency regression case must apply a stable robust start.');
assert(isfinite(branch.robustStart.StartIndex) && branch.robustStart.StartIndex > 1, ...
    'Robust-start must begin after the failing low-frequency prefix.');
assert(isfinite(branch.robustStart.StartFrequency_Hz), ...
    'Robust-start metadata must report the selected start frequency.');
assert(all(~branch.validCp(1:branch.robustStart.StartIndex-1)), ...
    'Frequencies before the robust start must remain invalid without backward tracking.');
assert(nnz(branch.validCp(branch.robustStart.StartIndex:end)) >= branch.robustStart.MinValidRun, ...
    'The recovered forward branch must contain the required stable valid run.');
assert(isequal(result.frequency_Hz(:), requestedFrequency_Hz), ...
    'Robust-start must not change the public requested frequency grid.');
assert(~result.fallback.applied, ...
    'Robust-start is a tracking policy and must not be reported as solver fallback.');

fprintf(['test_mrlfe_robust_start_contract passed. A0Like recovers forward from a ' ...
    'stable start while preserving invalid lower frequencies.\n']);
