clear; clc;
if isempty(which('mrlfeSolve'))
    startup
end

fprintf('\nRunning mRLFE production core contract test...\n');
fprintf('---------------------------------------------\n');

assertFunctionsOnPath({ ...
    'mrlfeBuildProblem', ...
    'mrlfeSolveBranch', ...
    'mrlfeSolveElasticBranch', ...
    'mrlfeSolveViscoelasticBranch', ...
    'mrlfeBuildSeed', ...
    'mrlfeTrackBranchAdaptive', ...
    'mrlfeApplyTerminationPolicy'});

root = testRepositoryRoot();
solveText = fileread(fullfile(root, 'models', 'mrlfe', 'api', 'mrlfeSolve.m'));
assert(~contains(solveText, 'mrlfeEvaluateAtlasFitModel'), ...
    'mrlfeSolve must not call mrlfeEvaluateAtlasFitModel.');
assert(~contains(solveText, 'mrlfeEvaluateFitModel'), ...
    'mrlfeSolve must not call mrlfeEvaluateFitModel.');

productionFiles = [ ...
    string(fullfile(root, 'models', 'mrlfe', 'core', 'mrlfeBuildProblem.m')); ...
    string(fullfile(root, 'models', 'mrlfe', 'solvers', 'mrlfeSolveBranch.m')); ...
    string(fullfile(root, 'models', 'mrlfe', 'solvers', 'mrlfeSolveElasticBranch.m')); ...
    string(fullfile(root, 'models', 'mrlfe', 'solvers', 'mrlfeSolveViscoelasticBranch.m')); ...
    string(fullfile(root, 'models', 'mrlfe', 'tracking', 'mrlfeBuildSeed.m')); ...
    string(fullfile(root, 'models', 'mrlfe', 'tracking', 'mrlfeTrackBranchAdaptive.m')); ...
    string(fullfile(root, 'models', 'mrlfe', 'policies', 'mrlfeApplyTerminationPolicy.m'))];

for i = 1:numel(productionFiles)
    text = fileread(productionFiles(i));
    assert(~contains(text, 'mrlfeEvaluateAtlasFitModel'), ...
        'Production core must not call mrlfeEvaluateAtlasFitModel: %s', productionFiles(i));
    assert(~contains(text, 'mrlfeEvaluateFitModel'), ...
        'Production core must not call mrlfeEvaluateFitModel: %s', productionFiles(i));
    assert(~contains(text, 'guiRunMRLFEModel') && ~contains(text, 'guiFitMRLFESolver'), ...
        'Production core must not call GUI adapters: %s', productionFiles(i));
end

request = localRequest("A0Like", 0.05, "fast", "physicalTail");
result = mrlfeSolve(request);
assert(result.execution.internalEngine == "viscoelastic_adaptive", ...
    'Effective engine name must be neutral for viscoelastic cases.');
assert(~contains(result.execution.internalEngine, "Fit") && ...
    ~contains(result.execution.internalEngine, "GUI") && ...
    ~contains(result.execution.internalEngine, "Unified"), ...
    'Effective engine must not expose historical route naming.');
assert(result.execution.requestedPreset == "fast", 'Requested preset metadata changed.');
assert(result.execution.effectivePreset == "fast", 'Effective preset metadata changed.');
assert(result.fallback.applied == false, 'Production core must not apply fallback.');

elastic = mrlfeSolve(localRequest("S0Like", 0, "fast", "none"));
assert(elastic.execution.internalEngine == "elastic_adaptive", ...
    'Effective engine name must be neutral for zero-viscosity cases.');

fprintf('mRLFE production core contract test passed.\n');

function assertFunctionsOnPath(functionNames)
for i = 1:numel(functionNames)
    assert(~isempty(which(functionNames{i})), 'Missing function on path: %s.', functionNames{i});
end
end

function request = localRequest(branch, etaS, preset, terminationPolicy)
request = struct();
request.branch = string(branch);
request.frequency_Hz = linspace(1000, 6000, 10).';
request.material = struct('mu_Pa', 75e3, 'etaS_Pas', etaS, 'rho_kgm3', 1000, 'nu', 0.4999);
request.geometry = struct('thickness_m', 0.5e-3);
request.fluid = struct('density_kgm3', 1000, 'soundSpeed_mps', 1500);
request.numerics = struct('preset', string(preset));
request.selection = struct('strategy', "adaptive");
request.termination = struct('policy', string(terminationPolicy));
request.fallback = struct('policy', "none");
end
