clear; clc;
configureTestPath;
fprintf('\nRunning mRLFE production dependency contract...\n');
fprintf('---------------------------------------------\n');

root = testRepositoryRoot(mfilename('fullpath'));
productionDirs = [ ...
    string(fullfile(root, 'models', 'mrlfe', 'api')); ...
    string(fullfile(root, 'models', 'mrlfe', 'core')); ...
    string(fullfile(root, 'models', 'mrlfe', 'solvers')); ...
    string(fullfile(root, 'models', 'mrlfe', 'tracking')); ...
    string(fullfile(root, 'models', 'mrlfe', 'policies')); ...
    string(fullfile(root, 'models', 'mrlfe', 'results'))];

retiredNames = [ ...
    "mrlfeMakePhysicalSeedMode", ...
    "solveMRLFEBranchAdaptiveAtlas", ...
    "mrlfeApplyPhysicalCorridorCut"];

for iDir = 1:numel(productionDirs)
    files = dir(fullfile(productionDirs(iDir), '**', '*.m'));
    for iFile = 1:numel(files)
        filePath = fullfile(files(iFile).folder, files(iFile).name);
        text = string(fileread(filePath));
        for iName = 1:numel(retiredNames)
            assert(~contains(text, retiredNames(iName)), ...
                'Production file still references retired owner %s: %s', retiredNames(iName), filePath);
        end
    end
end

assert(isempty(which('mrlfeMakePhysicalSeedMode')), ...
    'Retired seed helper should not resolve on the MATLAB path.');
assert(isempty(which('solveMRLFEBranchAdaptiveAtlas')), ...
    'Retired adaptive tracker should not resolve on the MATLAB path.');
assert(isempty(which('mrlfeApplyPhysicalCorridorCut')), ...
    'Retired physical-tail helper should not resolve on the MATLAB path.');

fprintf('mRLFE production dependency contract passed.\n');
