clear; clc;
startup

fprintf('\nRunning mRLFE removed-route-flags-absent test...\n');
fprintf('------------------------------------------\n');

root = testRepositoryRoot(mfilename('fullpath'));
maintainedFiles = string({ ...
    fullfile(root, 'app', 'adapters', 'guiRunMRLFEModel.m'), ...
    fullfile(root, 'app', 'adapters', 'guiRunMRLFESweep.m'), ...
    fullfile(root, 'app', 'adapters', 'guiFitMRLFESolver.m'), ...
    fullfile(root, 'analysis', 'mrlfe', 'mrlfeEvaluateFitModel.m'), ...
    fullfile(root, 'analysis', 'mrlfe', 'mrlfeDefaultSweepOptions.m'), ...
    fullfile(root, 'analysis', 'mrlfe', 'mrlfeBuildFitSolveRequest.m'), ...
    fullfile(root, 'models', 'mrlfe', 'configuration', 'mrlfeResolveConfiguration.m')});

forbidden = [ ...
    "mrlfeUseAtlasFitRoute", ...
    "mrlfeUseLegacyFitRoute", ...
    "mrlfeUseDirectViscoAtlas", ...
    "mrlfeUseUnifiedAtlasRoute", ...
    "mrlfeGuiActualRoute", ...
    "mrlfeGuiAtlasPreset", ...
    "mrlfeZeroViscosityAdaptiveFallback", ...
    "fast_fit_atlas", ...
    "viscous_unified_atlas", ...
    "zero_viscosity_adaptive_fallback", ...
    "adaptivePhysicalTail", ...
    "delayedCut"];

for i = 1:numel(maintainedFiles)
    text = string(fileread(maintainedFiles(i)));
    for j = 1:numel(forbidden)
        assert(~contains(text, forbidden(j)), ...
            'Maintained file still contains legacy route token %s: %s.', forbidden(j), maintainedFiles(i));
    end
end

fprintf('mRLFE removed-route-flags-absent test passed.\n');
