clear; clc;
startup

fprintf('\nRunning mRLFE SweepTool public-solver route guard test...\n');
fprintf('--------------------------------------------------------\n');

repoRoot = fileparts(fileparts(fileparts(fileparts(mfilename('fullpath')))));
adapterPath = fullfile(repoRoot, 'app', 'sweep', 'guiRunMRLFESweep.m');
adapterText = string(fileread(adapterPath));

assert(contains(adapterText, "mrlfeSolve"), ...
    'mRLFE SweepTool adapter must call public mrlfeSolve.');
assert(~contains(adapterText, "guiRunMRLFEModel"), ...
    'mRLFE SweepTool adapter must not call the Main GUI mRLFE adapter.');
assert(~contains(adapterText, "solveMRLFE") && ~contains(adapterText, "computeMRLFE") && ...
    ~contains(adapterText, "mrlfeTrackBranchAdaptive"), ...
    'mRLFE SweepTool adapter must not contain low-level mRLFE solver logic.');
assert(contains(adapterText, "runParametricSweep"), ...
    'mRLFE SweepTool adapter must delegate iteration to runParametricSweep.');

branches = ["A0Like", "S0Like"];
etaSValues = [0, 0.05];
for iBranch = 1:numel(branches)
    for iEta = 1:numel(etaSValues)
        out = runSmallSweep(branches(iBranch), etaSValues(iEta));
        assert(numel(out.sweepResult.points) == 1, 'Expected one public-solver sweep point.');
        point = out.sweepResult.points{1};
        assert(point.status == "ok", 'Sweep point must complete successfully.');
        assert(isfield(point, 'modelResult') && isstruct(point.modelResult), ...
            'Sweep point must preserve the public model result.');
        assert(point.modelResult.execution.effectivePreset == "fast", ...
            'SweepTool mRLFE must use public fast preset.');
        assert(point.modelResult.fallback.policy == "none" && point.modelResult.fallback.applied == false, ...
            'SweepTool mRLFE must not apply fallback.');
        if etaSValues(iEta) == 0
            assert(point.modelResult.execution.internalEngine == "elastic_adaptive", ...
                'Zero-viscosity sweep point must use elastic_adaptive.');
        else
            assert(point.modelResult.execution.internalEngine == "viscoelastic_adaptive", ...
                'Positive-viscosity sweep point must use viscoelastic_adaptive.');
        end
        if branches(iBranch) == "A0Like"
            assert(point.modelResult.termination.policy == "physicalTail", ...
                'A0Like sweep must use physicalTail termination.');
        else
            assert(point.modelResult.termination.policy == "none", ...
                'S0Like sweep must use no additional termination.');
        end
    end
end

fprintf('\nmRLFE SweepTool public-solver route guard test passed.\n');

function out = runSmallSweep(branchName, etaS)
params = rlDefaultParams();
params.fmin = 1000;
params.fmax = 3000;
params.numFrequencyPoints = 10;
params.frequencySpacing = "linspace";
controls = struct('robustness', "Fast", 'etaS', etaS, ...
    'fluidDensity', 1000, 'fluidSoundSpeed', 1500, ...
    'mrlfeA0Policy', "physicalTail");
out = guiRunMRLFESweep(guiBuildSweepRequest("mrlfe", ...
    'modelLabel', "mRLFE real-k", ...
    'branchName', branchName, ...
    'sweepField', "mu", ...
    'sweepLabel', "mu", ...
    'sweepValuesDisplay', 75, ...
    'displayUnit', "kPa", ...
    'displayScale', 1e3, ...
    'baseParams', params, ...
    'controls', controls));
end
