function test_mrlfe_sweep_metadata_and_mapping()
%TEST_MRLFE_SWEEP_METADATA_AND_MAPPING Validate sweep metadata and parameter mapping.

fprintf('\nRunning mRLFE SweepTool metadata and mapping test...\n');
fprintf('---------------------------------------------------\n');

%% Mixed etaS sweep must aggregate both engines.
etaOut = runSweep("A0Like", "etaS", "etaS", [0, 0.05, 0.10], "Pa*s", 1, 0.05);
assert(isequal(etaOut.sweepSpec.values(:), [0; 0.05; 0.10]), ...
    'etaS sweep values must preserve order and units.');
assert(any(etaOut.metadata.internalEngines == "elastic_adaptive"), ...
    'Mixed etaS sweep metadata must include elastic_adaptive.');
assert(any(etaOut.metadata.internalEngines == "viscoelastic_adaptive"), ...
    'Mixed etaS sweep metadata must include viscoelastic_adaptive.');
assert(numel(etaOut.metadata.internalEngines) == 2, ...
    'Mixed etaS sweep metadata must not report only the first point engine.');
assert(etaOut.metadata.anyFallbackApplied == false, ...
    'SweepTool mRLFE must not apply fallback in mixed etaS sweep.');
assert(etaOut.metadata.pointCount == 3 && etaOut.metadata.failedPointCount == 0, ...
    'Mixed etaS aggregate point counts are incorrect.');
assert(etaOut.executionProfile.requestedExecutionProfile == "Fast", ...
    'Requested execution profile must remain visible.');
assert(etaOut.executionProfile.effectiveExecutionProfile == "Fast", ...
    'Effective execution profile must remain visible.');
assert(all(etaOut.metadata.effectiveNumericalPresets == "fast"), ...
    'Effective numerical preset metadata must be fast.');

for i = 1:numel(etaOut.sweepResult.points)
    point = etaOut.sweepResult.points{i};
    assert(point.configuration.effective.parameters.etaS_Pas == etaOut.sweepSpec.values(i), ...
        'etaS sweep point was not mapped to public etaS_Pas.');
    assert(point.fallback.policy == "none" && point.fallback.applied == false, ...
        'Point fallback must remain disabled.');
    assert(isfield(etaOut.normalized.curves(i), 'modelResult') && ...
        isstruct(etaOut.normalized.curves(i).modelResult), ...
        'Normalized curve must retain point public model result for diagnostics.');
    assert(~isempty(etaOut.normalized.curves(i).frequency_Hz), ...
        'Normalized curve must preserve plotting frequency data.');
    assert(isequal(size(etaOut.normalized.curves(i).frequency_Hz), size(etaOut.normalized.curves(i).Cp_mps)), ...
        'Plotting frequency and Cp sizes must match.');
end

%% Thickness mapping.
thicknessOut = runSweep("A0Like", "thickness", "thickness", [0.4, 0.5, 0.6], "mm", 1e-3, 0.05);
assert(isequal(thicknessOut.sweepSpec.values(:), [0.4; 0.5; 0.6] * 1e-3), ...
    'thickness sweep values must convert mm to m.');
for i = 1:numel(thicknessOut.sweepResult.points)
    point = thicknessOut.sweepResult.points{i};
    assert(abs(point.configuration.effective.parameters.thickness_m - thicknessOut.sweepSpec.values(i)) <= ...
        eps(max(1, thicknessOut.sweepSpec.values(i))), ...
        'thickness sweep point was not mapped to public thickness_m.');
end

%% S0Like positive-viscosity mu sweep.
s0Out = runSweep("S0Like", "mu", "mu", [60, 75], "kPa", 1e3, 0.05);
assert(all(s0Out.metadata.terminationPolicies == "none"), ...
    'S0Like sweep aggregate metadata must report no additional termination.');
for i = 1:numel(s0Out.sweepResult.points)
    point = s0Out.sweepResult.points{i};
    assert(point.modelResult.branch == "S0Like", 'S0Like branch identity changed.');
    assert(point.configuration.effective.parameters.mu_Pa == s0Out.sweepSpec.values(i), ...
        'mu sweep point was not mapped to public mu_Pa.');
end

fprintf('Mixed engines: %s\n', strjoin(etaOut.metadata.internalEngines, ', '));
fprintf('\nmRLFE SweepTool metadata and mapping test passed.\n');
end

function out = runSweep(branchName, sweepField, sweepLabel, valuesDisplay, displayUnit, displayScale, etaS)
params = rlDefaultParams();
params.fmin = 1000;
params.fmax = 6000;
params.numFrequencyPoints = 10;
params.frequencySpacing = "linspace";
params.mu = 75e3;
params.thickness = 0.5e-3;
params.rho = 1070;
params.nu = 0.4999;

controls = struct('robustness', "Fast", 'etaS', etaS, ...
    'fluidDensity', 1000, 'fluidSoundSpeed', 1500, ...
    'mrlfeA0Policy', "physicalTail");

out = guiRunMRLFESweep(guiBuildSweepRequest("mrlfe", ...
    'modelLabel', "mRLFE real-k", ...
    'branchName', branchName, ...
    'sweepField', sweepField, ...
    'sweepLabel', sweepLabel, ...
    'sweepValuesDisplay', valuesDisplay, ...
    'displayUnit', displayUnit, ...
    'displayScale', displayScale, ...
    'baseParams', params, ...
    'controls', controls));
end
