function test_ae_physical_sweep_examples_contract()
%TEST_AE_PHYSICAL_SWEEP_EXAMPLES_CONTRACT Validate maintained AE sweep campaigns.
%
% This is a lightweight source-level contract. It checks the public entrypoints,
% requested fields, ranges, units, and output task names without running the
% computationally expensive Robust sweeps.

repoRoot = testRepositoryRoot();
analysisPath = fullfile(repoRoot, 'analysis', 'sweeps', ...
    'acoustoelastic_iop_hgo', 'aeRunSweep.m');
oldModelPath = fullfile(repoRoot, 'models', 'acoustoelastic_iop_hgo', 'solvers', 'aeRunSweep.m');
assert(isfile(analysisPath), 'aeRunSweep must be owned by the AE analysis layer.');
assert(~isfile(oldModelPath), 'The former model-layer aeRunSweep path must be absent.');
assert(strcmp(which('aeRunSweep'), analysisPath), ...
    'aeRunSweep must resolve uniquely from the AE analysis layer.');
interactivePlotPath = fullfile(repoRoot, 'app', 'sweep', ...
    'aePlotGridSweepFrequencySurfaceInteractive.m');
oldInteractivePlotPath = fullfile(repoRoot, 'analysis', 'acoustoelastic_iop_hgo', ...
    'aePlotGridSweepFrequencySurfaceInteractive.m');
assert(isfile(interactivePlotPath), ...
    'The interactive AE sweep visualization must be owned by app/sweep.');
assert(~isfile(oldInteractivePlotPath), ...
    'The former analysis-layer interactive visualization path must be absent.');
assert(strcmp(which('aePlotGridSweepFrequencySurfaceInteractive'), interactivePlotPath), ...
    'The interactive AE sweep visualization must resolve uniquely from app/sweep.');

cases = makeCase("ae_sweep_iop_A0Like", "IOP", ...
    "IOP_mmHg = [5, 10, 15, 20, 25]", "iop_sweep");

for i = 1:numel(cases)
    entryPath = which(cases(i).entrypoint);
    assert(~isempty(entryPath), ...
        'Missing maintained AE sweep entrypoint: %s.', cases(i).entrypoint);

    text = string(fileread(entryPath));
    expectedCall = string(sprintf('aeRunSweep(baseParams, "%s"', cases(i).field));
    expectedTask = string(sprintf('"%s"', cases(i).taskName));

    assert(contains(text, cases(i).rangeText), ...
        'Unexpected sweep range in %s.', cases(i).entrypoint);
    assert(contains(text, "aeDefaultSweepParams()"), ...
        '%s must use the shared AE sweep defaults.', cases(i).entrypoint);
    assert(contains(text, "aeDefaultSweepOptions(""Robust"")"), ...
        '%s must preserve the maintained Robust example profile.', cases(i).entrypoint);
    assert(contains(text, expectedCall), ...
        '%s must sweep the expected physical field.', cases(i).entrypoint);
    assert(contains(text, "aeWriteSweepOutputs"), ...
        '%s must use the maintained AE output writer.', cases(i).entrypoint);
    assert(contains(text, expectedTask), ...
        '%s must use the expected output task name.', cases(i).entrypoint);
    assert(contains(text, "aePlotSweepCp"), ...
        '%s must use the maintained AE sweep plot helper.', cases(i).entrypoint);
    assert(contains(text, "aeSaveExampleFigure"), ...
        '%s must use the maintained AE figure writer.', cases(i).entrypoint);
end

assert(~isempty(which('ae_sweep_mu_iop_A0Like')), ...
    'Missing maintained AE combined mu-IOP sweep entrypoint.');
assertObsoleteEntrypointsAreAbsent([ ...
    "sweep_iop", ...
    "sweep_mu", ...
    "sweep_thickness", ...
    "sweep_k1", ...
    "sweep_k2", ...
    "sweep_radius", ...
    "sweep_mu_iop" ...
    ]);

fprintf('AE physical sweep example contract test passed.\n');
end

function assertObsoleteEntrypointsAreAbsent(names)
for i = 1:numel(names)
    assert(isempty(which(names(i))), ...
        'Obsolete AE sweep entrypoint should not resolve on the MATLAB path: %s.', names(i));
end
end

function c = makeCase(entrypoint, field, rangeText, taskName)
c = struct( ...
    'entrypoint', string(entrypoint), ...
    'field', string(field), ...
    'rangeText', string(rangeText), ...
    'taskName', string(taskName));
end
