function test_acoustoelastic_iop_hgo_short_entrypoints()
%TEST_ACOUSTOELASTIC_IOP_HGO_SHORT_ENTRYPOINTS Verify maintained AE entrypoints are on path.
%
% This is a path-level smoke test only. It does not execute heavy diagnostics.
% Retained implementation diagnostics are path-checked but not executed.

repoRoot = testRepositoryRoot(mfilename('fullpath'));

maintainedHelpers = [ ...
    "resolveModelOutputFolder", ...
    "aeResolveResultFile", ...
    "aeClassifyAmbiguityRegime" ...
    ];
maintainedWorkflows = [ ...
    "run_atlas_branch", ...
    "ae_sweep_iop_A0Like", ...
    "ae_sweep_mu_A0Like", ...
    "ae_sweep_thickness_A0Like", ...
    "ae_sweep_k1_A0Like", ...
    "ae_sweep_k2_A0Like", ...
    "ae_sweep_radius_A0Like", ...
    "ae_sweep_mu_iop_A0Like" ...
    ];
maintainedDiagnostics = [ ...
    "compare_atlasA0_vs_raw_branch1", ...
    "validate_atlas_raw_grid", ...
    "diagnose_raw_branch_corner", ...
    "diagnose_branch_families", ...
    "diagnose_sweep_reliability", ...
    "diagnose_atlas_truncation", ...
    "diagnose_idA0_plausibility" ...
    ];

maintainedNames = [maintainedHelpers, maintainedWorkflows, maintainedDiagnostics];

for i = 1:numel(maintainedNames)
    entryPath = which(maintainedNames(i));
    assert(~isempty(entryPath), 'Missing maintained AE entrypoint/helper on MATLAB path: %s', maintainedNames(i));
end

retainedDiagnosticImplementations = [ ...
    "validate_idA0_score_grid", ...
    "validate_idA0_grid", ...
    "diagnose_modal_atlas", ...
    "diagnose_idA0_score", ...
    "diagnose_grid_start_sensitivity", ...
    "track_raw_branch1" ...
    ];

for i = 1:numel(retainedDiagnosticImplementations)
    assert(~isempty(which(retainedDiagnosticImplementations(i))), ...
        'Missing retained AE diagnostic implementation on MATLAB path: %s', retainedDiagnosticImplementations(i));
end

assertFunctionsAbsent([ ...
    "validate_acoustoelastic_iop_hgo_identityA0_diagnostic_grid", ...
    "validate_acoustoelastic_iop_hgo_branch_identity_score_grid", ...
    "diagnose_acoustoelastic_iop_hgo_modal_atlas", ...
    "diagnose_idA0_plausibility_impl" ...
    ], 'removed AE diagnostic name');
assertObsoleteModalAtlasLowFrequencyEntrypointsAreAbsent(repoRoot);
assertObsoleteSweepEntrypointsAreAbsent();
assertMaintainedDocsContain(maintainedHelpers, maintainedWorkflows, maintainedDiagnostics);

fprintf('Maintained acoustoelastic IOP/HGO entrypoint path test passed. Retained diagnostic implementations verified.\n');
end

function assertObsoleteSweepEntrypointsAreAbsent()
obsoleteNames = [ ...
    "sweep_iop", ...
    "sweep_mu", ...
    "sweep_thickness", ...
    "sweep_k1", ...
    "sweep_k2", ...
    "sweep_radius", ...
    "sweep_mu_iop" ...
    ];
for i = 1:numel(obsoleteNames)
    assert(isempty(which(obsoleteNames(i))), ...
        'Obsolete AE sweep entrypoint should not be on the MATLAB path: %s', obsoleteNames(i));
end
end

function assertObsoleteModalAtlasLowFrequencyEntrypointsAreAbsent(repoRoot)
obsoletePaths = { ...
    fullfile(repoRoot, 'examples', 'acoustoelastic_iop_hgo', 'diagnostics', 'diagnose_modal_atlas_lowfreq.m'), ...
    fullfile(repoRoot, 'examples', 'acoustoelastic_iop_hgo', 'diagnostics', 'diagnose_acoustoelastic_iop_hgo_low_frequency_modal_atlas.m')};
for i = 1:numel(obsoletePaths)
    assert(~isfile(obsoletePaths{i}), 'Obsolete low-frequency modal-atlas entrypoint should not exist: %s', obsoletePaths{i});
end
assert(isempty(which('diagnose_modal_atlas_lowfreq')), ...
    'Obsolete diagnose_modal_atlas_lowfreq entrypoint should not be on the MATLAB path.');
end

function assertFunctionsAbsent(functionNames, label)
for i = 1:numel(functionNames)
    assert(isempty(which(functionNames(i))), ...
        'Unexpected %s on MATLAB path: %s', label, functionNames(i));
end
end

function assertMaintainedDocsContain(maintainedHelpers, maintainedWorkflows, maintainedDiagnostics)
repoRoot = testRepositoryRoot(mfilename('fullpath'));
entrypointsText = fileread(fullfile(repoRoot, 'docs', 'repository', 'maintained_entrypoints.md'));
publicApiText = fileread(fullfile(repoRoot, 'docs', 'models', 'acoustoelastic_iop_hgo', 'active', 'public_api.md'));
readmeText = fileread(fullfile(repoRoot, 'docs', 'models', 'acoustoelastic_iop_hgo', 'README.md'));

for iName = 1:numel([maintainedHelpers, maintainedWorkflows, maintainedDiagnostics])
    entryName = [maintainedHelpers, maintainedWorkflows, maintainedDiagnostics];
    assert(contains(publicApiText, entryName(iName)), ...
        'public_api.md is missing maintained AE entrypoint/helper: %s', entryName(iName));
end

for iName = 1:numel([maintainedWorkflows, maintainedDiagnostics])
    entryName = [maintainedWorkflows, maintainedDiagnostics];
    assert(contains(entrypointsText, entryName(iName)), ...
        'maintained_entrypoints.md is missing maintained AE workflow/diagnostic: %s', entryName(iName));
    assert(contains(readmeText, entryName(iName)), ...
        'README.md is missing maintained AE workflow/diagnostic: %s', entryName(iName));
end
end
