function test_ae_physical_sweep_examples_contract()
%TEST_AE_PHYSICAL_SWEEP_EXAMPLES_CONTRACT Validate maintained AE sweep campaigns.
%
% This is a lightweight source-level contract. It checks the public entrypoints,
% requested fields, ranges, units, and output task names without running the
% computationally expensive Robust sweeps.

cases = [ ...
    makeCase("sweep_thickness", "thickness", ...
        "thickness_um = [400, 475, 550, 625, 700]", "thickness_sweep"); ...
    makeCase("sweep_k1", "k1", ...
        "k1_kPa = [10, 25, 50, 75, 100]", "k1_sweep"); ...
    makeCase("sweep_k2", "k2", ...
        "k2_values = [50, 100, 200, 300, 400]", "k2_sweep"); ...
    makeCase("sweep_radius", "R", ...
        "radius_mm = [7.0, 7.4, 7.8, 8.2, 8.6]", "radius_sweep")];

for i = 1:numel(cases)
    entryPath = which(cases(i).entrypoint);
    assert(~isempty(entryPath), ...
        'Missing maintained AE sweep entrypoint: %s.', cases(i).entrypoint);

    text = string(fileread(entryPath));
    assert(contains(text, cases(i).rangeText), ...
        'Unexpected sweep range in %s.', cases(i).entrypoint);
    assert(contains(text, "aeDefaultSweepParams()"), ...
        '%s must use the shared AE sweep defaults.', cases(i).entrypoint);
    assert(contains(text, "aeDefaultSweepOptions(""Robust"")"), ...
        '%s must preserve the maintained Robust example profile.', cases(i).entrypoint);
    assert(contains(text, "aeRunSweep(baseParams, """ + cases(i).field + """"), ...
        '%s must sweep the expected physical field.', cases(i).entrypoint);
    assert(contains(text, "aeWriteSweepOutputs"), ...
        '%s must use the maintained AE output writer.', cases(i).entrypoint);
    assert(contains(text, """" + cases(i).taskName + """"), ...
        '%s must use the expected output task name.', cases(i).entrypoint);
    assert(contains(text, "aePlotSweepCp"), ...
        '%s must use the maintained AE sweep plot helper.', cases(i).entrypoint);
    assert(contains(text, "aeSaveExampleFigure"), ...
        '%s must use the maintained AE figure writer.', cases(i).entrypoint);
end

fprintf('AE physical sweep example contract test passed.\n');
end

function c = makeCase(entrypoint, field, rangeText, taskName)
c = struct( ...
    'entrypoint', string(entrypoint), ...
    'field', string(field), ...
    'rangeText', string(rangeText), ...
    'taskName', string(taskName));
end