function result = rlBuildResult(params, options, material, geometry, frequency_Hz, modes, approximations, elapsedSeconds)
%RLBUILDRESULT Construct the canonical Rayleigh-Lamb scientific result.

result = struct();
result.model = "rayleigh_lamb";
result.modes = modes;
result.approximations = approximations;
result.quality = lamb.models.rayleigh_lamb.quality.rlEvaluateModeQuality(modes);
result.material = material;
result.geometry = rmfield(geometry, 'halfThickness');

effectiveParameters = params;
effectiveParameters.frequency_Hz = frequency_Hz(:);
result.configuration = struct( ...
    'requested', struct('parameters', params, 'options', options), ...
    'effective', struct( ...
        'parameters', effectiveParameters, ...
        'options', options));
result.execution = struct( ...
    'engine', "independent_continuation", ...
    'elapsedSeconds', elapsedSeconds, ...
    'computedBranches', string(fieldnames(modes)).');
result.diagnostics = struct( ...
    'angularFrequency_radps', 2*pi*frequency_Hz(:));
end
