function fig = plotParametricSweepCp(sweepResults, modelName, branchName, varargin)
%PLOTPARAMETRICSWEEPCP Plot RL/mRLFE sweep curves with the shared renderer.
%
% Supported maintained model names include RayleighLamb, mRLFERealK, and
% mRLFEViscoRealK. The function adapts runParametricSweep output to the
% neutral plotSweepCpFigure contract.

p = inputParser;
addParameter(p, 'Title', "", @(x)ischar(x) || isstring(x) || iscellstr(x));
addParameter(p, 'NewFigure', true, @(x)islogical(x) || isnumeric(x));
addParameter(p, 'ShowLastValidPoint', false, @(x)islogical(x) || isnumeric(x));
addParameter(p, 'LastValidPointMarkerSize', 7, @(x)isnumeric(x) && isscalar(x));
addParameter(p, 'FrequencyScale', 1, @(x)isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'FrequencyUnit', "Hz", @(x)ischar(x) || isstring(x));
addParameter(p, 'StartFrequencyAtZero', false, @(x)islogical(x) || isnumeric(x));
addParameter(p, 'StartCpAtZero', true, @(x)islogical(x) || isnumeric(x));
addParameter(p, 'ShowFixedParameters', true, @(x)islogical(x) || isnumeric(x));
addParameter(p, 'LineWidth', 1.8, @(x)isnumeric(x) && isscalar(x) && x > 0);
addParameter(p, 'LegendLocation', "southeast", @(x)ischar(x) || isstring(x));
parse(p, varargin{:});

plotData = buildParametricSweepPlotData(sweepResults, modelName, branchName);
fig = plotSweepCpFigure(plotData, ...
    'Title', p.Results.Title, ...
    'FigureName', string(modelName) + " sweep Cp", ...
    'NewFigure', p.Results.NewFigure, ...
    'ShowLastValidPoint', p.Results.ShowLastValidPoint, ...
    'LastValidPointMarkerSize', p.Results.LastValidPointMarkerSize, ...
    'FrequencyScale', p.Results.FrequencyScale, ...
    'FrequencyUnit', p.Results.FrequencyUnit, ...
    'StartFrequencyAtZero', p.Results.StartFrequencyAtZero, ...
    'StartCpAtZero', p.Results.StartCpAtZero, ...
    'ShowFixedParameters', p.Results.ShowFixedParameters, ...
    'LineWidth', p.Results.LineWidth, ...
    'LegendLocation', p.Results.LegendLocation);
end