function test_ae_analyze_sweep_reliability()
%TEST_AE_ANALYZE_SWEEP_RELIABILITY Focused behavioral test for sweep diagnostics.

summary = syntheticSummary();
source = summary;

analysis = aeAnalyzeSweepReliability(summary, ...
    'ExpectedDirection', "increasing", ...
    'Tolerance', 0, ...
    'Label', "synthetic");

assert(isequaln(summary, source), ...
    'Sweep reliability analysis must not modify its source summary.');
assert(height(analysis.truncationTable) == 2, ...
    'Expected one truncation row per sweep condition.');
assert(analysis.truncationTable.ValidFraction(1) == 0.75, ...
    'Canonical condition validity information must be preserved.');
assert(analysis.truncationTable.HasInternalGap(1), ...
    'The analyzer must identify an internal validity gap.');
assert(analysis.truncationTable.LastValidFrequency_kHz_FromDispersion(2) == 4, ...
    'The analyzer must compute each condition truncation limit from dispersion data.');

M = analysis.monotonicityTable;
assert(isequal(logical(M.SharedValid(:)).', [true false true true]), ...
    'Shared-frequency validity must require valid data from every condition.');
assert(isequal(logical(M.IsMonotonic(:)).', [true false true false]), ...
    'Shared-frequency monotonicity must expose both consistency and violations.');
assert(analysis.monotonicitySummary.SharedValidFrequencyCount == 3, ...
    'Unexpected shared-valid frequency count.');
assert(analysis.monotonicitySummary.MonotonicSharedFrequencyCount == 2, ...
    'Unexpected monotonic shared-frequency count.');

assert(~any(isfield(analysis, {'phaseVelocity_mps', 'validMask', 'branch'})), ...
    'Sweep diagnostics must not construct an alternate production branch.');

fprintf('test_ae_analyze_sweep_reliability passed.\n');
end

function summary = syntheticSummary()
conditionIndex = [1; 1; 1; 1; 2; 2; 2; 2];
sweepValue = [10; 10; 10; 10; 20; 20; 20; 20];
frequencyHz = repmat((1:4).' * 1e3, 2, 1);
cp = [10; nan; 12; 14; 11; 12; 13; 13];
valid = [true; false; true; true; true; true; true; true];

summary = struct();
summary.conditionTable = table((1:2).', [10; 20], [10; 20], ...
    ["10"; "20"], ["synthetic"; "synthetic"], ["IOP"; "IOP"], ...
    [0.75; 1], [4; 4], ...
    'VariableNames', {'ConditionIndex', 'SweepValue', 'SweepValueScaled', ...
    'SweepValueDisplay', 'SweepName', 'SweepField', 'ValidFraction', ...
    'LastValidFrequency_kHz'});
summary.dispersionTable = table(conditionIndex, ...
    repmat(["synthetic"; "synthetic"; "synthetic"; "synthetic"], 2, 1), ...
    repmat(["IOP"; "IOP"; "IOP"; "IOP"], 2, 1), ...
    sweepValue, string(sweepValue), frequencyHz, frequencyHz / 1e3, cp, valid, ...
    ones(8, 1), ones(8, 1), ...
    'VariableNames', {'ConditionIndex', 'SweepName', 'SweepField', ...
    'SweepValue', 'SweepValueDisplay', 'Frequency_Hz', 'Frequency_kHz', ...
    'Cp_mps', 'validCp', 'objective', 'nearestRank'});
summary.branchTable = table();
end
