function seed = mrlfeBuildSeed(problem, configuration)
%MRLFEBUILDSEED Build the production seed for an mRLFE branch.

seed = mrlfeMakePhysicalSeedMode(configuration.branch, ...
    problem.frequencySolve_Hz(:), ...
    problem.material, ...
    problem.geometry, ...
    problem.seedModes);
end
