function fitOutput = rlGuiFitSolver(request)
%R LGUIFITSOLVER Run Rayleigh-Lamb fitting from an app-level request.

request = guiBuildFitRequest(request.modelFamily, ...
    'branchName', request.branchName, 'mode', request.mode, ...
    'experimental', request.experimental, 'fixedParams', request.fixedParams, ...
    'freeParams', request.freeParams, 'initialGuess', request.initialGuess, ...
    'bounds', request.bounds, 'controls', request.controls, ...
    'fitOptions', request.fitOptions, 'outputMode', request.outputMode);
branchName = string(request.branchName);
if strlength(branchName) == 0, branchName = "A0"; end
if ~(branchName == "A0" || branchName == "S0")
    error('Unsupported Rayleigh-Lamb fitting branchName. Use A0 or S0.');
end
controls = request.controls;
[solverOptions, profileMetadata] = rlResolveExecutionProfile(controls, ...
    'DefaultProfile', "Fast", 'DefaultSource', "FitTool default");
controls.executionProfile = profileMetadata.requestedExecutionProfile;
request.controls = controls;
fitConfig = struct('branchName', branchName, 'freeParams', request.freeParams, ...
    'fixedParams', request.fixedParams, 'initialGuess', request.initialGuess, ...
    'bounds', request.bounds, 'solverOptions', solverOptions, 'fitOptions', request.fitOptions);
tFit = tic;
fitResult = lamb.fitting.rayleigh_lamb.rlFitDispersionData(request.experimental, fitConfig);
fitElapsedSeconds = toc(tFit);
normalized = guiNormalizeFitResult(fitResult, request);
normalized.executionProfile = profileMetadata;
normalized.fullCurve.executionProfile = profileMetadata;
normalized.fitElapsedSeconds = fitElapsedSeconds;
fitOutput = struct('request', request, 'modelFamily', "rayleigh_lamb", ...
    'modelName', "RayleighLamb", 'branchName', branchName, 'fitResult', fitResult, ...
    'normalized', normalized, 'executionProfile', profileMetadata, ...
    'fitElapsedSeconds', fitElapsedSeconds);
end
