function test_acoustoelastic_iop_hgo_short_entrypoints()
%TEST_ACOUSTOELASTIC_IOP_HGO_SHORT_ENTRYPOINTS Verify short AE entrypoints are on path.
%
% This is a path-level smoke test only. It does not execute heavy diagnostics.
% It also checks that remaining example wrappers using aeRunLegacyScript point
% to an existing script file.

requiredNames = [ ...
    "aeOutputFolder", ...
    "aeResolveResultFile", ...
    "aeRunLegacyScript", ...
    "aeCopyLegacyResultFolder", ...
    "aeClassifyAmbiguityRegime", ...
    "run_atlas_branch", ...
    "sweep_iop", ...
    "sweep_mu", ...
    "validate_idA0_score_grid", ...
    "validate_idA0_grid", ...
    "compare_branch_policies", ...
    "compare_atlasA0_vs_raw_branch1", ...
    "validate_atlas_raw_grid", ...
    "diagnose_raw_branch_corner", ...
    "diagnose_branch_families", ...
    "diagnose_branch_policy", ...
    "diagnose_sweep_reliability", ...
    "diagnose_truncation_cases", ...
    "diagnose_branch_persistence", ...
    "diagnose_atlas_truncation", ...
    "diagnose_atlas_resolution", ...
    "diagnose_landscape_failure", ...
    "diagnose_idA0_score", ...
    "diagnose_idA0_plausibility", ...
    "diagnose_modal_atlas", ...
    "diagnose_modal_atlas_lowfreq", ...
    "track_raw_branch1" ...
    ];

for i = 1:numel(requiredNames)
    entryPath = which(requiredNames(i));
    assert(~isempty(entryPath), 'Missing short AE entrypoint/helper on MATLAB path: %s', requiredNames(i));
    validateLegacyTargetIfExampleWrapper(requiredNames(i), entryPath);
end

fprintf('Short acoustoelastic IOP/HGO entrypoint path test passed. Example legacy wrapper targets verified where present.\n');
end

function validateLegacyTargetIfExampleWrapper(entryName, entryPath)
%VALIDATELEGACYTARGETIFEXAMPLEWRAPPER Check simple static legacy targets.

[~, ~, ext] = fileparts(entryPath);
if ext ~= ".m"
    return;
end

pathForCheck = strrep(entryPath, '\\', '/');
if ~contains(pathForCheck, '/examples/acoustoelastic_iop_hgo/')
    return;
end

text = fileread(entryPath);
if ~contains(text, 'aeRunLegacyScript')
    return;
end

marker = "fullfile(thisFolder, '";
markerStart = strfind(text, marker);
assert(~isempty(markerStart), 'Short example entrypoint %s calls aeRunLegacyScript but no static legacy target was parsed.', entryName);

entryFolder = fileparts(entryPath);
for j = 1:numel(markerStart)
    nameStart = markerStart(j) + strlength(marker);
    tail = extractAfter(text, nameStart - 1);
    nameEnd = strfind(tail, "')");
    assert(~isempty(nameEnd), 'Short example entrypoint %s has an incomplete legacy target expression.', entryName);
    targetName = extractBefore(tail, nameEnd(1));
    if ~endsWith(targetName, ".m")
        continue;
    end
    targetPath = fullfile(entryFolder, char(targetName));
    assert(exist(targetPath, 'file') == 2, ...
        'Short example entrypoint %s points to missing legacy target: %s', entryName, targetPath);
end
end
