function test_ae_sensitivity_study_contract()
%TEST_AE_SENSITIVITY_STUDY_CONTRACT Validate maintained AE sensitivity campaigns.
%
% This is a lightweight source-level contract. It checks the public entrypoints,
% requested fields, ranges, units, and output task names without running the
% computationally expensive Robust sweeps.

repoRoot = testRepositoryRoot();
studyRoot = fullfile(repoRoot, 'studies', 'sensitivity', ...
    'acoustoelastic_iop_hgo');
studyPath = fullfile(studyRoot, 'runAcoustoelasticSensitivity.m');
oldModelPath = fullfile(repoRoot, 'src', '+lamb', '+models', '+acoustoelastic_iop_hgo', '+solvers', 'runAcoustoelasticSensitivity.m');
assert(isfile(studyPath), 'AE sensitivity orchestration must be study-owned.');
assert(~isfile(oldModelPath), 'Model code must not own sensitivity orchestration.');
assert(strcmp(which('runAcoustoelasticSensitivity'), studyPath), ...
    'AE sensitivity orchestration must resolve from its opt-in study owner.');
assert(~isfolder(fullfile(repoRoot, 'app', 'sweep')), ...
    'The retired SweepTool adapter tree must remain absent.');
assert(isempty(which('aePlotGridSweepFrequencySurfaceInteractive')), ...
    'The retired SweepTool interactive plot must not resolve.');

cases = makeCase("study_iop_A0Like", "IOP", ...
    "IOP_mmHg = [5, 10, 15, 20, 25]", "iop_sweep");

for i = 1:numel(cases)
    entryPath = fullfile(studyRoot, cases(i).entrypoint + ".m");
    assert(isfile(entryPath), ...
        'Missing maintained AE sweep entrypoint: %s.', cases(i).entrypoint);

    text = string(fileread(entryPath));
    expectedCall = string(sprintf('runAcoustoelasticSensitivity(baseParams, "%s"', cases(i).field));
    expectedTask = string(sprintf('"%s"', cases(i).taskName));

    assert(contains(text, cases(i).rangeText), ...
        'Unexpected sweep range in %s.', cases(i).entrypoint);
    assert(contains(text, "acoustoelasticSensitivityParameters()"), ...
        '%s must use the shared AE sweep defaults.', cases(i).entrypoint);
    assert(contains(text, "acoustoelasticSensitivityOptions(""Robust"")"), ...
        '%s must preserve the maintained Robust example profile.', cases(i).entrypoint);
    assert(contains(text, expectedCall), ...
        '%s must sweep the expected physical field.', cases(i).entrypoint);
    assert(contains(text, "writeAcoustoelasticSensitivityOutputs"), ...
        '%s must use the maintained AE output writer.', cases(i).entrypoint);
    assert(contains(text, expectedTask), ...
        '%s must use the expected output task name.', cases(i).entrypoint);
    assert(contains(text, "plotAcoustoelasticSensitivity"), ...
        '%s must use the maintained AE sweep plot helper.', cases(i).entrypoint);
    assert(contains(text, "saveAcoustoelasticStudyFigure"), ...
        '%s must use the maintained AE figure writer.', cases(i).entrypoint);
end

assert(isfile(fullfile(studyRoot, 'study_mu_iop_A0Like.m')), ...
    'Missing maintained AE combined mu-IOP sweep entrypoint.');
assertObsoleteEntrypointsAreAbsent([ ...
    "sweep_iop", ...
    "sweep_mu", ...
    "sweep_thickness", ...
    "sweep_k1", ...
    "sweep_k2", ...
    "sweep_radius", ...
    "sweep_mu_iop" ...
    ]);
assertObsoleteEntrypointsAreAbsent([ ...
    "rlRunSweep", "mrlfeRunSweep", "aeRunSweep", "aeRunGridSweep"]);

fprintf('AE sensitivity study contract passed.\n');
end

function assertObsoleteEntrypointsAreAbsent(names)
for i = 1:numel(names)
    assert(isempty(which(names(i))), ...
        'Obsolete AE sweep entrypoint should not resolve on the MATLAB path: %s.', names(i));
end
end

function c = makeCase(entrypoint, field, rangeText, taskName)
c = struct( ...
    'entrypoint', string(entrypoint), ...
    'field', string(field), ...
    'rangeText', string(rangeText), ...
    'taskName', string(taskName));
end
