function aeOptions = aeGuiBuildOptions(executionProfile)
%AEGUIBUILDOPTIONS Build AE options for the solver GUI.
[aeOptions, profileMetadata] = aeResolveExecutionProfile(executionProfile, ...
    'DefaultProfile', "Balanced", ...
    'DefaultSource', "Solver GUI default", ...
    'Surface', "SolverGUI");
aeOptions.executionProfileMetadata = profileMetadata;
end
